### ISSUE TITLE
Do both of 'en_core_sci_sm' and 'en_core_sci_md' use MedMentions all dataset?

### ISSUE THREAD

**Issue by izuna385** [allenai/scispacy#126]
Thanks for developing nice and useful library.
My question is , do both of 'en_core_sci_sm' and 'en_core_sci_md' use MedMentions all dataset?
Because my task is related to MedMentions dataset itself, so I can only use MedMentions train dataset.
If 'en_core_sci_sm' or 'en_core_sci_md' only used MedMentions train datasets, it's OK. But if datasets including dev/test data are used for training model, I can't use it because my task is related to datasets itself.

Or, how can I retrain spacy model?  If these model use MedMentions all(including dev/test) data, I'd like to create model all over again.

**Comment by DeNeutoy** [comment]
Oh, naturally we only used the training set to train the models on - the development and test sets are only used for validation. You're definitely safe to use them on medmentions!

**Comment by izuna385** [comment]
Great!  Again, thanks.

**Comment by DeNeutoy** [comment]
Great - also please let us know any feedback you have when using the models, or additional features you'd love. 

I'm not sure what task you are working on (entity linking maybe?) but you might also be interested in the knowledge base we have curated from UMLS - it is quite large and covers 99.9% of the entities which occur in the MedMentions annotations.

You can read more about it here:
https://github.com/allenai/scispacy#umlsentitylinker-alpha-feature

**Comment by izuna385** [comment]
I'm using scispacy mainly for sbd, but yes I'm much interested in Entity typing and linking.
I'll try that, thanks!

In trying sbd with `en_core_sci_md`', scispacy performs well.
However, there's some minor tokenization problem and if custom rules are added, it can be prevented.
https://gist.github.com/izuna385/512a9c62868c751a8290a9676f994d16
(Maybe this isn't scispacy's problem.)
