### ISSUE TITLE
Can scispacy models be used in spacy without having installed the additional requirements?

### ISSUE THREAD

**Issue by erotavlas** [allenai/scispacy#130]
I noticed that the models can be loaded into spacy without the need to install the scispacy package and all its requirements (i.e. just install spacy on its own and load your models).  Is there any problem with this? What do the other requirements do and can we use the models without installing these packages?

> numpy
> spacy>=2.1.3
> pandas
> awscli
> conllu
> 
> Candidate generation and entity linking
> joblib
> nmslib>=1.7.3.6
> scikit-learn>=0.20.3

**Comment by DeNeutoy** [comment]
Hmm I believe this would work (i.e have no dependency at all on the actual scispacy library) if we removed this line: 

https://github.com/allenai/scispacy/blob/master/proto_model/__init__.py#L7

This might actually be quite a good solution, as we currently don't even use this custom segmenter.

Yes, the other dependencies are just for the entity linking/candidate generation step, which is a little more involved. 

Let me think a bit about making the package not rely on these.

**Comment by danielkingai2** [comment]
seems fine to just remove that line, i think. the sentence segmenter (even though it is unused at the moment) could just be the same type of optional component as the linker and abbreviation detector. And that could be the general paradigm for all the extra pipes, that they are optional stuff that can be added. That seems fine to me.

**Comment by mrxiaohe** [comment]
Just wanted to check if it is indeed possible to load `scispacy` models without installing `scispacy`. I've been having trouble installing `nmslib`. I tried loading a couple of the models, but was met with an error message saying `scispacy` was not installed.
