### ISSUE TITLE
Efficient Computation of Similarity Matrix for Set of Documents? 

### ISSUE THREAD

**Issue by meaningfromdata** [allenai/scispacy#138]
Do you have any suggestions on how to efficiently compute the pairwise similarity over a large  set of tokens/sentences/documents using the scispacy en_core_sci_md vectors?  I'm finding the method suggested by the spacy documentation ((https://spacy.io/usage/vectors-similarity) to be extremely slow and resource intensive.

**Comment by DeNeutoy** [comment]
Hi!

To do this faster, you should batch them together and compute the result using a matrix multiplication, which you can speed up by using a GPU, for example.

More generally you should be a little careful of relying on the document vectors of spacy models, as I think they are just word vector averages. Also note that the scispacy med model only has 20k vectors, which is not a huge amount, so many words will be OOV (i.e not have a vector). Is a large model (~2GB with vectors) something that you would be interested in?

**Comment by meaningfromdata** [comment]
Thanks for reply.  This post on stackexchange which uses matrix multiplication via numpy is significantly boosting speed: https://stackoverflow.com/questions/41905029/create-cosine-similarity-matrix-numpy?rq=1

I would be interested in larger vector models.  I realize there are caveats to using them but am trying to pair them with other features to cluster/classify biomedical documents.

**Comment by DeNeutoy** [comment]
Cool, i'll bear that in mind for what to work on for the next release!
