### ISSUE TITLE
most/least similar tokens (like gensim)?

### ISSUE THREAD

**Issue by meaningfromdata** [allenai/scispacy#139]
Is there some way to return the n most/least similar tokens to a given token in the en_core_sci_md vocabulary?  In gensim the most_similar method allows you to do this.

**Comment by DeNeutoy** [comment]
Hey, you might find it easiest to just extract the vectors and words from the vocabulary and put them into a gensim model. We used the vectors found on this page:

http://bio.nlplab.org/

**Comment by meaningfromdata** [comment]
Ok, thanks for reply and link.
