### ISSUE TITLE
How to get dependency parse annotation from OntoNotes 5.0 corpus?

### ISSUE THREAD

**Issue by phiedulxp** [allenai/scispacy#142]
As mention in paper:
`To increase the robustness of the dependency parser and POS tagger to generic text,
we make use of the OntoNotes 5.0 corpus`
I can only find the Constituency parse annotation.

**Comment by DeNeutoy** [comment]
Closed offline.

**Comment by DeNeutoy** [comment]
I sent you an email, if you didn't get it let me know!

**Comment by phiedulxp** [comment]
Thanks, I have tried StanfordNLP converter for other to generate UD annotaions.
