### ISSUE TITLE
More Tutorials for SciSpacy

### ISSUE THREAD

**Issue by dusadvarshit** [allenai/scispacy#143]
Hello SciSpacy team,

Thank you for building sci-spacy.
I just wanted to say that it would be very helpful if there were more examples/jupyter notebooks available to learn diverse use cases of sci-spacy.
Please let me know where can I find complete sci-spacy documentation.

**Comment by DeNeutoy** [comment]
Hi!

Thanks for your interest in the project.

Currently you can use scispacy in the same way as other spacy models, so you can look at the spacy tutorials and the core pipelines should work in exactly the same way.

If you have any specifics that you found hard to get started with, we could definitely write some tutorials for the non-standard parts of the library. Was there something in particular you found tricky?

**Comment by dusadvarshit** [comment]
Hi Mark,

Thank you very much for your reply.

I am very new to sci-spacy and honestly, do not have much experience with
spacy either.
I am just very curious of the current breadth of features available in
sci-spacy. Until now, I have used the abbreviation feature and UMLS linker
feature. I assume native spacy do not have UMLS linker, and this is
precisely my motivation for asking the above question. What are the bionlp
specific use cases sci-spacy can currently handle which are not available
in native spacy? Because there are only two examples it is hard to realize
the full potential of sci-spacy.
I attempted the examples on github-repo page and was able to replicate the
results so no issues there.
I believe that sci-spacy can do a good name-entity recognition specific to
biomedical domains though I have yet to test it myself. However, I wonder
can I use it to pre-process text to remove biomedical stopwords, or
generate word embeddings. I am not saying I request these features if not
available but it would be great to have an understanding of the full extent
of capabilities of sci-spacy especially for users who are new to BioNLP
such as myself.

Thank you for your reply and also for developing sci-spacy in first place!

Warm regards,
Varshit Dusad

**Comment by himanshumohan19** [comment]
Hi, I also like to know answer if above qs

**Comment by himanshumohan19** [comment]
Hi Dan,
Thanks for the input. I am working on a medical use case and i need some inputs :
1. Is there a licence needed to use Scispacy and Spacy in our application in production to be hosted on AWS ?
2. We are building a NLP pipeline in which last step is to put the medical abstract text into LDA for unsupervised clustering in order to find most relevant medical abstract based on medical search terms I have following issue ..i am unable to figure out how to pass the 'Doc' data structure to LDA algorithm and also do you have a medical LDA ..as current LDA are based out of english non medical text learning nning

**Comment by danielkingai2** [comment]
1. Spacy is licensed under the MIT License (https://github.com/explosion/spaCy/blob/master/LICENSE) and scispaCy is licensed under the Apache License 2.0 (https://github.com/allenai/scispacy/blob/master/LICENSE).
2. See https://github.com/allenai/scispacy/issues/219
