### ISSUE TITLE
Sentence segmenter can not be loaded

### ISSUE THREAD

**Issue by yuhui-zh15** [allenai/scispacy#149]
Hello,

I ran the following commands to train the parser:

```sh
bash ./scripts/base_model.sh small base_model
bash ./scripts/parser.sh base_model parser
```

When I used the following commands to load the trained parser, the sentence segmenter does not work:

```python
import spacy
nlp = spacy.load('parser/best')
x = nlp('Hello. Hello.')
print(len(list(x.sents)) # Output: 1, Expected: 2
```

However, when I followed the code and added the segmenter to the pipeline, the sentense segmenter still does not work:

```python
import spacy
from scispacy.custom_sentence_segmenter import combined_rule_sentence_segmenter
nlp = spacy.load('parser/best')
nlp.add_pipe(combined_rule_sentence_segmenter, first=True)
x = nlp('Hello. Hello.')
print(len(list(x.sents)) # Output: 1, Expected: 2
```

What should I do to add the sentence segmenter into pipeline? 

Thanks!

**Comment by DeNeutoy** [comment]
Does it not work at all, even for more normal sentences?

**Comment by yuhui-zh15** [comment]
Yes, it does not work on all sentences.

**Comment by DeNeutoy** [comment]
No problem, glad you fixed it!
