### ISSUE TITLE
Abbreviations and UMLS linking

### ISSUE THREAD

**Issue by rdaniel** [allenai/scispacy#150]
Here's a test sentence:

Human induced pluripotent stem cells (hiPSC) are generated from reprogrammed fibroblasts by overexpression of pluripotency factors (Takahashi et al., 2007; Yu et al., 2007).

The abbreviation detector correctly identifies hiPSC and "Human induced pluripotent stem cells". Also, "Human induced pluripotent stem cells" is in UMLS as CUI C3658289. However, the UMLS linker does not find that code. Instead of the long form of the abbreviation being used (which is associated with the document), the linker is using the entities from the mention detector. In this case it had found the mentions (Human, induced, pluripotent stem cells, hiPSC, fibroblasts, overexpression, pluripotency factors, Takahashi). 
The result is that the abbreviation hiPSC gets candidate codes C2717959 and C0872076, which are for 'Induced Pluripotent Stem Cells' and 'Pluripotent Stem Cells', respectively.

It may be good to have an early step in the UMLS linker that looks for document-level abbreviations. If it finds some then exclude those spans from consideration when looking for non-abbreviated mentions.  (Or maybe let people ask for nested concepts, in which case the abbreviation spans would not be excluded).

**Comment by DeNeutoy** [comment]
Hi! Good news - we have that functionality already!

https://github.com/allenai/scispacy#umlsentitylinker-alpha-feature

if you set `resolve_abbreviations : bool = True` and add the [abbreviation detector](https://github.com/allenai/scispacy#abbreviationdetector) to the pipeline _before_ the linker, the linker will use the long forms of any abbreviations that it finds.

**Comment by rdaniel** [comment]
Hi Mark,

Thanks for your prompt reply. My apologies for taking a few days to reply.

I think I am already using resolve_abbreviations=True in the proper manner.
Here’s a bit of test code and output. Note that the abbreviations code does find ‘Human induced pluripotent stem cells’ as the long form for hiPSC, but the UMLS codes for hiPSC don’t include that one.



# Test of scispacy to see problem where it doesn't find

#  CUI C3658289 for Human Induced Pluripotent stem cells.



import spacy

import scispacy

from scispacy.abbreviation import AbbreviationDetector

from scispacy.umls_linking import UmlsEntityLinker



nlp = spacy.load("en_core_sci_sm")

abbreviation_pipe = AbbreviationDetector(nlp)

nlp.add_pipe(abbreviation_pipe)

linker = UmlsEntityLinker(resolve_abbreviations=True)

nlp.add_pipe(linker)



text1 = "Human induced pluripotent stem cells (hiPSC) are generated from "\

"reprogrammed fibroblasts by overexpression of pluripotency factors.\n"



# Process the text w/ full SciSpacy pipeline

print("Pipeline: ", nlp.pipe_names)

doc1 = nlp(text1)

print("Abbreviations:")

for a in doc1._.abbreviations:

    print(a, a._.long_form)



print("\nEntities: ", doc1.ents)



# Comment out next block and uncomment loop below it to see all UMLS entities.

entity = doc1.ents[3]    # for the hiPSC case

print("Entity Name: ", entity)

for umls_ent in entity._.umls_ents:

    print("\t", linker.umls.cui_to_entity[umls_ent[0]])

$ python test_abbrv.py
Pipeline:  ['tagger', 'parser', 'ner', 'AbbreviationDetector', 'UmlsEntityLinker']
Abbreviations:
hiPSC Human induced pluripotent stem cells

Entities:  (Human, induced, pluripotent stem cells, hiPSC, fibroblasts, overexpression, pluripotency factors)
Entity Name:  hiPSC
       CUI: C2717959, Name: Induced Pluripotent Stem Cells
Definition: Cells from adult organisms that have been reprogrammed into a pluripotential state similar to that of EMBRYONIC STEM CELLS.
TUI(s): T025
Aliases: (total: 6):
       Induced Pluripotent Stem Cell, iPSC, IPS Cells, Cell, IPS, IPS Cell, Cells, IPS
       CUI: C0872076, Name: Pluripotent Stem Cells
Definition: Cells that can give rise to cells of the three different GERM LAYERS.
TUI(s): T025
Aliases (abbreviated, total: 12):
       Pluripotent Stem Cells, pluripotent stem cells, pluripotent stem cell, pluripotent stem cell, pluripotent stem cell, Pluripotent Stem Cell, Pluripotent Stem Cell, Stem Cell, Pluripotent, Pluripotent stem cell, Pluripotent stem cell
(scispacy) ELSSLCM-4176012:scispacy danielr$

Best regards,

Ron Daniel, Ph.D.
Director, Elsevier Labs | ELSEVIER
+1 619 208 3064 | r.daniel@elsevier.com<mailto:r.daniel@elsevier.com>

**Comment by DeNeutoy** [comment]
Thanks for the snippet! We actually figured out this was a combination of two problems:

1. We filter for entities which have definitions in the KnowledgeBase, because over 80% of mentions typically should prefer an entity with a definition. However, it was a bit dumb to filter these out when there is an exact string match, so I fixed this part in #153.

2. The second part is that if the mention detector goes a bit wrong and splits up a long entity into several separate ones, we should be able to use the abbreviation detector to fix those cases. We haven't done this yet, but we opened an issue for it here: #152 .

Thanks for the useful error cases!

**Comment by rdaniel** [comment]
Hi Mark,

Thank *you* for the super-fast debugging of that issue, and the quick fix when there is a known long form. Looking forward to the other fix too.


Best regards,

Ron Daniel, Ph.D.
Director, Elsevier Labs | ELSEVIER
+1 619 208 3064 | r.daniel@elsevier.com<mailto:r.daniel@elsevier.com>

**Comment by danielkingai2** [comment]
Closing this issue as part of it was fixed, and the other part is in #152
