### ISSUE TITLE
UmlsEntityLinker terminated by signal SKGKILL

### ISSUE THREAD

**Issue by fireholder** [allenai/scispacy#166]
when i run `linker  = UmlsEnitityLinker(resolve_abbreviations=True)` it was forced to be killed.

**Comment by DeNeutoy** [comment]
Hi! Normally this means that you have run out of memory. Perhaps checking that might help? Additionally, it's worth checking that `nmslib` is installed correctly. It is a c++ library and so might have segfaulted etc. can you use `nmslib` directly in a python shell?

**Comment by fireholder** [comment]
I just did what the demo did but it doesn't work, and I can't figure out why my memory run out.  I do have installed nmslib and I can import it. Does it mean I have installed it correctly?

**Comment by danielkingai2** [comment]
@fireholder was this issue also resolved by downgrading spacy version (similar to #167) or are you still facing this issue as well?

**Comment by fireholder** [comment]
@danielkingai2 Yes, I'm still facing this issue.

**Comment by danielkingai2** [comment]
Could you provide the output of `pip list` along with the full code snippet that is failing?

**Comment by fireholder** [comment]
@danielkingai2 
my pip list is as follows:
`absl-py (0.8.0)
apturl (0.5.2)
asn1crypto (0.24.0)
astor (0.8.0)
attrs (19.1.0)
awscli (1.16.248)
backcall (0.1.0)
bleach (3.1.0)
blis (0.4.1)
botocore (1.12.238)
Brlapi (0.6.6)
certifi (2019.9.11)
chardet (3.0.4)
colorama (0.3.9)
command-not-found (0.3)
conllu (2.0)
cryptography (2.1.4)
cupshelpers (1.0)
cymem (2.0.2)
decorator (4.4.0)
defer (1.0.6)
defusedxml (0.6.0)
distro-info (0.18ubuntu0.18.04.1)
docutils (0.15.2)
en-core-sci-lg (0.2.3)
en-core-sci-md (0.2.3)
en-core-sci-sm (0.2.3)
en-ner-bionlp13cg-md (0.2.3)
entrypoints (0.3)
gast (0.3.2)
google-pasta (0.1.7)
grpcio (1.24.0)
Guake (3.0.5)
h5py (2.10.0)
httplib2 (0.9.2)
idna (2.8)
ipykernel (5.1.2)
ipython (7.8.0)
ipython-genutils (0.2.0)
ipywidgets (7.5.1)
jedi (0.15.1)
Jinja2 (2.10.1)
jmespath (0.9.4)
joblib (0.13.2)
jsonschema (3.0.2)
jupyter (1.0.0)
jupyter-client (5.3.3)
jupyter-console (6.0.0)
jupyter-core (4.5.0)
Keras-Applications (1.0.8)
Keras-Preprocessing (1.1.0)
keyring (10.6.0)
keyrings.alt (3.0)
language-selector (0.1)
launchpadlib (1.10.6)
lazr.restfulclient (0.13.5)
lazr.uri (1.0.3)
louis (3.5.0)
macaroonbakery (1.1.3)
Mako (1.0.7)
Markdown (3.1.1)
MarkupSafe (1.1.1)
mistune (0.8.4)
murmurhash (1.0.2)
nbconvert (5.6.0)
nbformat (4.4.0)
netifaces (0.10.4)
nmslib (1.8.1)
notebook (6.0.1)
numpy (1.17.2)
oauth (1.0.1)
olefile (0.45.1)
pandocfilters (1.4.2)
parso (0.5.1)
pbr (3.1.1)
pexpect (4.7.0)
pickleshare (0.7.5)
Pillow (6.1.0)
pip (9.0.1)
plac (0.9.6)
preshed (3.0.2)
prometheus-client (0.7.1)
prompt-toolkit (2.0.9)
protobuf (3.9.2)
ptyprocess (0.6.0)
pyasn1 (0.4.7)
pybind11 (2.4.2)
pycairo (1.16.2)
pycrypto (2.6.1)
pycups (1.9.73)
Pygments (2.4.2)
pygobject (3.26.1)
pymacaroons (0.13.0)
PyNaCl (1.1.2)
pyRFC3339 (1.0)
pyrsistent (0.15.4)
python-apt (1.6.4)
python-dateutil (2.8.0)
python-debian (0.1.32)
pytz (2018.3)
pyxdg (0.25)
PyYAML (5.1.2)
pyzmq (18.1.0)
qtconsole (4.5.5)
reportlab (3.4.0)
requests (2.22.0)
requests-unixsocket (0.1.5)
rsa (3.4.2)
s3transfer (0.2.1)
scikit-learn (0.21.3)
scipy (1.3.1)
scispacy (0.2.3)
screen-resolution-extra (0.0.0)
SecretStorage (2.3.1)
Send2Trash (1.5.0)
setuptools (41.2.0)
simplegeneric (0.8.1)
simplejson (3.13.2)
six (1.12.0)
spacy (2.1.8)
srsly (0.1.0)
system-service (0.3)
systemd-python (234)
tensorboard (1.14.0)
tensorflow (1.14.0)
tensorflow-estimator (1.14.0)
tensorflow-gpu (1.14.0)
termcolor (1.1.0)
terminado (0.8.2)
testpath (0.4.2)
thinc (7.1.1)
torch (1.2.0)
torchvision (0.4.0)
tornado (6.0.3)
tqdm (4.36.1)
traitlets (4.3.2)
ubuntu-drivers-common (0.0.0)
ufw (0.36)
unattended-upgrades (0.1)
urllib3 (1.25.6)
usb-creator (0.3.3)
wadllib (1.3.2)
wasabi (0.2.2)
wcwidth (0.1.7)
webencodings (0.5.1)
Werkzeug (0.16.0)
wheel (0.33.6)
widgetsnbextension (3.5.1)
wrapt (1.11.2)
xkit (0.0.0)
zope.interface (4.3.2)`

and my full code snippet is :
`In [1]: import spacy                                                            

In [2]: import scispacy                                                         

In [3]: from scispacy.umls_linking import UmlsEntityLinker                                                               

In [4]: nlp = spacy.load('en_core_sci_sm')                                      

In [5]: linker = UmlsEntityLinker(resolve_abbreviations=True)                   
fish: “ipython” terminated by signal SIGKILL (Forced quit)
`

**Comment by danielkingai2** [comment]
This is quite likely an out of memory error. Could you check memory usage while that command is run? And how much memory does the machine you are running it on have?

**Comment by fireholder** [comment]
I have a machine of of 8G memory, and I only used firefox when the command was run. @danielkingai2

**Comment by danielkingai2** [comment]
It would still be helpful if you could check memory usage (on linux: htop, on windows: task manager, on mac: activity monitor) while running the command, just so we can confirm that out of memory is the issue versus something else.

**Comment by fireholder** [comment]
It used at least 4G memory. @danielkingai2

**Comment by danielkingai2** [comment]
Could you try this again in a clean conda environment? I'd like to know if the latest updates to `nmslib` resolved your issue.

**Comment by DeNeutoy** [comment]
Unfortunately I think this is just a straightforward lack of memory - please re-open if you find it actually is something more severe. Thanks!
