### ISSUE TITLE
 [E167] Unknown morphological feature: 'ConjType'

### ISSUE THREAD

**Issue by fireholder** [allenai/scispacy#167]
When I run `nlp(doc)` I got error: 
 ` [E167] Unknown morphological feature: 'ConjType' (9141427322507498425). This can happen if the tagger was trained with a different set of morphological features. If you're using a pretrained model, make sure that your models are up to date:
python -m spacy validate`
some of the docs work while some don't.

**Comment by danielkingai2** [comment]
Could you please provide the output of running `pip list`? I suspect your model version and scispacy version are out of sync.

**Comment by mdarcy220** [comment]
I have a similar issue with spacy=2.2.1, scispacy=0.2.3, en-core-sci-sm=0.2.3. I believe this stems from the [spacy 2.2.0 release](https://github.com/explosion/spaCy/releases/tag/v2.2.0), which is not backward compatible with old models. Downgrading to spacy 2.1.8 seems to fix it in my case.

**Comment by danielkingai2** [comment]
Ah, that is probably correct, thanks! We will have to retrain the models. @fireholder for now, please see if downgrading spacy to 2.1.8 solves your problems

**Comment by fireholder** [comment]
Yes, downgrading does work. Thanks~

**Comment by epurdy** [comment]
Can you please update scispacy to work with the current spacy?

**Comment by fireholder** [comment]
@epurdy  No, when I update to spacy 2.2.1, it still doesn't work.

**Comment by danielkingai2** [comment]
We are working on updating it, not sure of an ETA, there are a few issues we have to work through.

**Comment by danielkingai2** [comment]
One issue we are facing is a bug with the latest spacy, so we will have to wait on them to release the fix for that, at a minimum.

**Comment by itssantosh** [comment]
**scispacy 0.2.3-unreleased has requirement spacy>=2.2.1, but you'll have spacy 2.1.8 which is incompatible.**

I tried to downgrade my spacy from 2.2.1 to 2.1.8 but I got above error .Kindly help me resolve .
![Screenshot (3)](https://user-images.githubusercontent.com/27534184/67003511-bd9ab100-f0fb-11e9-951e-b2cb14392148.png)

**Comment by danielkingai2** [comment]
We haven't finished updating scispacy to be compatible with spacy 2.2.1 yet. It seems that you have installed scispacy from source. I would suggest installing the released version with `pip` from pypi with `pip install scispacy`. As for the permission error, likely the solutions [here](https://stackoverflow.com/questions/51912999/could-not-install-packages-due-to-an-environmenterror-winerror-5-access-is-de/57132010) will help you out

**Comment by jack-rory-staunton** [comment]
Just to chime in, I'm also getting this same error 
en-core-sci-lg                    0.2.3 
scispacy                              0.2.3
spacy                                   2.2.1
looking forward to trying out the scispacy models :)

**Comment by danielkingai2** [comment]
you'll need to downgrade spacy to 2.1.8 for now, we're working on it though :)

**Comment by danielkingai2** [comment]
Closing as `scispacy == 0.2.4` is live and is compatible with `spacy == 2.2.1`

**Comment by manvendrautralia** [comment]
Worked for me with Spacy2.2.3 also. Worked with using en_core_web_sm-2.2.5.

**Comment by Raghu17s** [comment]
Any updates on this.
spacy == 2.2.1 with scispacy==0.2.4 also has issue.
