### ISSUE TITLE
Transfer Learning using a scispacy model 

### ISSUE THREAD

**Issue by rohittilwani** [allenai/scispacy#179]
I have installed the scispacy model "en_core_sci_lg" for biomedical NER. I want to train it over my custom biomedical data. How can it be achieved. When trying to further train like other spacy models, i am getting the error as follows:

proc.update(docs, golds, sgd=get_grads, losses=losses, **kwargs)
  File "nn_parser.pyx", line 431, in spacy.syntax.nn_parser.Parser.update
  File "_parser_model.pyx", line 299, in spacy.syntax._parser_model.ParserStepModel.begin_update.backprop_parser_step
ValueError: operands could not be broadcast together with shapes (776,14) (13,) (776,14)

**Comment by danielkingai2** [comment]
A couple of questions:
(1) Could you provide the output of `pip list` in your environment so I can see what version of everything you have?
(2) Are you able to train the standard spacy models with your data?

**Comment by rohittilwani** [comment]
Yes, i am able to train the standard spacy "en_core_web_sm" model with my data.
 
The output of "pip list" is as follows:

Package                            Version   
---------------------------------- ----------
absl-py                            0.7.1     
alabaster                          0.7.12    
anaconda-client                    1.7.2     
anaconda-project                   0.8.2     
asn1crypto                         0.24.0    
astor                              0.8.0     
astroid                            2.1.0     
astropy                            3.1       
atomicwrites                       1.2.1     
attrs                              18.2.0    
awscli                             1.16.261  
Babel                              2.6.0     
backcall                           0.1.0     
backports.os                       0.1.1     
backports.shutil-get-terminal-size 1.0.0     
beautifulsoup4                     4.6.3     
bitarray                           0.8.3     
bkcharts                           0.2       
blaze                              0.11.3    
bleach                             3.0.2     
blis                               0.4.1     
bokeh                              1.0.2     
boto                               2.49.0    
botocore                           1.12.251  
Bottleneck                         1.2.1     
certifi                            2018.11.29
cffi                               1.11.5    
chardet                            3.0.4     
Click                              7.0       
cloudpickle                        0.6.1     
clyent                             1.2.2     
colorama                           0.4.1     
conllu                             2.2       
contextlib2                        0.5.5     
cryptography                       2.4.2     
cupy                               6.4.0     
cycler                             0.10.0    
cymem                              2.0.2     
Cython                             0.29.2    
cytoolz                            0.9.0.1   
dask                               1.0.0     
datashape                          0.5.4     
decorator                          4.3.0     
defusedxml                         0.5.0     
distributed                        1.25.1    
docutils                           0.14      
en-core-sci-lg                     0.2.3     
en-core-web-sm                     2.2.0     
entrypoints                        0.2.3     
et-xmlfile                         1.0.1     
fastcache                          1.0.2     
fastrlock                          0.4       
filelock                           3.0.10    
Flask                              1.0.2     
Flask-Cors                         3.0.7     
gast                               0.2.2     
gevent                             1.3.7     
glob2                              0.6       
gmpy2                              2.0.8     
google-pasta                       0.1.7     
greenlet                           0.4.15    
grpcio                             1.23.0    
h5py                               2.8.0     
heapdict                           1.0.0     
html5lib                           1.0.1     
idna                               2.8       
imageio                            2.4.1     
imagesize                          1.1.0     
importlib-metadata                 0.6       
ipykernel                          5.1.0     
ipython                            7.2.0     
ipython-genutils                   0.2.0     
ipywidgets                         7.4.2     
isort                              4.3.4     
itsdangerous                       1.1.0     
jdcal                              1.4       
jedi                               0.13.2    
jeepney                            0.4       
Jinja2                             2.10      
jmespath                           0.9.4     
joblib                             0.14.0    
jsonschema                         2.6.0     
jupyter                            1.0.0     
jupyter-client                     5.2.4     
jupyter-console                    6.0.0     
jupyter-core                       4.4.0     
jupyterlab                         0.35.3    
jupyterlab-server                  0.2.0     
Keras-Applications                 1.0.8     
Keras-Preprocessing                1.1.0     
keyring                            17.0.0    
kiwisolver                         1.0.1     
lazy-object-proxy                  1.3.1     
libarchive-c                       2.8       
lief                               0.9.0     
llvmlite                           0.26.0    
locket                             0.2.0     
lxml                               4.2.5     
Markdown                           3.1.1     
MarkupSafe                         1.1.0     
matplotlib                         3.0.2     
mccabe                             0.6.1     
mistune                            0.8.4     
mkl-fft                            1.0.6     
mkl-random                         1.0.2     
more-itertools                     4.3.0     
mpmath                             1.1.0     
msgpack                            0.5.6     
multipledispatch                   0.6.0     
murmurhash                         1.0.2     
nbconvert                          5.4.0     
nbformat                           4.4.0     
networkx                           2.2       
nltk                               3.4       
nmslib                             1.8.1     
nose                               1.3.7     
notebook                           5.7.4     
numba                              0.41.0    
numexpr                            2.6.8     
numpy                              1.15.4    
numpydoc                           0.8.0     
odo                                0.5.1     
olefile                            0.46      
openpyxl                           2.5.12    
packaging                          18.0      
pandas                             0.23.4    
pandocfilters                      1.4.2     
parso                              0.3.1     
partd                              0.3.9     
path.py                            11.5.0    
pathlib2                           2.3.3     
patsy                              0.5.1     
pep8                               1.7.1     
pexpect                            4.6.0     
pickleshare                        0.7.5     
Pillow                             5.3.0     
pip                                18.1      
pkginfo                            1.4.2     
plac                               0.9.6     
pluggy                             0.8.0     
ply                                3.11      
preshed                            3.0.2     
prometheus-client                  0.5.0     
prompt-toolkit                     2.0.7     
protobuf                           3.9.1     
psutil                             5.4.8     
ptyprocess                         0.6.0     
py                                 1.7.0     
pyasn1                             0.4.7     
pybind11                           2.4.3     
pycodestyle                        2.4.0     
pycosat                            0.6.3     
pycparser                          2.19      
pycrypto                           2.6.1     
pycurl                             7.43.0.2  
pyflakes                           2.0.0     
Pygments                           2.3.1     
pylint                             2.2.2     
pyodbc                             4.0.25    
pyOpenSSL                          18.0.0    
pyparsing                          2.3.0     
PySocks                            1.6.8     
pytest                             4.0.2     
pytest-arraydiff                   0.3       
pytest-astropy                     0.5.0     
pytest-doctestplus                 0.2.0     
pytest-openfiles                   0.3.1     
pytest-remotedata                  0.3.1     
python-dateutil                    2.7.5     
pytz                               2018.7    
PyWavelets                         1.0.1     
PyYAML                             3.13      
pyzmq                              17.1.2    
QtAwesome                          0.5.3     
qtconsole                          4.4.3     
QtPy                               1.5.2     
requests                           2.21.0    
rope                               0.11.0    
rsa                                3.4.2     
ruamel-yaml                        0.15.46   
s3transfer                         0.2.1     
scikit-image                       0.14.1    
scikit-learn                       0.21.3    
scipy                              1.1.0     
scispacy                           0.2.3     
seaborn                            0.9.0     
SecretStorage                      3.1.0     
Send2Trash                         1.5.0     
setuptools                         40.6.3    
simplegeneric                      0.8.1     
singledispatch                     3.4.0.3   
six                                1.12.0    
snowballstemmer                    1.2.1     
sortedcollections                  1.0.1     
sortedcontainers                   2.1.0     
spacy                              2.2.1     
Sphinx                             1.8.2     
sphinxcontrib-websupport           1.1.0     
spyder                             3.3.2     
spyder-kernels                     0.3.0     
SQLAlchemy                         1.2.15    
srsly                              0.1.0     
statsmodels                        0.9.0     
sympy                              1.3       
tables                             3.4.4     
tblib                              1.3.2     
termcolor                          1.1.0     
terminado                          0.8.1     
testpath                           0.4.2     
thinc                              7.1.1     
thinc-gpu-ops                      0.0.4     
toolz                              0.9.0     
tornado                            5.1.1     
tqdm                               4.28.1    
traitlets                          4.3.2     
unicodecsv                         0.14.1    
urllib3                            1.24.1    
wasabi                             0.2.2     
wcwidth                            0.1.7     
webencodings                       0.5.1     
Werkzeug                           0.14.1    
wheel                              0.32.3    
widgetsnbextension                 3.4.2     
wrapt                              1.11.2    
wurlitzer                          1.0.2     
xlrd                               1.2.0     
XlsxWriter                         1.1.2     
xlwt                               1.3.0     
zict                               0.1.3

**Comment by danielkingai2** [comment]
Ah, please upgrade to scispacy==0.2.4 and redownload the scispacy models (making sure you get the ones for the 0.2.4 release). Version 0.2.3 is not compatible with spacy==2.2.1

**Comment by rohittilwani** [comment]
The training process is not failing, so upgrading to scispacy 0.2.4 worked. Thanks for the help.

But while training it, i am facing another issue.

The training of the scispacy model "en_core_sci_lg"  continues for a long time, eventually consumes all RAM (on a 64GB , 32 core CPU machine with GPU) and finally crashes after running for around one and a half day in background. Does the further training of this model requires even larger machine and resources ?

**Comment by danielkingai2** [comment]
hm, this is unexpected to me. When I trained the `en_core_sci_lg` model, it was on a machine with 64 GB of RAM, and 8 CPUs. Using these scripts (as opposed to the built in spacy command): https://github.com/allenai/scispacy/blob/master/scripts/train_parser_and_tagger.py (for parser and tagger) and https://github.com/allenai/scispacy/blob/master/scripts/train_ner.py (for ner). A couple of questions, what part of the training process did `en_core_sci_lg` make it to (i.e. what output did you see before it crashed)? and, are you able to train `en_core_web_lg` (if not, I would suggest asking for help on the spacy repo)?

**Comment by danielkingai2** [comment]
Closing due to no response. Please reopen or open a new issue if you are still having problems. Thanks!
