### ISSUE TITLE
Chaining models or specifying priorities for overlapping entities?

### ISSUE THREAD

**Issue by bulutsuzku** [allenai/scispacy#184]
I already tried scispaCy with a NER task using en_ner_bionlp13cg_md, but unfortunately it recognizes entities in a wrong way i.e.: "Americas" as ORGANISM, so this is my question:

Could I chain different models? 
Like using both en_ner_bionlp13cg_md and en_ner_bc5cdr_md?

If yes, how do I specify "priority"? For example: I would like to prioritize on geopolitical entities using model A but for gene names use model B? 
Does this make sense?

 Is this what the "pipeline" concept refers to?

**Comment by danielkingai2** [comment]
There isn't currently a way to use multiple ner models in the same pipeline. You can definitely run them each independently and then combine results however you like. Also, see this issue (https://github.com/explosion/spaCy/issues/2920) about the same thing.
