### ISSUE TITLE
How to get entity types?

### ISSUE THREAD

**Issue by ahmadkhajehnejad** [allenai/scispacy#185]
According to the second table in https://allenai.github.io/scispacy/ each model supports multiple entity types. For example, en_core_sci_sm should have GGP, SO, TAXON, CHEBI, GO, CL entity types. But when I use en_core_sci_sm and get the entity types of the tokens, all of them are ENTITY. Is there anything wrong with the documentation or with my code?

**Comment by danielkingai2** [comment]
Where in the documentation do you see that `en_core_sci_sm` should have those entity types? Those look like the entity types for `en_ner_craft_md`.

**Comment by ahmadkhajehnejad** [comment]
Oh! Sorry! You are correct.
Thanks.
