### ISSUE TITLE
Combine 'ner' model with 'core_sci' model

### ISSUE THREAD

**Issue by masonedmison** [allenai/scispacy#186]
Hi,

I am working on a project using neuralcoref and I would like to incorporate the scispacy ner models. My hope was to use one of the `ner` models in combination with the `core_sci` tagger and dependency parser. 

NeuralCoref depends on the `tagger, parser, and ner`.

So far I have tried this code:
```python 
cust_ner = spacy.load('en_ner_craft_md')
nlp = spacy.load('en_core_sci_md')
nlp.remove_pipe('ner')
nlp.add_pipe(cust_ner, name="ner", last=True)
```

but when I pass text to the `nlp` object , I get the following error:
`TypeError: Argument 'string' has incorrect type (expected str, got spacy.tokens.doc.Doc)`

When I look at the `nlp.pipeline` attribute after adding the `cust_ner` to the pipe I see the `cust_ner` added as a `Language` object rather than a `EntityRecognizer` object:
```python
[('tagger', <spacy.pipeline.pipes.Tagger object at 0x7fb84976eda0>), ('parser', <spacy.pipeline.pipes.DependencyParser object at 0x7fb849516288>), ('ner', <spacy.lang.en.English object at 0x7fb853725668>)]
```

Before I start hacking away and writing terrible code, I thought I would reach out to see if you had any suggestions in how to accomplish what I am after?

Thanks in advance and for all that you folks do!

**Comment by danielkingai2** [comment]
As you have discovered, `cust_ner` is a full pipeline, which contains an NER pipe. You might be ablet to just add the NER pipe to the `en_core_sci_md`, haven't tested that. However, this shouldn't be necessary. The `en_ner_craft_md` model only retrains the NER pipe from `en_core_sci_md`, the parser and tagger should be equivalent. Are you seeing dramatic differences between the parser/tagger in `en_ner_craft_md` and the parser/tagger in `en_core_sci_md`?

**Comment by masonedmison** [comment]
Thanks for your speedy reply! The parser/tagger do not appear to be included the `ner` modules - neither in the directory nor in the `pipeline`. 
when I run  `cust_ner.pipeline` I only see `(ner, EntityRecognizer)`. In the actual directory, I see a vocab folder (with vectors files?) and ner folder. 

![en_craft_ner](https://user-images.githubusercontent.com/36715397/70349696-e0f3f980-182a-11ea-8637-57fc228830d7.png)


I tried to specifically add the `ner` pipe from craft corpus with the following:
```python
cust_ner_mod = spacy.load('en_ner_craft_md')
ner_pipe = cust_ner_mod.pipeline[0][1]
nlp = spacy.load('en_core_sci_md')
nlp.remove_pipe('ner')
nlp.add_pipe(ner_pipe, name="ner", last=True)
```

but receive an error regarding the `StringStore`:
```python
ValueError: [E084] Error assigning label ID 15990443803332177159 to span: not in StringStore.
```

**Comment by danielkingai2** [comment]
hm, it is possible I made a mistake when training these models. I'll look into this.

**Comment by danielkingai2** [comment]
Could you paste the output of `pip list` here?

**Comment by masonedmison** [comment]
Sorry, it is a bit long.
```python 
atomicwrites       1.3.0    
attrs              19.3.0   
autopep8           1.4.4    
awscli             1.16.260 
blis               0.2.4    
boto3              1.9.249  
botocore           1.12.250 
certifi            2019.9.11
chardet            3.0.4    
colorama           0.4.1    
conllu             2.2      
cymem              2.0.2    
Cython             0.29.13  
docutils           0.15.2   
en-core-sci-lg     0.2.3    
en-core-sci-md     0.2.3    
en-core-sci-sm     0.2.4    
en-core-web-md     2.1.0    
en-core-web-sm     2.1.0    
en-ner-craft-md    0.2.3    
en-ner-jnlpba-md   0.2.3    
entrypoints        0.3      
ez-setup           0.9      
flake8             3.7.9    
idna               2.8      
importlib-metadata 0.23     
jmespath           0.9.4    
joblib             0.14.0   
jsonschema         2.6.0    
mccabe             0.6.1    
more-itertools     7.2.0    
murmurhash         1.0.2    
neuralcoref        4.0      
nmslib             1.7.3.6  
numpy              1.17.3   
packaging          19.2     
pandas             0.25.3   
pip                19.3.1   
pkg-resources      0.0.0    
plac               0.9.6    
pluggy             0.13.0   
preshed            2.0.1    
py                 1.8.0    
pyasn1             0.4.7    
pybind11           2.4.3    
pycodestyle        2.5.0    
pyflakes           2.1.1    
pyparsing          2.4.2    
pyrsistent         0.15.5   
pytest             5.2.1    
python-dateutil    2.8.0    
pytz               2019.3   
PyYAML             5.1.2    
requests           2.22.0   
rsa                3.4.2    
s3transfer         0.2.1    
scikit-learn       0.21.3   
scipy              1.3.1    
scispacy           0.2.3    
setuptools         39.0.1   
six                1.12.0   
spacy              2.1.3    
srsly              0.1.0    
thinc              7.0.8    
tqdm               4.36.1   
urllib3            1.25.6   
wasabi             0.4.0    
wcwidth            0.1.7    
XlsxWriter         1.2.6    
zipp               0.6.0   
```

**Comment by danielkingai2** [comment]
Is upgrading to `scispacy==0.2.4` an option for you? I'm not sure what happened with `0.2.3`, but I just checked `en_ner_craft_md` in `0.2.4` and it has the full pipeline.

**Comment by danielkingai2** [comment]
Note, you'll to reinstall the models as well if you do upgrade.

**Comment by masonedmison** [comment]
Unfortunately, `0.2.3` is the newest I can go as the `neuralcoref` library only supports `spacy <=2.2.0`

**Comment by danielkingai2** [comment]
Well, I'm still not sure what happened with `0.2.3` (@DeNeutoy do you know? I think you did the release for that version), but adding the craft pipe to the core model seems to work for me. Could you try again in a clean environment and make sure you have the right versions of everything?

```
In [1]: import spacy                                                                                                                                                                                                                          

In [2]: md = spacy.load('en_core_sci_md')                                                                                                                                                                                                     

In [3]: craft = spacy.load('en_ner_craft_md')                                                                                                                                                                                                 

In [4]: md.remove_pipe('ner')                                                                                                                                                                                                                 
Out[4]: ('ner', <spacy.pipeline.pipes.EntityRecognizer at 0x7f21b83be8e8>)

In [5]: spacy.__version__                                                                                                                                                                                                                     
Out[5]: '2.1.3'

In [6]: md.meta['version']                                                                                                                                                                                                                    
Out[6]: '0.2.3'

In [7]: craft.meta['version']                                                                                                                                                                                                                 
Out[7]: '0.2.3'

In [8]: md.add_pipe(craft.pipeline[0][1], name='ner', last=True)                                                                                                                                                                              

In [9]: md("This text has DNA.")                                                                                                                                                                                                              
Out[9]: This text has DNA.

In [10]: md("This text has DNA.").ents                                                                                                                                                                                                        
Out[10]: (DNA,)

In [11]: [token.dep_ for token in md("This text has DNA.")]                                                                                                                                                                                   
Out[11]: ['det', 'nsubj', 'ROOT', 'dobj', 'punct']
```

**Comment by masonedmison** [comment]
I created a clean venv and verified correct version and the text input `This text has DNA` does not fuss when I access the `ents` attribute but other text examples still yield the `StringStore` error. 

Here is the code that generates the error:
```python 
>>> ab = md("""Regulation of c-jun mRNA expression by hydroxyurea in human K562 cells during erythroid differentiation [published erratum appears in Biochim Biophys Acta 1995 Dec 27;1264(3):409] 
... ... Hydroxyurea (HU) is an antitumor agent which also induces hemoglobinization during erythroid differentiation. In addition, HU stimulates the synthesis of fetal hemoglobin in sickle cell anemia patients. To further understand its mechanism of action, we investigated the effects of HU on regulation of c-jun expression prior to the onset of erythroid differentiation of K562 cells. HU induced a dose-dependent stimulation of c-jun synthesis. The levels of c-jun mRNA was elevated 4 to 7.5-fold by HU within 2 h. This was followed by a gradual decline to the basal level by 24 h. Both nuclear run-on and actinomycin D pulse experiments strongly indicate that HU regulates c-jun mRNA expression by increasing the rate of synthesis as well as stabilizing the c-jun mRNA. In addition, the level of jun protein was elevated by 2 to 5-fold within 4 h in HU treated cells. Furthermore, concentrations of HU below 250 microM slightly increased the 5X AP-1/CAT activity. These results strongly suggest that HU induces both transcriptional and post-transcription regulation of c-jun during erythroid differentiation. """)
>>> ab.ents
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "doc.pyx", line 496, in spacy.tokens.doc.Doc.ents.__get__
  File "span.pyx", line 114, in spacy.tokens.span.Span.__cinit__
ValueError: [E084] Error assigning label ID 15990443803332177159 to span: not in StringStore.
>>> 
```

**Comment by danielkingai2** [comment]
Well i got it down to this text that causes the crash `"""Regulation of c-jun mRNA expression by hydroxyurea"""`

**Comment by danielkingai2** [comment]
It looks like maybe something weird is happening with tokenization and the added pipe

**Comment by masonedmison** [comment]
Hm. I think I got it to work! If I use the vocab from the `ner` model within `sci_md` it works.

**Comment by danielkingai2** [comment]
oh nice! Sorry about that, we got something wrong for the `0.2.3` release there.

**Comment by danielkingai2** [comment]
Could you share the code that works?

**Comment by masonedmison** [comment]
Sure thing, working on it now.

**Comment by masonedmison** [comment]
So unfortunately the best I could do was to manually replace the `vocab` dir in the `core_sci_md` folder with the `vocab` found in the `ner_craft_md` folder.

I tried various ways to not have to manually copy the `vocab` folder, but none worked. It seems the `tagger, parser` depend on the `tokenizer` in the `sci_md` and the `ner` relies on the `vocab`. I tried to follow this logic and create a `Language` object from class but it did not work for me. 

After moving the `vocab` dir, replace the `ner` pipe in the `sci_md` model with the `ner` model as shown below:
```python
ner_mod = spacy.load('en_ner_craft_md')
ner_pipe = ner_mod.pipeline[0][1]
nlp = spacy.load('en_core_sci_md')
nlp.remove_pipe('ner')
nlp.add_pipe(ner_pipe, name="ner", last=True)
```

**Comment by danielkingai2** [comment]
Yikes, that is annoying. @DeNeutoy do you have any ideas about a nicer fix for this issue?

**Comment by DeNeutoy** [comment]
hmm, couple of issues here:

1. Until 0.2.4, none of the specialised NER models contained the full pipeline. I didn't add it in because it fits with spacy's naming convention `{lang}_{model}_{data}_{size}`. It's not really a problem that 0.2.4 contains them (just a miscommunication between Daniel and I), and maybe it's actually a good thing given this problem.

2. https://support.prodi.gy/t/error-assigning-label-id-when-combining-custom-ner-model-from-prodigy-with-spacy-dependency-parsing-model/1444/2 This seems to be a similar problem. Basically what I think is happening is that spacy assumes that all NER labels are in the vocabulary - here they are not, because the vocabs are different. You might find that just adding the literal strings the NER model needs for its labels to the vocabulary of the one for the parser/tagger works.

**Comment by DeNeutoy** [comment]
Also, I should have used the base vocab from the medium pipeline when training these specialised NER models, meaning that the NER vocab should be strictly larger (as it contains only the additional labels), although I am not confident that is the case - it's possible spacy adds tokens it sees during training on the fly to the vocab or something that I don't know about. If you try just setting the vocab from the pipeline equal to the vocab from the ner-only pipeline, do you get that same stringstore error when trying to use the parser? That would at least make sense...

**Comment by danielkingai2** [comment]
I did try just setting the vocab equal and got the same error. Looks like your hope about the relative size of them isn't the case:
```
In [96]: md = spacy.load('en_core_sci_md')                                                                                                                                                                                                    

In [97]: craft = spacy.load('en_ner_craft_md')                                                                                                                                                                                                

In [98]: len(md.vocab)                                                                                                                                                                                                                        
Out[98]: 386148

In [99]: len(craft.vocab)                                                                                                                                                                                                                     
Out[99]: 363532
```

**Comment by danielkingai2** [comment]
I'm confused how the ner model ended up with a smaller vocab...

**Comment by danielkingai2** [comment]
@masonedmison you could try building spacy and neuralcoref from source as suggested here (https://github.com/huggingface/neuralcoref/issues/197). don't really know if this would work with scispacy or not, but maybe worth a shot unless the vocab copying thing is working alright for you.

**Comment by masonedmison** [comment]
@danielkingai2 I just ended up manually moving over the vocab file to the `sci_md` model, then adding the `ner` pipe for the `ner` module, then use the `spacy.Language.to_disk` to save the full pipeline with the specialized `ner`. Not the most pretty process, but only needs done once and it seems to work as expected. Thanks for all of your time and help!

**Comment by danielkingai2** [comment]
Glad you were able to find a solution and apologies for the difficulty :)

**Comment by DeNeutoy** [comment]
We now build the specialised NER models with the parser and tagger inside them, so I think we can close this issue. Please reopen if not!
