### ISSUE TITLE
What is the expected functionality of Abbreviations ?

### ISSUE THREAD

**Issue by sahas-** [allenai/scispacy#189]
This may not be a bug, more of a clarification to understand expected functionality of AbbreviationDetector.

When I pass in a text `CTA chest`, it returns an empty array `[]`. Whereas I expected it to return 'computed tomography angiography' as long_form. Am I missing something silly or is it expected behavior ?

Thanks !!

**Comment by DeNeutoy** [comment]
Ah! The Abbreviation detector detects abbreviations defined in text, but does not try to disambiguate arbitrary abbreviations. So in a document, you had `blah blah... computed tomography angiography (CTA) was used ... After, CTA was done.`, the abbreviation detector would find the definition and connect it to its uses in the document. Hopefully that's clearer?

**Comment by sahas-** [comment]
Understood the current implementation and expected behavior.
However, just curious, is there a plan to implement "arbitrary abbreviation detector" on a given statement ?

**Comment by DeNeutoy** [comment]
No, sorry. That's very domain specific, and wouldn't be useful generally. It should be easy to implement (just a dictionary lookup) for any given abbreviations you have though!
