### ISSUE TITLE
Very sensitive UMLS tagging and some weird entities

### ISSUE THREAD

**Issue by nikolamilosevic86** [allenai/scispacy#190]
We had recently use case of tagging query with UMLS for which we have tried to use scispacy. However, when it comes to some countries next to disease names it is giving weird entities. For example a query: 
China kidney failure incidence
found "China kidney failure" as one entity. Similar with "United States kidney failure". However, if kidney failure is first and name of the country second, it works well and finds countries as separate entities, while that was not the case previously. Is there any quick fix to that? I was using en_core_sci_lg model.

**Comment by DeNeutoy** [comment]
Hi,

This seems to be a side effect of the models with vectors, sorry! If you try the small model, it is correct. Broadly, the performance is within ~1% of the medium and large models and the errors are often a bit more "sensible". The other thing you could try doing is updating the model a bit on your data, as the syntax of search queries is a bit different from biomedical abstracts.

**Comment by DeNeutoy** [comment]
FYI you can try out the models here:

https://scispacy.apps.allenai.org/

**Comment by DeNeutoy** [comment]
@nikolamilosevic86 just tagging you so you saw this - I think you might be better off with the small model? Closing, as this is just a difficulty with statistical models.
