### ISSUE TITLE
Acronyms: short form (long form)

### ISSUE THREAD

**Issue by fj-morales** [allenai/scispacy#192]
Hi, 

I'm working with your abbreviation detector tool. It's a great product. However, for the detection of short form (long form), it misses something like "SBMA (Spinal and bulbar muscular atrophy)" because the `filter_matches()` function in `abbreviation.py` requires two words instead of one as a verification step. Could you fix this, please?

Thanks!

**Comment by DeNeutoy** [comment]
Hi, it seems quite reasonable to assume that short form abbreviations will be a single token. Would you like to submit a PR with the change (and a small test demonstrating that single token short form abbreviations can be extracted?)
