### ISSUE TITLE
Unable to install Scipacy using anaconda navigator in Mac

### ISSUE THREAD

**Issue by ghostintheshellarise** [allenai/scispacy#193]
I am using Mac with latest Catalina version 10.15.3.  Anaconda is suggesting using the terminal option under environment i dedicated to scispacy.  However, when I start the terminal under that environment.  All i got is below message that i cannot proceed further.

```
Last login: Fri Feb  7 17:11:38 on ttys000
ka-mantse@Ka-mans-MBP ~ % /Users/ka-mantse/.anaconda/navigator/a.tool ; exit;
/Users/ka-mantse/.anaconda/navigator/a.tool: line 1: syntax error near unexpected token `('
/Users/ka-mantse/.anaconda/navigator/a.tool: line 1: `bash --init-file <(echo "source activate /opt/anaconda3/envs/scispacy;")'

[Process completed]

```

I encountered no such problem using Windows.  I am confused.

**Comment by DeNeutoy** [comment]
Hi, this appears to be a problem with anaconda and the terminal you are using, rather than a problem with scisapcy - maybe take a look at this issue:

https://github.com/ContinuumIO/anaconda-issues/issues/1831

If you can't fix it and figure out that it is a scispacy issue directly, please re-open!
