### ISSUE TITLE
Link to streamlit-based demo code

### ISSUE THREAD

**Issue by karelin** [allenai/scispacy#197]
Hello,

Many thanks for developing SciSpacy!
Is it possible to find the source code of demo app from here: https://scispacy.apps.allenai.org/ ?

**Comment by DeNeutoy** [comment]
Hi!

The demo code (i.e the actual repo) is closed source because it uses some internal AI2 infrastructure, but the streamlit part is here in this gist:

https://gist.github.com/DeNeutoy/b20860b40b9fa9d33675893c56afde42

**Comment by karelin** [comment]
Thank you @DeNeutoy!

**Comment by jkgenser** [comment]
> 

@DeNeutoy : Do you happen to know what version was used in the streamlit app? The results from the streamlit public demo case were really good for me but I'm having trouble replicating them.
