### ISSUE TITLE
Are you planning to release a pretrained- NER model for DBpedia?

### ISSUE THREAD

**Issue by amulyahwr** [allenai/scispacy#198]
Hello,

Are you planning to release/do you have a model for DBpedia such as for BIONLP13CG corpus (en_ner_bionlp13cg_md)? 
1. If yes, when can I expect it?
2. If it already exists and I can use it with scispacy, could you please guide me to it?
3. If no, could you please point me to the datasets DBpedia used in this paper: https://arxiv.org/pdf/1805.02262.pdf and let me know how can I train a specialized NER for DBpedia?

Thank you for your efforts!

**Comment by danielkingai2** [comment]
Hi, we do not currently have any plans to train an NER model on DBpedia. I am not sure where the DBpedia based dataset mentioned in that paper is, but it seems your goal is to train an NER model to recognize mentions of entities that are in Wikipedia? If so, you might be able to find some datasets just by searching around, for example I found this which looks like it might be what you are after (https://github.com/ghaddarAbs/WiNER). Once you have the data you want to train on, you just need to get it into a format that spacy accepts (https://spacy.io/api/annotation#training) and then train spacy's ner model (https://spacy.io/usage/training#ner).
