### ISSUE TITLE
pip install scispacy errors in windows

### ISSUE THREAD

**Issue by lingluodlut** [allenai/scispacy#200]
Hi,
I used the command 'pip install scispacy' to install in my conda environment of windows. But it fails and shows the following errors:

ERROR: boto3 1.9.66 has requirement botocore<1.13.0,>=1.12.66, but you'll have botocore 1.15.9 which is incompatible.
ERROR: boto3 1.9.66 has requirement s3transfer<0.2.0,>=0.1.10, but you'll have s3transfer 0.3.3 which is incompatible.
Installing collected packages: conllu, pybind11, nmslib, pyasn1, rsa, PyYAML, s3transfer, awscli, pysbd, scispacy
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 5.3
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

What should I do?
Thanks!

**Comment by danielkingai2** [comment]
It looks like something about your setup is preventing PyYAML from being uninstalled? Can you try installing scispacy in a clean conda environment?

**Comment by lingluodlut** [comment]
OK. It works in a clean conda environment. Thanks. @danielkingai2
