### ISSUE TITLE
Candidategenerator sometimes returns more candidates than specified k.

### ISSUE THREAD

**Issue by izuna385** [allenai/scispacy#202]
https://github.com/allenai/scispacy/blob/master/scispacy/candidate_generation.py#L179
seems like, sometimes returning more candidates than specified k.

Is this caused from many data points which exist in same distance from searched query vector? or, another cause?
If you'd know about this, I'd appreciate it. Thanks.

**Comment by izuna385** [comment]
For example, mention : problems
> `candidate_generator(['problems'],10)[0]`
```
[MentionCandidate(concept_id='C1546466', aliases=['Problems'], similarities=[1.0]), MentionCandidate(concept_id='C0262471', aliases=['ent problems'], similarities=[0.921135425567627]), MentionCandidate(concept_id='C1718157', aliases=['Oral problems'], similarities=[0.9019364714622498]), MentionCandidate(concept_id='C0231339', aliases=['age problems'], similarities=[0.8679661154747009]), MentionCandidate(concept_id='C0577885', aliases=['nose problems'], similarities=[0.8645884394645691]), MentionCandidate(concept_id='C0741992', aliases=['hand problems'], similarities=[0.8645559549331665]), MentionCandidate(concept_id='C0150920', aliases=['problems spine'], similarities=[0.8607649803161621]), MentionCandidate(concept_id='C0262174', aliases=['ear problems'], similarities=[0.8554203510284424]), MentionCandidate(concept_id='C0848067', aliases=['mental problems'], similarities=[0.8512626886367798]), MentionCandidate(concept_id='C0438989', aliases=['hear problems'], similarities=[0.8470597863197327]), MentionCandidate(concept_id='C0260662', aliases=['hear problems'], similarities=[0.8470597863197327])]
```
> `len(candidate_generator(['problems'],10)[0])`
11

**Comment by izuna385** [comment]
Sorry to keep bothering you. I think this is not bug, and candidate_generator cover all possible cui with same scores.
Another example, 'preferred setting' k=10 return includes
'Preferred Term' of C1709637 and C2347664 with score 0.6542521715164185
(Both canonical name is same, 'Preferred Term')

and 'setting' of C0542559 and 'Setting' of C4281677 with score 0.6470361948013306.

After all, UMLS covers so many concepts that sometimes this can happen.
This issue can be closed. Sorry for bothering.

**Comment by danielkingai2** [comment]
No problem! Glad you resolved it!
