### ISSUE TITLE
Details about ums meta output json?

### ISSUE THREAD

**Issue by izuna385** [allenai/scispacy#204]
https://github.com/allenai/scispacy/blob/25e4c5d9e30f48eebbddc121bb05ff1057d5992a/scispacy/umls_utils.py#L40
This file seems to contain some concepts which don't exist in UMLS2017AA MRCONSO.RRF file.
If you'd know the source of this meta_output json file, I'd appreciate it.
Thnaks.

**Comment by ibeltagy** [comment]
All the concepts in `umls_2017_aa_cat0129.json` are from `UMLS2017AA MRCONSO.RRF` for categories 0, 1, 2 and 9. Can you double check that your `MRCONSO.RRF` contains all categories 0,1,2,9 ?

**Comment by izuna385** [comment]
I' ll check again, thanks.
Actually, I didn't know "categories" exist in MRCONSO.RRF file, so now I'll investigate it, Thanks.
