### ISSUE TITLE
Would `en_core_sci_{sm|md|lg}`  generate the same UMLS candidates?

### ISSUE THREAD

**Issue by wammar** [allenai/scispacy#208]
Hello friends! I'd like to verify whether the behavior of the candidate generator in `UmlsEntityLinker` (with abbreviations enabled) depends at all on which size of the `en_core_sci_*` model we load. As far as I can tell, the file paths used to find approximate nearest neighbors are [the same](https://github.com/allenai/scispacy/blob/master/scispacy/candidate_generation.py#L16) regardless of the model specified at `spacy.load` but I may have missed something.

**Comment by danielkingai2** [comment]
Hi Waleed! The entity linker is its own pipe, and does not depend on the model used. However, the entity linker just provides linking candidates for a given entity span, the entity spans themselves are predicted by the NER pipe. The predictions of the NER pipe can differ between the different model sizes.

**Comment by wammar** [comment]
Gotcha, thanks Daniel!
