### ISSUE TITLE
[Text Mining]How to encode keywords in spacy/scispacy?

### ISSUE THREAD

**Issue by vectorkt** [allenai/scispacy#210]
Hello,

I'm currently working on some biomedical text mining.
The idea is, I have a set of abstracts of 50 words each, and in each one I have the same two keywords such as ProteinA and ProteinB.
The output would be if the two proteins are connected or not in said abstract aka a 0 or 1 output.

I have attempted to code each word of the abstract with spacy or scispacy and feed the resulting (50,word_vector_length) to my neural network.
The trouble is, neither spacy or scispacy seem able to encode the keywords.

`
import spacy
spa = spacy.load("en_core_web_lg")
sci = spacy.load("en_core_sci_lg")

print(spa("proteinA").vector) #results in zero vector

print(spa("proteinB").vector) #results in zero vector

print(sci("proteinA").vector) #results in zero vector

print(sci("proteinB").vector) #results in zero vector
`

What can I do about this situation? 

Are there special keywords that either of these embeddings will latch onto?

Can I somehow train these embeddings to suit my needs?

Perhaps there's a way to include spacy in the keras Embedding layer?

Thanks!

**Comment by DeNeutoy** [comment]
Hi, 

The scispacy models have reasonable coverage (the larger the model the bigger the vocab which has vectors), but unfortunately they don't have vectors for all possible words. There's not much we can do about this - you might consider using a bigger set of vectors to see if they contain the words you are looking for or something?

Thanks
