### ISSUE TITLE
Issue while trying to download the data

### ISSUE THREAD

**Issue by prashikhurana** [allenai/scispacy#211]
Hi,

Thank you so much for this package. Although I Had some confusion regarding the downloading of the module. I was trying to download the data via  : !pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_core_sci_sm-0.2.4.tar.gz8

But I got an error. 
ERROR: Could not install requirement https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_core_sci_sm-0.2.4.tar.gz8 because of error 403 Client Error: Forbidden for url: https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_core_sci_sm-0.2.4.tar.gz8

Could you help me with the same ? 

My code:
!pip install scispacy
!pip install -U spacy
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_core_sci_sm-0.2.4.tar.gz8 -> _got error at this point_
import scispacy
import spacy
import en_core_sci_lg
nlp1 = spacy.load("en_core_sci_lg")

Thank you.

**Comment by prashikhurana** [comment]
I also tried !pip install <https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_core_sci_sm-0.2.4.tar.gz8> 
But still got an issue: /bin/bash: -c: line 0: syntax error near unexpected token `newline'
/bin/bash: -c: line 0: `pip install <https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_core_sci_sm-0.2.4.tar.gz8>'

**Comment by DeNeutoy** [comment]
@prashikhurana you have an extra "8" character at the end of the URL. 

Try https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_core_sci_sm-0.2.4.tar.gz
