### ISSUE TITLE
BibTex citation wrong in README

### ISSUE THREAD

**Issue by AssassinTee** [allenai/scispacy#213]
Currently the citation in the README looks like this:
```
@inproceedings{Neumann2019ScispaCyFA,
  title={ScispaCy: Fast and Robust Models for Biomedical Natural Language Processing},
  author={Mark Neumann and Daniel King and Iz Beltagy and Waleed Ammar},
  year={2019},
  Eprint={arXiv:1902.07669}
}
```
But it should look like this:
```
@inproceedings{Neumann2019ScispaCyFA,
  title={{ScispaCy}: {Fast} and {Robust} {Models} for {Biomedical} {Natural} {Language} {Processing}},
  author={Mark Neumann and Daniel King and Iz Beltagy and Waleed Ammar},
  year={2019},
  booktitle={TODO?},
  Eprint={arXiv:1902.07669}
}
```

You can see in this [table](https://de.wikipedia.org/wiki/BibTeX), that the booktitle key is required. In the english version the table is missing(?!). In order to be casesensitve, upper letter words needs to be embraced `{...}`. I am currently writing my master thesis and fixing warnings and this might help others in the future.

This is what [arxiv.org](https://arxiv.org/abs/1902.07669) generated for me:

```
@article{Neumann_2019,
   title={ScispaCy: Fast and Robust Models for Biomedical Natural Language Processing},
   url={http://dx.doi.org/10.18653/v1/W19-5034},
   DOI={10.18653/v1/w19-5034},
   journal={Proceedings of the 18th BioNLP Workshop and Shared Task},
   publisher={Association for Computational Linguistics},
   author={Neumann, Mark and King, Daniel and Beltagy, Iz and Ammar, Waleed},
   year={2019}
}
```

This is what [sematicscholar.org](https://www.semanticscholar.org/paper/ScispaCy%3A-Fast-and-Robust-Models-for-Biomedical-Neumann-King/de28ec1d7bd38c8fc4e8ac59b6133800818b4e29) gave me:
```
@inproceedings{Neumann2019ScispaCyFA,
  title={ScispaCy: Fast and Robust Models for Biomedical Natural Language Processing},
  author={Mark Neumann and Daniel King and Iz Beltagy and Waleed Ammar},
  booktitle={BioNLP@ACL},
  year={2019}
}
```

**Comment by danielkingai2** [comment]
Thanks! We should probably update the bibtex to be a citation to the published version anyway. Feel free to submit a PR, or I'll get to it sometime soon.
