### ISSUE TITLE
How to select only particular domains from UMLS using UmlsEntityLinker?

### ISSUE THREAD

**Issue by Raghu17s** [allenai/scispacy#215]
Hi,

I need to look for only conditions, procedures, and observations in my medical text. Is there any way to specify these options in UmlsEntityLinker.

**Comment by danielkingai2** [comment]
Hi, every UMLS entity is associated with one or more types, which come from the UMLS type tree (https://ai2-s2-scispacy.s3-us-west-2.amazonaws.com/data/umls_semantic_type_tree.tsv). You could browse this type tree, find the types that are relevant to you, and then filter the results by UMLS type.

**Comment by Raghu17s** [comment]
Hi,
Do you have any examples for same to select UMLS entity?

**Comment by danielkingai2** [comment]
If you have the UMLS entity identifier for the entities you want to filter to (called a CUI), you could easily filter the output to only entities matching the CUIs you are interested in.
