### ISSUE TITLE
How to train the new vocubalary in sciscapy?

### ISSUE THREAD

**Issue by Raghu17s** [allenai/scispacy#216]
Hi,

I have a medical text where I need to extract only SNOMED concepts from the text. The existing sciscapy models are detecting something beyond my requirement (ex, pharma, DNA, cell type, chemicals). I have a list of SNOMED concepts corpus to be extracted from medical text. Is there any way to use our own vocabulary and use the rest of sciscapy pipeline?

**Comment by danielkingai2** [comment]
Could you clarify your problem here? Is that you want to extract biomedical concepts from text, but _only_ the ones that show up in your list of SNOMED concepts? What identifying information do you have for the SNOMED concepts that you want to extract?

**Comment by Raghu17s** [comment]
Hi @danielkingai2 
Yes, I am interested in extracting only SNOMED vocabulary concepts like "condition", "procedure", 'findings" and other few domains concepts.

**Comment by danielkingai2** [comment]
What information do you have for that concept list? That is, does each concept have an identifier that you can map to UMLS? Does it have a description? Does it have a list of aliases? Other?

**Comment by Raghu17s** [comment]
I have a concept ID and its descriptions. and also its aliases from SNOMED  in table format.

**Comment by danielkingai2** [comment]
If the concept ID is a UMLS id, you could just filter the output of the linker based on your list of concept IDs.

**Comment by Raghu17s** [comment]
I could able to map from CUI to SNOMED. Thanks for the suggestion
