### ISSUE TITLE
The entities are missing in UmlsEntityLinker

### ISSUE THREAD

**Issue by Raghu17s** [allenai/scispacy#220]
Hi,

I have a biomedical medical text document and trying to extract medical concepts out of it. There are medical terms like "transient ischemic attack, aortic dissection," are detected using "display_entities" function. When I perform "unified_medical_language_entity_linker" they are not resulting as an entity, Concept_Id, Score. What are the parameters to be fined to get in UMLSLinker.

I am using "en_core_sci_md" model.

**Comment by DeNeutoy** [comment]
The entity linker is quite naive, so it may not link all of your entities that are extracted. You can play around with some of the linker parameters here: https://github.com/allenai/scispacy#umlsentitylinker-alpha-feature

You might want to try lowering the thresholds for the score at which an entity is linked - be aware that this will probably increase your false positives also.

**Comment by Raghu17s** [comment]
Yes, I tried same and faced false positive as you said. 
By the way, is there any way to find negations using this.

**Comment by danielkingai2** [comment]
Not in scispacy. I haven't used this package myself, but I have seen it used in a couple place, might be worth checking out: https://github.com/jenojp/negspacy

**Comment by Raghu17s** [comment]
@danielkingai2 Thanks,  negspacy worked for me. 
Can I gent information which method was used for text matching? like levenshtein distance (fuzzy ratio, partial, or any other) -- ShouldI open new issue for this different question?

**Comment by danielkingai2** [comment]
The details are described in the paper (https://www.semanticscholar.org/paper/ScispaCy%3A-Fast-and-Robust-Models-for-Biomedical-Neumann-King/de28ec1d7bd38c8fc4e8ac59b6133800818b4e29) in section 5. It is an approximate nearest neighbors search over tfidf character 3-grams.

**Comment by Raghu17s** [comment]
Thanks for the article.

How do we print "Canonical Name"? as it shows in here https://scispacy.apps.allenai.org/

**Comment by danielkingai2** [comment]
`print(linker.umls.cui_to_entity[concept_id])` all the entity attributes can be found on the entity objects in `linker.umls.cui_to_entity`. I'd encourage you to read through the README, as there is lots of good information in there.
