### ISSUE TITLE
no_definition_threshold is giving error in UmlsEntityLinker?

### ISSUE THREAD

**Issue by Raghu17s** [allenai/scispacy#221]
Hi,

I am trying to play around with `no_definition_threshold` parameters given the UmlsEntityLinker. But it throws the following error.

__init__() got an unexpected keyword argument 'no_definition_threshold'

Another question
Initializing UmlsEntityLinker takes too long everytime. And it does not work in the absence of interent. How to get rid of this?

**Comment by DeNeutoy** [comment]
The class has this parameter, you can see here:

https://github.com/allenai/scispacy/blob/master/scispacy/umls_linking.py#L64
 - please post the full traceback so we can help you. 

I would suggest you try to load it only once, as it had to load a substantial amount of data (this is unavoidable). It it true there may be a way to load it faster, but we haven't particularly looked into it.

I don't understand your question about the absence of "interent"?

**Comment by Raghu17s** [comment]
@DeNeutoy here is the full traceback
```
TypeError                                 Traceback (most recent call last)
<ipython-input-3-ca0a2c880bef> in <module>
      1 # link to UMLS
----> 2 linker = UmlsEntityLinker(k = 10, max_entities_per_mention = 5, threshold = 0.5, no_definition_threshold = 0.8)    #parameters are tunable  k = 10, max_entities_per_mention = 2
      3 nlp.add_pipe(linker)

TypeError: __init__() got an unexpected keyword argument 'no_definition_threshold'

**Comment by danielkingai2** [comment]
I would guess that you are on an old version, that parameter was introduced in `v0.2.3`

**Comment by Raghu17s** [comment]
I had downgraded to v0.2.2 due to following error. If I update the version I recieve following error
```
E167] Unknown morphological feature: 'ConjType' (9141427322507498425). 
This can happen if the tagger was trained with a different set of morphological features.
 If you're using a pretrained model, make sure that your models are up to date:

**Comment by danielkingai2** [comment]
When you change scispacy version, you also need to download the models for that version.

**Comment by danielkingai2** [comment]
@Raghu17s Did this work for you?

**Comment by Raghu17s** [comment]
@danielkingai2 yes, it worked for me. Thanks for the suggestion. 
Scispacy is really awesome.

For curiosity this question
Is there any way we can build relationships from the entities extracted from text.

**Comment by danielkingai2** [comment]
Great!

For that, you'll have to explore the literature on "relation extraction," as this task is not supported in scispacy :) but you may check out some related work from some of our colleagues https://api.semanticscholar.org/CorpusID:202660640
