### ISSUE TITLE
License fee for Commercial Use of SciSpacy

### ISSUE THREAD

**Issue by himanshumohan19** [allenai/scispacy#222]
Hi ,
We are planning to use scispacy in one of our commerical product . can you please let us know f we need to pay any licence fee to use scispacy library in our production system 

Thanks

**Comment by DeNeutoy** [comment]
Hi, no fee is necessary - the code and models are released under the Apache 2.0 license, which allows commercial use. However, it would be great if you could let us know a bit about what you are using it for, as we want to continue to make scispacy useful and it would be great to hear what your main needs are. You can email us at `{markn, daniel} AT allenai.org`

**Comment by himanshumohan19** [comment]
Hi,
Can you please send me your email id in correct format ?

Thanks

**Comment by radiatechs-himanshu** [comment]
Thanks You can close this issue
