### ISSUE TITLE
scispacy model installation via PyPi / Spacy 

### ISSUE THREAD

**Issue by vgainullin** [allenai/scispacy#224]
There appears to be no straightforward option to include scispacy models as dependencies for PyPi projects.

Are there plans to distribute en_core_sci_sm with either: 
`pip install en_core_sci_sm`

or 

`from spacy.cli import download`
`download("en_core_sci_md")`

**Comment by DeNeutoy** [comment]
Hi, @vgainullin,

You can simply add the full url to the model to your requirements.txt file.

e.g

`https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_core_sci_sm-0.2.4.tar.gz
`

**Comment by vgainullin** [comment]
@DeNeutoy, thanks for the reply. Correct me if I am wrong, but packaging for PyPi does not include dependencies specified in requirements.txt.

**Comment by DeNeutoy** [comment]
@vgainullin  Ah! Sorry you are right, I miss read your question. Spacy also does not provide this functionality, so it is unlikely we will. It's possible you can call `spacy.cli.download` with a url path, i'm not sure. Regardless, I don't think having models as dependencies is 100% useful (they can be large, you want to cache them in a way you don't want to with normal dependencies) so it's unlikely we will implement this. Sorry!
