### ISSUE TITLE
Is Scispacy model compatible with AWS sagemaker ?

### ISSUE THREAD

**Issue by radiatechs-himanshu** [allenai/scispacy#225]
Hi ,
I am working to deploy scispacy model on AWS sagemaker . I like to know is Scispacy models compatible with AWS sagemaker and what is the approach should we use - is storing Scispacy model in s3 or loading runtime on docker container 

Thanks

**Comment by danielkingai2** [comment]
I believe Sagemaker relies on docker, so you'll just want to install whatever you need (including scispacy) via docker.

**Comment by radiatechs-himanshu** [comment]
Hi Dan,
You are correct we need to make a docker file to install spacy and scispacy libraries and the corresponding code . I am struggling where the pre trained model will be stored so that we can access oin our python code on docker 

Thanks

**Comment by danielkingai2** [comment]
pretty sure you just want to have
```
RUN pip install scispacy
RUN pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_core_sci_sm-0.2.4.tar.gz (or whatever model you want)
```
in your Dockerfile

**Comment by radiatechs-himanshu** [comment]
thanks
