### ISSUE TITLE
Can we combine two entities before linking to UMLS?

### ISSUE THREAD

**Issue by Raghu17s** [allenai/scispacy#226]
Hi,

I have extracted entities from the text but I am not getting desired output after linking to UMLS bcs sentence has broken? is there any way I can combine two entities before feeding into UMLS.

`text = 'replacement of knee joint`
`doc = nlp (text)`
it ouputs entities as  `doc.ents`
 `replacement `
 `knee joint `

I get exact meaning only when I combine both entities like "replacement knee joint" and feed it to 
following code 
`for ent in doc.ents:`
    `for umls_ent in entity._.umls_ents:`
	`print(linker.umls.cui_to_entity[umls_ent[0]])`

**Comment by danielkingai2** [comment]
You can use the entity ruler (https://spacy.io/api/entityruler) instead of the ner module if you want to pass in entities yourself. You can also sort of hack the `doc.ents` to pass in your own entities like so:
```
In [174]: linker = UmlsEntityLinker(resolve_abbreviations=False, filter_for_definitions=False, threshold=0.5)                                                                                                                                 
In [175]: doc = base_nlp('il-10-producing regulatory t-cells')                                                                                                                                                                                
In [176]: doc.ents = [Span(doc, 0, len(doc), label="Entity")]                                                                                                                                                                                 
In [177]: linked_doc = linker(doc)                                                                                                                                                                                                            
In [178]: linked_doc.ents[0]._.umls_ents                                                                                                                                                                                                      
Out[178]: 
[('C0039198', 0.6841055154800415),
 ('C4284002', 0.5307365655899048),
 ('C0039194', 0.5252377986907959),
 ('C3178914', 0.5139729976654053),
 ('C1819477', 0.5007489323616028)]
```
but this may cause other things to break.

**Comment by Raghu17s** [comment]
@danielkingai2 Yes, this breaks other things. 
*************************************
Further, I am getting strange results in some cases (please let me know if anyone has faced the same issue)
I have text as ` fever hypertension diabetes mellitus`
when I extract entities using scispacy, it output them as one entity like
`fever hypertension diabetes mellitus` 
which suppose to be three different in the medical context
`fever`
`hypertension` 
`diabetes mellitus`

Note: Similar results using all of Scispacy models.

**Comment by danielkingai2** [comment]
The models were trained on proper sentences, and are likely to not do what you expect given less well formed text.

**Comment by Raghu17s** [comment]
You are correct.  Sorry for the wrong question. 
My input data format is wrong.

**Comment by danielkingai2** [comment]
No problem! Closing this issue, feel free to open a new one if you have more questions.
