### ISSUE TITLE
What is the purpose of the awscli dependency? 

### ISSUE THREAD

**Issue by sndrtj** [allenai/scispacy#228]
Hello there,
 
Scispacy depends on `awscli` without a version constraint. As awscli has over 1000 releases, this makes dependency resolving in tools such as poetry using scispacy take a very long time.

I could not find any actual uses of the awscli package inside scispacy. What is the purpose of specifying it as a dependency? I did find a use of `requests` in  [file_cache.py](https://github.com/allenai/scispacy/blob/master/scispacy/file_cache.py), which is of course a transitive dependency of awscli. Would it be possible to promote requests to a direct dependency of scispacy, and drop the awscli dependency?

**Comment by DeNeutoy** [comment]
@danielkingai2 any ideas? I think this might be a hangover from when the file cache could sign requests to private buckets. If so, we can just remove it and replace with requests as @sndrtj suggests!

**Comment by danielkingai2** [comment]
It would appear that I put it in the requirements when I made the repo for some reason 🤷‍♂️ pretty sure its safe to remove.

**Comment by sndrtj** [comment]
I went ahead and opened a PR (#229) that addresses this :-). I hope the version constraint I put on requests isn't too strict (or too loose).

**Comment by DeNeutoy** [comment]
Closed by #229, thanks!
