### ISSUE TITLE
re-train sci-spacy entity linking model

### ISSUE THREAD

**Issue by rshah1990** [allenai/scispacy#234]
Hi Team,

is it possible to re-train Name entity linking model with custom data & also want to change KB of it. 
just to give you an example in our case if the data is like " Essex-Lopresti fracture of left radius" than current sci-spacy model identifies **fracture** as an entity but we want **Essex-Lopresti fracture** as an entity. we also want to **add/modify new terms in KB** so that we could  get proper TUI. We have limited data so we want to take advantage of pre-trained model of sci-spacy

Can someone please help , Thanks in advance.

**Comment by fcggamou** [comment]
I'm also looking to do something like this

**Comment by danielkingai2** [comment]
@DeNeutoy Are the scripts set up such that it would be easy to add your own entities and then retrain the tfidf/ann stuff? (especially after your recent refactor)

**Comment by DeNeutoy** [comment]
Hi @rshah1990 , @fcggamou 
This function trains a linker:
https://github.com/allenai/scispacy/blob/master/scispacy/candidate_generation.py#L325

which takes a `KnowledgeBase`: https://github.com/allenai/scispacy/blob/master/scispacy/linking_utils.py#L45

which reads JSON/JSONL with the following simple format:

```
# Json per entity you have:
{
"concept_id": "The ID for the concept",
"canonical_name": "MyEntity",
"aliases": ["List of alternative ways to refer to the entity"],
"definition": "Longer form def of entity", # optional
"types": ["The type of the entity"] # optional
}

```

Also note that this will only work if you work off of the master branch.

**Comment by DeNeutoy** [comment]
Closing in favour of #237 which has more detail.
