### ISSUE TITLE
New Model to Contribute

### ISSUE THREAD

**Issue by lordtt13** [allenai/scispacy#235]
I have been working on a spacy model trained on word2vec vectors based on the CORD-19 dataset, a large model based on all training data and a small model based on only the abstracts of the research papers. All of my work is done in collaboration with @smoke-trees and @CYBINT-IN. How do I go about the submission?

**Comment by DeNeutoy** [comment]
Hello!

Scispacy isn't currently soliciting user models for hosting. We provide a set of models which we have trained and maintain, but we don't want to do this with user submitted models currently. Feel free to share a link to your model here and interested people will probably see it!

**Comment by lordtt13** [comment]
Thank you for the reply, will certainly open source it.
