### ISSUE TITLE
Custom (local) UMLS subsets

### ISSUE THREAD

**Issue by ChantalvanSon** [allenai/scispacy#237]
Hi scispacy team,

First of all, thanks for creating a great tool, I think it's very useful!

I have a couple of questions related to the UMLS Entity Linker:

**Generic UMLS linker**
From the [paper](https://arxiv.org/pdf/1902.07669.pdf), I understand that scispacy links entities to UMLS concepts from "sections 0, 1, 2 and 9 (SNOMED) of the UMLS 2017 AA release". Is that still correct? I think it would be useful to add this information to the README as well. 

**Custom UMLS linker**
Somewhat related to #234: would it also be possible to link the entities to a local UMLS subset (installed with [MetamorphoSys](https://www.nlm.nih.gov/research/umls/implementation_resources/metamorphosys/help.html)) for people with a [UMLS license](https://uts.nlm.nih.gov/license.html)?

The reason I'm asking is twofold:

1.  UMLS is released [twice a year](https://www.nlm.nih.gov/research/umls/licensedcontent/umlsarchives04.html) in the first weeks of May and November. The current version is [2020AA](https://www.nlm.nih.gov/research/umls/licensedcontent/umlsknowledgesources.html) and contains new concepts, such as COVID-19, that will currently not be detected by scispacy. Unless you're planning to do frequent updates on the model, I'd like to be able to use the most frequent concepts.
2. UMLS is highly customisable; users can select their own subsets of the many [vocabularies](https://www.nlm.nih.gov/research/umls/sourcereleasedocs/index.html). It would be great if this customisability is also applied in scispacy.

My understanding is that it is possible by:

- Converting a UMLS `MRCONSO.RFF` file to JSON using [export_uml_json.py](https://github.com/allenai/scispacy/blob/master/scripts/export_uml_json.py)
- Generating a [KnowledgeBase](https://github.com/allenai/scispacy/blob/master/scispacy/linking_utils.py#L45) object 
- Training a new linker using [create_tfidf_ann_index()](https://github.com/allenai/scispacy/blob/master/scispacy/candidate_generation.py#L325 )

Is this correct? Any help or more detailed instructions would be greatly appreciated!

**Comment by DeNeutoy** [comment]
Hi @ChantalvanSon, sorry for the delay in getting back to you. I was trying to get access to the latest release of UMLS, but failed because our subscription had run out 🙄 . 

Overall the steps you describe are accurate - the only important thing is the format of the kb file. After that it should be pretty straightforward - let us know if you run into any problems. Note that for all of UMLS it can take a little while to build the ANN index, maybe 2-3 hours.

Overall, it wouldn't be too much effort to release multiple entity linkers, but I want to make sure they would see good use. E.g for the upcoming release, I have created one which links to MESH terms. However, for very niche use cases, i'd prefer to just make it easy for people to create their own, so consider yourself a guinea pig for that!

We will try to update the entity linker in upcoming releases though, it is a bit old certainly.

**Comment by ChantalvanSon** [comment]
Hi @DeNeutoy, thanks for the information! I'm happy to share that I managed to create my custom Entity Linker based on the 2020AA release. It took a bit longer (~8 hours) to build the ANN index, but this could very well be because of the size of my UMLS subset (all level 0 sources + SNOMED).  

Overall, it was not tóó difficult to do, but I think some small changes in the code would make it even easier. I don't have an answer to this question myself yet -- if I have time and I do think of a good solution, I will try to see if I can help out by creating a PR. But I think it comes down to the following:

`CandidateGenerator()` currently accepts either a pre-trained linker (`umls` or `mesh`), for which the default `LinkerPaths` have been defined globally in the `candidate_generation.py`. While it is possible to provide your own `ann_index`, `tfidf_vectorizer`, `ann_concept_aliases_list` and `kb`, these will first have to be loaded using `load_approximate_nearest_neighbours_index`, and this one only accepts a `LinkerPaths` object.  So I ended up writing something like the following (based on how it's done for the pre-trained `umls` and `mesh` linkers in `candidate_generation.py`):

```
import json
import joblib

from scispacy.linking_utils import UmlsKnowledgeBase
from scispacy.candidate_generation import (
    CandidateGenerator,
    LinkerPaths,
    load_approximate_nearest_neighbours_index,
)

CustomLinkerPaths_2020AA = LinkerPaths(
    ann_index="path/to/nmslib_index.bin",
    tfidf_vectorizer="path/to//nmslib_index.bin",
    tfidf_vectors="path/to/tfidf_vectorizer.joblib",
    concept_aliases_list="path/to/concept_aliases.json",
)

# set default release
DEFAULT_RELEASE = "2020AA"
DEFAULT_KB_PATH = "path/to/2020AA.json"
DEFAULT_PATHS = {"2020AA": CustomLinkerPaths_2020AA}


def load_candidate_generator(
    release: str = DEFAULT_RELEASE, kb_path: str = DEFAULT_KB_PATH,
) -> CandidateGenerator:
    """Loads a pre-trained custom scispacy candidate generator by
    loading the different model components from disk.

    release: str
        The name of the pretrained candidate generator to load. 
        Currently, the only available (and default) is "2020AA".

    kb_path: str
        Path to the Knowledge Base in JSON format as required by scispacy.
    """

    # create LinkerPaths
    linker_paths = DEFAULT_PATHS[release]

    # load ann_index, tfifd_vectorizer and ann_concept_aliases_list
    ann_index = load_approximate_nearest_neighbours_index(linker_paths=linker_paths)
    tfidf_vectorizer = joblib.load(linker_paths.tfidf_vectorizer)
    with open(linker_paths.concept_aliases_list, "r") as f:
        ann_concept_aliases_list = json.load(f)

    # load UMLS KnowledgeBase (converted json file)
    umls_kb = UmlsKnowledgeBase(file_path=kb_path)

    # create candidate generator
    candidate_generator = CandidateGenerator(
        ann_index=ann_index,
        tfidf_vectorizer=tfidf_vectorizer,
        ann_concept_aliases_list=ann_concept_aliases_list,
        kb=umls_kb,
    )

    return candidate_generator
```

I'm not sure if this makes sense, but think it would be great if instead, you could simply provide the paths to the necessary files directly when initiating a `CandidateGenerator`, so that you could do something like the following:

```
    candidate_generator = CandidateGenerator(
        ann_index="path/to/ann_index",
        tfidf_vectorizer="path/to/tfidf_vectorizer",
        ann_concept_aliases_list="path/to/ann_concept_aliases_list",
        kb="path/to/kb",
    )
```

I hope I explained my thoughts properly :-) Thanks and keep up the good work!!

**Comment by DeNeutoy** [comment]
Hi @ChantalvanSon ,

Great that you got it working, sorry it was a bit tricky.

You raise some good points - there is one way that you can not require your function which loads all the pieces which is this:


```python
from scispacy.candidate_generation import DEFAULT_PATHS, DEFAULT_KNOWLEDGE_BASES
from scispacy.candidate_generation import (
    CandidateGenerator,
    LinkerPaths
)

CustomLinkerPaths_2020AA = LinkerPaths(
    ann_index="path/to/nmslib_index.bin",
    tfidf_vectorizer="path/to//nmslib_index.bin",
    tfidf_vectors="path/to/tfidf_vectorizer.joblib",
    concept_aliases_list="path/to/concept_aliases.json",
)
class UMLS2020KnowledgeBase(KnowledgeBase):
    def __init__(
        self,
        file_path: str = "path/to/2020AA.json",
    ):
        super().__init__(file_path)


# Admittedly this is a bit of a hack, because we are mutating a global object.
# However, it's just a kind of registry, so maybe it's ok.
DEFAULT_PATHS["umls2020"] = CustomLinkerPaths_2020AA
DEFAULT_KNOWLEDGE_BASES["umls2020"] = UMLS2020KnowledgeBase

linker = CandidateGenerator(name="umls2020")

```

Overall, we have it like this so that we can present the simplest possible interface to people who are using scispacy (i.e being able to just pass names to get particular linkers rather than having to know the internals of how the linker is implemented). However I definitely see your point that we should try to make this a bit nicer. In another project I used to work on, we had the concept of using a decorator to register this type of info with the base class, so it can construct itself. That might be a bit of overkill here, but maybe we could provide a function which does this global mutation for you and throws intelligent errors if you e.g try to overwrite something in there? 

I think you're right that we need to fix this if we want people to frequently be able to create their own very specific/custom linkers though so thanks for raising it!

**Comment by ChantalvanSon** [comment]
Hi @DeNeutoy,

Thanks for the alternative! I'm adopting that, since it's indeed a bit nicer without my previous function to bring everything together.

```
```

**Comment by ChantalvanSon** [comment]
Hi @DeNeutoy,

Thanks for the alternative! I'm adopting that, because it's indeed a bit nicer than my previous solution. I completely understand the reasons for implementing it as you did :-) Providing a function that does this global mutation with intelligent errors sounds like a nice addition to `scispacy`.

At the moment, however, I'm running into another, related issue. I'm getting the following error when I try to run your suggested code:

```
Traceback (most recent call last):
  File "linkers/scispacy/custom_candidate_generator.py", line 35, in <module>
    linker = CandidateGenerator(name="umls2020AA")
  File "/Users/chantalvanson/Library/Caches/pypoetry/virtualenvs/umls-i-qzJ2DH-py3.7/src/scispacy/scispacy/candidate_generation.py", line 188, in __init__
    linker_paths=linker_paths, ef_search=ef_search
  File "/Users/chantalvanson/Library/Caches/pypoetry/virtualenvs/umls-i-qzJ2DH-py3.7/src/scispacy/scispacy/candidate_generation.py", line 98, in load_approximate_nearest_neighbours_index
    cached_path(linker_paths.tfidf_vectors)
  File "/Users/chantalvanson/Library/Caches/pypoetry/virtualenvs/umls-i-qzJ2DH-py3.7/lib/python3.7/site-packages/scipy/sparse/_matrix_io.py", line 123, in load_npz
    with np.load(file, **PICKLE_KWARGS) as loaded:
  File "/Users/chantalvanson/Library/Caches/pypoetry/virtualenvs/umls-i-qzJ2DH-py3.7/lib/python3.7/site-packages/numpy/lib/npyio.py", line 444, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
```

I remember seeing this error before and somehow got it running, but now I don't seem to be able to replicate what was going on. It seems to be related to `numpy` having changed the default value for the `allow_pickle` parameter from `True` to `False` (see also [this issue](https://github.com/automl/auto-sklearn/issues/668)). However, fixing the `numpy` version to 1.16.2 in my virtual env didn't fix the issue for me.

Any ideas on how to fix this?

**Comment by DeNeutoy** [comment]
I think this issue has been mostly resolved by #247 - if people like the new entity linkers and we get requests for people to be able to make their own, we might add this global registry in a bit more of a formal way, but I think we'll punt on that for now as @ChantalvanSon seems to have figured out a reasonable way to make custom linkers.

**Comment by GregSilverman** [comment]
@DeNeutoy , I'm slightly confused by this issue and by the referenced paper. My understanding is that SNOMED is only distributable through a licensed agreement, which is bundled into the full UMLS licensing scheme, as per [snomed_licensing](https://www.nlm.nih.gov/healthit/snomedct/snomed_licensing.html).

Given this, how can the scispaCy model be unlicensed? 

Thanks in advance!

**Comment by gfhayworth** [comment]
I was able to get this working.  I needed to include a couple of minor tweaks.
Added: 
`from scispacy.linking_utils import KnowledgeBase`

I applied to code shown by @DeNeutoy 
then I was able to add_pipe with the new name: 
`umls_nlp.add_pipe("scispacy_linker", config={"resolve_abbreviations": True, "linker_name": "umls2020" } )`
