### ISSUE TITLE
Spacy's similarity function using model: en_core_sci_lg doesn't give accurate results

### ISSUE THREAD

**Issue by radiatechs-himanshu** [allenai/scispacy#238]
Hi,
I have used Spacy's similarity function using model : en_core_sci_lg for comparing 2 medical abstracts . Even both are giving high degree of similarity but from user point of view they are not similar. Can you please let us know underlying what algorithm is similarity function using and does Spacy or Scispacy has other similarity function which will change the behaviour?

Abstract 1: "Background: Pazopanib is approved for the first-line treatment of patients with metastatic renal cell carcinoma (mRCC). The present study was a retrospective registry-based analysis of 426 patients with mRCC treated with pazopanib as first-line targeted therapy. Patients and Methods: The data were obtained from the Renal Cell Carcinoma Information system registry. Patient baseline parameters, treatment course and outcomes, and toxicity were analysed. Results: Median progression-free and overall survival were 12.9 (95% confidence interval(CI)=11.0-14.8) months and 33.2 (95% CI=29.9-36.4) months, respectively. Overall response rate and disease control rate were 25.1% and 57.4%, respectively. Adverse events led to discontinuation of treatment in 37 (12.1%) patients. Conclusion: The results confirm that pazopanib is an effective and safe first-line targeted treatment in patients with mRCC. Both the International mRCC Database Consortium and the Memorial Sloan Kettering models were valid predictors of prognosis and nephrectomy was associated with improved survival."

Abstract2="Aim: To assess the association between tumor response and health-related quality of life (HRQoL) in patients with metastatic Merkel cell carcinoma treated with the anti-PD-L1 avelumab. Materials & methods: Phase II single-arm trial (NCT02155647) data of 88 patients were analyzed. Correlations between percentage reduction in tumor size and change from baseline in Functional Assessment of Cancer Therapy - General (FACT-G), FACT - Melanoma (FACT-M) and EuroQol-5 Dimension scores were calculated. HRQoL and utility by tumor response (per the Response Evaluation Criteria In Solid Tumors version 1.1) was estimated. Results: Tumor shrinkage correlated positively with patients' change from baseline in the FACT-M total (0.364 [95% CI: 0.050-0.607]) and subscale scores. Differences in HRQoL and utility between nonprogressive disease and progressive disease were clinically relevant. Conclusion: In patients with metastatic Merkel cell carcinoma, nonprogression during treatment with avelumab correlated with gains in HRQoL.Trial registration This study is a planned exploratory analysis conducted on data collected in Part A of the JAVELIN Merkel 200 trial. This trial was registered on 2 June 2014 with ClinicalTrials.gov as NCT02155647."

As per user Abstract1 is of use and asbtract2 'population not of interest
Is there a different way to achieve this ?

**Comment by DeNeutoy** [comment]
Hi @radiatechs-himanshu , yes the doc vectors are just averages of the word vectors, which means they aren't that great past the sentence/phrase level. Sorry, there isn't much we can do about that because this is spacy functionality, rather than scispacy specific.

**Comment by chen-yifu** [comment]
Hi, 

Thanks for this post. 

Does the "doc.similarity(...)" function use the word vector from Spacy (which is not specifically trained on biomedical text at all)? 

In other words, is there any difference between calling "doc.similarity(...)" via Spacy or Scispacy?

Thanks a lot for your attention,
Yifu
