### ISSUE TITLE
scispacy.linking module not recognized 

### ISSUE THREAD

**Issue by maxfarrell** [allenai/scispacy#239]
Hello, 

I am just starting to try scispacy and the demo looks great, but when I try running through the Example Usage for the EntityLinker I get the error : "No module named 'scispacy.linking'.

I have just installed scispacy version 0.2.4 via pip as per the Readme

Thanks for developing what looks to be a great resource!

**Comment by danielkingai2** [comment]
Could you please paste your whole code and the output of `pip list` in your environment so that we can try to help?

**Comment by DeNeutoy** [comment]
@maxfarrell , we've recently updated the entity linking code so the master branch is not correct for the released version. Please try the instructions/snippets on the `v0.2.4` branch here:

https://github.com/allenai/scispacy/tree/v0.2.4
