### ISSUE TITLE
UmlsEntityLinker file in cache

### ISSUE THREAD

**Issue by giuliacassara** [allenai/scispacy#242]
Hi! Everytime I run this line of code
linker = UmlsEntityLinker(resolve_abbreviations=True)
it will download the file tfidf_vectors_sparse.npz in a temporary folder. I want to avoid to download it every time, but I don't understand where the script is looking for the file. I was looking at your code https://github.com/allenai/scispacy/blob/master/scispacy/file_cache.py and I find this reference : SCISPACY_CACHE but I can't find it in my home path.

**Comment by giuliacassara** [comment]
Ok, it is looking on ('~.scispacy'). I have downloaded the file tfidf_vectors_sparse.npz there but still, when I run linker = UmlsEntityLinker(resolve_abbreviations=True) it doesn't find anything in cache.

**Comment by DeNeutoy** [comment]
@giuliacassara hmm, that is surprising. Can you paste the output of running it twice along with the contents of `ls ~/.scispacy` please?

**Comment by GanjinZero** [comment]
The main reason of this error is scispacy check cache_path with a sha256 prefix in **file_cache.py**, putting **tfidf_vectors_sparse.npz** in **~/.scispacy/datasets** is not enough.

```python
filename = url_to_filename(url, etag)
cache_path = os.path.join(cache_dir, filename)
```
