### ISSUE TITLE
Inaccurate predictions using biomedical NER models

### ISSUE THREAD

**Issue by mariosaenger** [allenai/scispacy#243]
Hi,

I just experimented with the specialised NER models for the biomedical and found some rather strange annotation artifacts. Especially, there seems to be an issue if two entities occur consecutively.  For example, see the following sentence from the BioNLP13-CG corpus and the predicted entities (using en_ner_bionlp13cg_md): 

- METHOD: The intratumor microvessel density (IMVD), apoptotic index (AI) and vascular endothelial growth factor (VEGF) expression were detected by immunohistochemistry SABC and terminal uridine deoxynucleotidyl transferase mediated nick end labeling(TUNEL) methods in34 LSCC patients.
 -> intratumor microvessel(TISSUE)
 -> IMVD(GENE_OR_GENE_PRODUCT)
 -> vascular endothelial growth factor(GENE_OR_GENE_PRODUCT)
 -> VEGF(GENE_OR_GENE_PRODUCT)
 -> **LSCC patients(CANCER)**

Normally it should be LSCC (CANCER) and patients (SPECIES/ORGANISM). The latter should be easily recognizable by the model.

**Comment by DeNeutoy** [comment]
Hi @mariosaenger ,

The bionlp13cg model does not have a `SPECIES/ORGANISM` entity type. So this is likely the reason. You might have better luck with the general mention detector in the main models, and then using the entity linker to identify types.

**Comment by mariosaenger** [comment]
Hi @DeNeutoy ,

may I was a bit misleading. I meant `ORGANISM`, however this entity type is called `SPECIES` in other corpora. According to https://allenai.github.io/scispacy/, bionlp13cg should have this entity type and there over over 100 occurrences of "patients" as `ORGANISM` in the training set of the corpus. 

Additionally, I found such issues (with two entities that occur consecutively) in several other cases, e.g.

- In this work, we show that an 11-amino acid peptide derived from the second immunoglobulin-like domain of Flt-1 functions as an angiogenic inhibitor in chick chorioallantoic membrane and inhibited VEGF-induced vascular permeability in Miles' assay without binding to VEGF directly.
  -> ...
  -> **chick chorioallantoic membrane(ORGANISM)**
  -> ...

   Here, "chick" is `ORGANISM` and chorioallantoic membrane is `MULTI-TISSUE_STRUCTURE`. 

- Taken together , our studies , based on a molecular imaging approach for semiquantitative detection of micrometastases , point to an important role of tumor lymphatics in the metastatic process of human prostate cancer .
  -> ...
  -> **human prostate cancer(ORGANISM)**
  -> ...

  Here, "human" is `ORGANISM` and "prostate cancer" is `CANCER` 
 
- DNA of the non-tumorigenic cell hybrids transformed Rat-1 cells to anchorage-independent proliferation as expected for the transforming human Ha-ras gene present in the donor DNA.
  -> ..
  -> **human Ha-ras(ORGANISM)**
  -> ..

  Here, "human" is `ORGANISM` and "Ha-ras" is `GENE_OR_GENE_PRODUCT`

**Comment by DeNeutoy** [comment]
Hi @mariosaenger thanks for the additional info.

It seems like this is an annotation design in the original data which is a bit unfortunate:

https://github.com/cambridgeltl/MTL-Bioinformatics-2016/blob/master/data/BioNLP13CG-IOB/train.tsv#L2167


It annotates noun modifiers here as separate entities, which in some cases can be correct, but makes using a practical NER model substantially harder. For example in the line linked above, I don't really think that "human" refers to an entity - it's being used in an abstract sense, to modify the cell type. The word "human" in this sentence has no agency. 

Not only is this kind of dubious annotation, but it is also inconsistent:

https://github.com/cambridgeltl/MTL-Bioinformatics-2016/blob/master/data/BioNLP13CG-IOB/train.tsv#L2450

Here only _some_ of the noun modifiers are included in the entity. For me this is pretty damning and likely the reason that the F1 performance on this dataset is not that high.

Even within this phenomena of annotating organism modifiers as entities, it is done inconsistently: 

https://github.com/cambridgeltl/MTL-Bioinformatics-2016/blob/master/data/BioNLP13CG-IOB/train.tsv#L7570

here, it's pretty hard to argue that "amphibian" shouldn't also be an ORGANISM.


This is actually quite interesting, but it's kind of tricky to fix without a bit of effort cleaning up the training data. However, that's probably not too difficult, to go through and filter entity boundaries which are modifiers or something.

**Comment by mariosaenger** [comment]
Hi @DeNeutoy ,

sorry for the late response. I agree with the issues you mentioned - some of these annotations are worth discussing.
