### ISSUE TITLE
Warning about incompatible spaCy models.

### ISSUE THREAD

**Issue by dwadden** [allenai/scispacy#244]
I get the following error when trying to load `en_core_sci_sm`:

```
UserWarning: [W031] Model 'en_core_sci_sm' (0.2.4) requires spaCy v2.2 and is incompatible with the current spaCy version (2.3.0). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
```

Steps to reproduce:
Create clean Conda environment and activate
```
conda create --name scispacy python=3.8
conda activate scispacy
```

Install scispacy and install the latest `en_core_sci_sm` model.
```
pip install scispacy
pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_core_sci_sm-0.2.4.tar.gz
```

Attempt import
```
(scispacy) $ python -c "import spacy; nlp=spacy.load('en_core_sci_sm')"
/home/davidw/miniconda3/envs/scispacy/lib/python3.8/site-packages/spacy/util.py:271: UserWarning: [W031] Model 'en_core_sci_sm' (0.2.4) requires spaCy v2.2 and is incompatible with the current spaCy version (2.3.0). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
```

Is this warning important or can I ignore it?

Thanks,

Dave

**Comment by danielkingai2** [comment]
Looks like the spacy 2.3.0 release requires retraining the models. Can you go back to `spacy==2.2.4`?

**Comment by dwadden** [comment]
That fixed it. Thanks!

**Comment by danielkingai2** [comment]
I'm going to reopen this because we need to retrain the models for spacy 2.3.0 and other people will hit this, thanks for reporting!

**Comment by dwadden** [comment]
OK sounds good.

**Comment by FrancescoCasalegno** [comment]
I have observed the same problem. 

Also, notice that the [new 1.10 release of Prodigy](https://prodi.gy/docs/changelog#v1.10.0) requires `spacy` v2.3. This means that `prodigy` v1.10 cannot be used to fine-tune ScispaCy models.

**Comment by snosrap** [comment]
I ran into this as well -- 1.10 release of Prodigy requires spacy 2.3

Here are some [release notes on spacy 2.3](https://spacy.io/usage/v2-3#incompat) that mention incompatibility with models trained on earlier versions

**Comment by DeNeutoy** [comment]
closed by #247

**Comment by Komal-99** [comment]
i am facing same issue while importing en_core_web_sm in python3 and can't retrain spacy version from 2.3.5 to 2.2.5

**Comment by blazespinnaker** [comment]
I followed the instructions here:

https://spacy.io/usage

```
pip install -U pip setuptools wheel
pip install -U spacy
python -m spacy download en_core_web_sm
```

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
en-core-web-sm 3.1.0 requires spacy<3.2.0,>=3.1.0, but you have spacy 3.2.1 which is incompatible.
en-core-web-lg 3.1.0 requires spacy<3.2.0,>=3.1.0, but you have spacy 3.2.1 which is incompatible.
allennlp 2.8.0 requires spacy<3.2,>=2.1.0, but you have spacy 3.2.1 which is incompatible.
Successfully installed spacy-3.2.1
```

**Comment by OLGJ** [comment]
Any fix to this?

`UserWarning: [W094] Model 'en_core_web_sm' (2.2.0) specifies an under-constrained spaCy version requirement: >=2.2.0. This can lead to compatibility problems with older versions, or as new spaCy versions are released, because the model may say it's compatible when it's not. Consider changing the "spacy_version" in your meta.json to a version range, with a lower and upper pin. For example: >=3.4.2,<3.5.0
  warnings.warn(warn_msg)`
