### ISSUE TITLE
How to print all the trained entities in scispacy model? 

### ISSUE THREAD

**Issue by Raghu17s** [allenai/scispacy#248]
Hi folks,

I am using scispacy(md) and would like to check what are the entities are present in the model? How do I print them?
Further, Is there any way I can remove particular entity from the trained scispacy model?

My second question how can I disable accroyms expansion?

Thanks

**Comment by danielkingai2** [comment]
Hi, are you referring to the entities output by the mention detector (i.e. strings) or the entities output by the entity linker (i.e. umls entities)?

**Comment by Raghu17s** [comment]
Hi,
I am referring to all the entities trained in scispacy (md). Not wrt to any input. 
And Also, is there any way in can remove some entities from trained model? Let us say, I don't want to extract them.

**Comment by danielkingai2** [comment]
I still don't know whether you are talking about the mention detector or the entity linker. Are you using the model like this:
```
nlp = spacy.load('en_core_sci_md')
doc = nlp("Text")
entities = doc.ents
```

or like this:
```
nlp = spacy.load('en_core_sci_md')
nlp.add_pipe(EntityLinker())
doc = nlp("Text")
entities = [ent._.kb_ents for ent in doc.ents]
```
