### ISSUE TITLE
scispacy spacy and en_core_sci_lg version deadlock

### ISSUE THREAD

**Issue by ritika24-s** [allenai/scispacy#256]
i am using 
scispacy v 2.5.0 
en_core_sci_lg v 2.4
in the same code
when spacy is installed as dependency for them, a version of spacy which complements the compatibility of one package violates the compatibility of other. can you suggest the version corresponding to all the three of them which can work simultaneously without throwing a warning message.
also if you recommend a scispacy version for the set, i require it to have entity linker functionality.

**Comment by DeNeutoy** [comment]
This is not possible, sorry - the versions are incompatible. The mesh linker is only in the latest release, and that requires the most up to date version of spacy - 2.3.x
