### ISSUE TITLE
scispacy entitylinker

### ISSUE THREAD

**Issue by radiatechs-karan** [allenai/scispacy#257]
error in creating the object Linker
Linker = EntityLinker()
using scispacy-0.2.5 and en_core_sci_sm-0.2.5  
[entity_linker_error_log.txt](https://github.com/allenai/scispacy/files/4970609/entity_linker_error_log.txt)
file includes the error log the packages and dependencies installed and docker file for the container environment

**Comment by danielkingai2** [comment]
Hi, I am not able to reproduce this, even using your Dockerfile and requirements. Could you try again and make sure to fully rebuild the docker image?
