### ISSUE TITLE
Combine multiple NER and make 1

### ISSUE THREAD

**Issue by jdjmoon** [allenai/scispacy#261]
Hello,

I am new to SciSpacy, and I was wondering if there are anyway to combine NER from different model and make into one :

ner1 = en_core_web_lg.load()
ner2 = en_ner_bionlp13cg_md.load()

ner = ner1 + ner2

Thank you

**Comment by danielkingai2** [comment]
There isn't currently a way to use multiple ner models in the same pipeline. You can definitely run them each independently and then combine results however you like (by writing your own code). Also, see this issue (explosion/spaCy#2920) about the same thing.

**Comment by DeNeutoy** [comment]
Hi @jdjmoon, Daniel's answer above is the best there is for this at the moment, sorry - it's a bit annoying!
