### ISSUE TITLE
how to add new phrases/ words in the pretrained scispacy model

### ISSUE THREAD

**Issue by madhurkgp** [allenai/scispacy#262]
```
import en_core_sci_lg
nlp = en_core_sci_lg.load()

sentence = """Resident received in bed with eyes closed. 
Nebulizer Treatment Ipratropium-Albuterol for Shortness of Breath given as ordered and tolerated well. 
Comfort and safety measures maintained. Will continue to monitor."""

doc = nlp(sentence)

[ents for ents in doc.ents]
```

The output is - 
**[Resident, received, bed, eyes, closed, Nebulizer Treatment Ipratropium-Albuterol, 
Shortness, ordered, tolerated, Comfort, safety, measures, monitor]**

What I wanted to add "Shortness of Breath" keyword in the nlp piepline so that instead of "shortness" or "breath" , it recognizes the comple phrase "shortness of breath". 

Also can we remove a keyword from the nlp model?

**Comment by DeNeutoy** [comment]
Hi @madhurkgp ,

You might try https://spacy.io/api/pipeline-functions#merge_noun_chunks . If you add this to the pipeline BEFORE the NER model it might fix your issue, as then noun chunks would be treated as single tokens.

**Comment by madhurkgp** [comment]
and what if we want to remove some words from being getting identified?

**Comment by DeNeutoy** [comment]
@madhurkgp You can't stop them from being identified, but for whatever you are using them for, you can just check if they contain words that you don't want in them?
