### ISSUE TITLE
How to replace the our own EntityLinkiner?

### ISSUE THREAD

**Issue by Raghu17s** [allenai/scispacy#267]
Hi Folks,

I have been working with Scispacy for some time and found it interesting. 
I have found some limitations like the same entity is matching different targets with same score. When I match CUI to SNOMED it gives different meanings in SNOMED vocabulary. 
Currently, I am mapping CUI to SNOMED using UMLS MRCONSO.RRF mapping file. 
I am exploring is there any way that we can replace newly trained EntityLiker, Like train aliases directly with SNOMED code instead of CUI. 
I have the text with their aliases and a unique ID for the same. 

Please suggest me.

**Comment by DeNeutoy** [comment]
Hi @Raghu17s ,

Please take a look at this issue - it describes how to train your own entity linker:

https://github.com/allenai/scispacy/issues/237

Thanks!
