### ISSUE TITLE
Entity Linking NER mismatch check

### ISSUE THREAD

**Issue by cshivade** [allenai/scispacy#269]
Hello,

Thanks for creating a great library for the community! 

I was going through the Entity Linking code and was wondering if there should be a check before [this line](https://github.com/allenai/scispacy/blob/master/scispacy/candidate_generation.py#L345) along the lines of
```
if mention in self.kb.alias_to_cuis:
    concepts_for_mention = self.kb.alias_to_cuis[mention]
    ....
```
since it could happen that NER might not have captured the mention.

**Comment by danielkingai2** [comment]
I'm sorry, I don't quite understand your question. The `ann_concept_aliases_list` is ```        A list of strings, mapping the indices used in the ann_index to possible KB mentions.
        This is essentially used a lookup between the ann index and actual mention strings.```, so it can't really be missing from the kb. Did you encounter an error?

**Comment by cshivade** [comment]
Sorry the error stemmed from a silly mistake at my end. I had misspelt the name of a kb i created and edited `DEFAULT_KNOWLEDGE_BASES`. The KB by default loaded UMLS while the `ann_concept_aliases_list` was correctly loaded. Hence there was a mismatch. I will close the issue.
