### ISSUE TITLE
Is there a way to disable entity linker and its dependencies?

### ISSUE THREAD

**Issue by swartchris8** [allenai/scispacy#270]
In my production environment I can't install or run hnswlib. Is there a way I can install scispacy without the entity linker and its dependencies? I am happy to work on a way to decouple scispacy like this if this would be an acceptable contribution. I think it would be good to split the entity linking for other users as well.

**Comment by danielkingai2** [comment]
Hi @swartchris8, you can install scispacy with `pip install scispacy --no-deps`. This will not install any of the requirements for the package, and then you can install all of the requirements except for `nmslib`. You could also clone the repo, edit the requirements file and `setup.py` to remove `nmslib`, and then install from source. Does one of these solutions work for you? Or did you have another solution in mind?

**Comment by swartchris8** [comment]
Thanks for the great package, I realise I might not need the scispacy package installed if I just start working from the model directly and then I don't have to worry about disabling the linker until I can see if I can run this on Dataflow.
