### ISSUE TITLE
Adding support for different languages on UMLS EntityLinker

### ISSUE THREAD

**Issue by arianpasquali** [allenai/scispacy#271]
UMLS supports different languages besides English, but it seams harder than I expected to add support for that on top of the current UMLS EntityLinker.

We have https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/data/umls_2020_aa_cat0129.jsonl
and as far as I understood it was generated using the script https://github.com/allenai/scispacy/scripts/export_umls_json.py

The resulting jsonl file is referenced at https://github.com/allenai/scispacy/blob/f9144f42724afa621b6f4b0403c761b9154ad4ab/scispacy/linking_utils.py#L39-L41

I assume we should change the script https://github.com/allenai/scispacy/blob/master/scripts/export_umls_json.py to generate the alias file accordingly to the language we want.

However, I see that we have more references to language resources like tfidf vectors and other preprocessed files in the code. It iss not clear how to generate those files for another language.

https://github.com/allenai/scispacy/blob/15dfead09af3af3ff6a565b977b5128be9224867/scispacy/candidate_generation.py#L43-L48

Any help on how to add support for other languages on your UMLS EntityLinker?

**Comment by arianpasquali** [comment]
I believe I found it where to add language support using umls_utils.
https://github.com/allenai/scispacy/blob/8994934b986d4e16414ef038c162b44c1a4bdd2b/scispacy/umls_utils.py#L60-L68

language resources and indexes are generated at https://github.com/allenai/scispacy/blob/15dfead09af3af3ff6a565b977b5128be9224867/scispacy/candidate_generation.py#L360

**Comment by DeNeutoy** [comment]
Hi @arianpasquali, looks like you figured this out! Those are the right directions. Let us know if you run into any problems! Currently it would require modifying that function to pick up non-english sources, from UMLS (and requires that you have access to a UMLS export).
