### ISSUE TITLE
Document location of models for older versions

### ISSUE THREAD

**Issue by martijnvanbeers** [allenai/scispacy#273]
At the bottom of the README it says to document the version and model used for reproducibility. For this to really work, you would have to be able to download older versions of the models, but it isn't obvious how to do so. When I try simply replacing the version numbers in the url, I get `403 Permission Denied` errors. Is there a way I can find out how to download older models that I have missed?

**Comment by DeNeutoy** [comment]
Hi @martijnvanbeers,

We tag all our releases on github, so hopefully you should be able to checkout that tag and get the download URLs from there. For example:

https://github.com/allenai/scispacy/tree/v0.2.0


Admittedly this isn't completely transparent, I agree. Sorry about that!

**Comment by martijnvanbeers** [comment]
Oh right. That should have occurred to me. Thanks.
