### ISSUE TITLE
training NER from scratch and on top of existing NER models

### ISSUE THREAD

**Issue by wpan5** [allenai/scispacy#281]
Hi sciSpacy team,

I've been working on a project that's using spaCy to train a NER model from scratch (using a blank model) with my annotated biomedical data. From spaCy's documentation, I understand that pipeline components like tagger, parser, and entity recognizer are independent; and the default NER training scripts disabled all pipes other than 'NER'. The final results (entity-level F1) I got from spaCy were poor. I've been trying to find areas to improve, and have a few general questions about spaCy and sciSpacy. I'm new to NLP so I've likely missed something critical...

1. Would training NER from scratch (using a blank model) with my own data yield similar results for spacy and sciSpacy? 
2. Would I likely benefit from training on top of the existing models like 'en_core_sci_md', or pretrained NER models like 'en_ner_craft_md'? My data do have very different entity types than those of, say, 'CRAFT' or 'JNLPBA', so I assume it'll be challenging due to conflicts in annotations.

Thanks!

**Comment by DeNeutoy** [comment]
Hi @wpan5,

Yes, training from scratch would result in similar performance for spacy and scispacy. The only difference is the vocabulary, which makes a slight difference but is basically negligible. 

You're also right that you probably won't get much benefit from training on top of another NER model that has different types. I would suggest you look at tools like prodigy (Spacy's very nice annotation tool) to help you create a dataset for your task. It's a little hard to give suggestions as I'm not sure what problem you are working on - if you describe it in more detail we might be able to give you more precise advice. E.g for biomed, we have quite a few entity linkers which might do what you need?

**Comment by wpan5** [comment]
Hi Mark,

Thanks for the clarification and suggestions. I just checked out the entity linkers available in scispaCy. We sort of created our own ontology and annotated our data accordingly, so I assume it might be difficult to incorporate existing entity linkers. 

I'll explore tools like Prodigy. Thanks again.
