### ISSUE TITLE
Caching issues (?) with the linker

### ISSUE THREAD

**Issue by jusjosgra** [allenai/scispacy#289]
Hello! Firstly, thanks for an amazing library - scispacy is great!!

I seem to be running into some caching issues when using the linker. Periodically when running scripts that load the linker I get errors like
`requests.exceptions.SSLError: HTTPSConnectionPool(host='s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /ai2-s2-scispacy/data/kbs/2020-10-09/umls_2020_aa_cat0129.jsonl (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1076)')))`

after having successfully run previously. I suspect this is related to caching although not sure. I have received errors like this about 3 times but it is inconsistent.

Is it possible to manually manage the linker object? Looking at the formatting I assume it is not just that one file and is sharded.

**Comment by danielkingai2** [comment]
Hey Justin, is this a persistent issue? The most likely problem is some transient internet or AWS problem. Also, see @DeNeutoy's comment here (https://github.com/allenai/scispacy/pull/288#pullrequestreview-538218110) for a way to use local files. The files are not sharded or anything fancy, there are just multiple files needed, as shown in the code that Mark links to in that comment.

**Comment by DeNeutoy** [comment]
Yeah, I think this might have been related to the aws-east outage last week or something? I saw a lot of people's IOT doorbells not working 😄  - but if it isn't we can look into it!

**Comment by danielkingai2** [comment]
I'm going to close this due to inactivity, but feel free to reopen if you are still having issues!

**Comment by jusjosgra** [comment]
sorry for not replying -- it did seem to be an intermittent error. Perhaps relating to outage. I will reopen if the issue returns. Thanks!
