### ISSUE TITLE
Error while running test_data_util.py

### ISSUE THREAD

**Issue by yogeshhk** [allenai/scispacy#292]
Function: test_example_iterator()
Assertion fails at assert entity.mention_text == example.text[entity.start: entity.end] because
entity.mention_text = polished silicon
example.text[entity.start: entity.end] = d polished silic
Meaning, indices entity.start: entity.end are wrong?

**Comment by danielkingai2** [comment]
I don't think this test is failing on master. What are you trying to do?

**Comment by yogeshhk** [comment]
Just reporting the test case failure, seen without any code change.

**Comment by danielkingai2** [comment]
That test doesn't fail for me on master. Are you sure you haven't changed any code or files? If so, please make sure your environment has the versions of all the packages specified in the requirements file.

**Comment by yogeshhk** [comment]
I haven't changed any code. The other asserts/example-strings in the same test are not failing. Just this one, so thought of reporting it.

**Comment by danielkingai2** [comment]
I am quite sure that this test passes on master. Do you have any thought of why it might be failing for your local setup? What are your environment details (e.g. OS, python version, output of `pip list`)? Can you try recloning the repo, just to make absolutely sure you haven't accidentally changed something?

**Comment by yogeshhk** [comment]
Attaching  `conda env export > environment.txt' file for comparison with similar one from working/master env.

[environment.txt](https://github.com/allenai/scispacy/files/5727311/environment.txt)

**Comment by danielkingai2** [comment]
Turns out this is because you are on windows. We don't really support windows, but i've fixed this one in #293
