### ISSUE TITLE
Documentation / sample code for using MESH linker

### ISSUE THREAD

**Issue by gkovaig** [allenai/scispacy#296]
Looking for documentation or sample code for using the MESH linker.
Have been successful at using the UMLS linker.  Find it too complex for my needs, and would like to try a simpler ontology.

**Environment:**
Linux, JupyterHub, python 3.6

**Tried so far:**
import scispacy; print(scispacy.__version__) # 0.3.0
from scispacy.umls_linking import UmlsEntityLinker
nlp = en_core_sci_lg.load()

abbrev = AbbreviationDetector(nlp)
nlp.add_pipe(abbrev)

linker = UmlsEntityLinker(resolve_abbreviations=True)
nlp.add_pipe(linker)

doc = nlp('''The geographic spread of 2019 Novel Coronavirus (COVID-19) infections from the epicenter of Wuhan, China, has provided an opportunity to study the natural history of the recently emerged virus. Using publicly available event-date data from the ongoing epidemic, the present study investigated the incubation period and other time intervals that govern the epidemiological dynamics of COVID-19 infections. Our results show that the incubation period falls within the range of 2&ndash;14 days with 95% confidence and has a mean of around 5 days when approximated using the best-fit lognormal distribution. The mean time from illness onset to hospital admission (for treatment and/or isolation) was estimated at 3&ndash;4 days without truncation and at 5&ndash;9 days when right truncated. Based on the 95th percentile estimate of the incubation period, we recommend that the length of quarantine should be at least 14 days. The median time delay of 13 days from illness onset to death (17 days with right truncation) should be considered when estimating the COVID-19 case fatality risk.''')
doc.ents # returns a tuple 47 items

Expected behavior:
Modified code to use MESH linker instead of UMLS linker.

Thank you!

**Comment by gkovaig** [comment]
Made a little progress:
# instead of from scispacy.umls_linking import UmlsEntityLinker
from scispacy.linking import EntityLinker

# instead of linker = UmlsEntityLinker(resolve_abbreviations=True)
linker = EntityLinker(name='mesh', resolve_abbreviations=True)

Now, looking for the equivalent of:
for umls_ent in test[0]._.umls_ents:
    print(len(umls_ent), linker.umls.cui_to_entity[umls_ent[0]])

Am finding that doc.ents[0]._.kb_ents returns an empty list.

**Comment by danielkingai2** [comment]
Hi @gkovaig, I think you are looking for this section of the readme https://github.com/allenai/scispacy#example-usage-1

**Comment by danielkingai2** [comment]
I'm going to close this under the assumption that the readme answers your questions, but feel free to reopen or open a new issue if your still having problems!
