### ISSUE TITLE
How to use scispacy for detection of German biomedical terms?

### ISSUE THREAD

**Issue by sbhttchryy** [allenai/scispacy#297]
First of all, thank you for the wonderful work. I have a question. Is it possible to use scispacy  to detect German biomedical terms? has any experiments been done in this context? Thank you.

**Comment by DeNeutoy** [comment]
Hi @sbhttchryy,

That would be difficult because scispacy only provides english language models. Sorry about that!

You may wish to look at the various German sources in UMLS:

https://www.nlm.nih.gov/research/umls/sourcereleasedocs/index.html

Good luck!
