### ISSUE TITLE
Support spaCy 3.0

### ISSUE THREAD

**Issue by davidmezzetti** [allenai/scispacy#303]
spaCy was upgraded to 3.0 this week and it appears the current version of scispacy is incompatible. I see there is a spacy3 branch and #295 appears to be a WIP on the upgrade. 

Looks like a big pull on the move to 3.0. Do you have an idea on the timeline for the upgrade? Thank you for putting this project out there!

Here is the stack using a Python 3.8 virtualenv with spacy 3.0.1 and en_core_sci_md 0.3.0 installed. 

```
>>> import en_core_sci_md
/tmp/test/lib/python3.8/site-packages/spacy/util.py:715: UserWarning: [W094] Model 'en_core_sci_md' (0.3.0) 
specifies an under-constrained spaCy version requirement: >=2.3.1. This can lead to compatibility problems with 
older versions, or as new spaCy versions are released, because the model may say it's compatible when it's not. 
Consider changing the "spacy_version" in your meta.json to a version range, with a lower and upper pin. 
For example: >=3.0.1,<3.1.0
  warnings.warn(warn_msg)
>>> en_core_sci_md.load()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/test/lib/python3.8/site-packages/en_core_sci_md/__init__.py", line 10, in load
    nlp = load_model_from_init_py(__file__, **overrides)
  File "/tmp/test/lib/python3.8/site-packages/spacy/util.py", line 514, in load_model_from_init_py
    return load_model_from_path(
  File "/tmp/test/lib/python3.8/site-packages/spacy/util.py", line 388, in load_model_from_path
    config = load_config(config_path, overrides=dict_to_dot(config))
  File "/tmp/test/lib/python3.8/site-packages/spacy/util.py", line 545, in load_config
    raise IOError(Errors.E053.format(path=config_path, name="config.cfg"))
OSError: [E053] Could not read config.cfg from /tmp/test/lib/python3.8/site-packages/en_core_sci_md/
en_core_sci_md-0.3.0/config.cfg
```

**Comment by danielkingai2** [comment]
Yes, please see #295. It is in progress, thanks!

**Comment by davidmezzetti** [comment]
Appreciate the rapid response, thank you! Please feel free to close this issue if you feel it's duplicative.

**Comment by danielkingai2** [comment]
I'll leave it open until we merge the PR so that other people can find it easily :)

**Comment by danielkingai2** [comment]
Slightly premature closing. We've uploaded new models that are compatible with master, but haven't quite done a release yet. If you need it urgently, you should be able to use master and the new models. Otherwise, we should be doing a release sometime in the next week or so.

**Comment by davidmezzetti** [comment]
Thank you for the quick response and turnaround, appreciate it!

**Comment by dnm1977** [comment]
Anxiously awaiting, as well. Thank you.

**Comment by danielkingai2** [comment]
Release released!

**Comment by davidmezzetti** [comment]
Great, thank you for the rapid turnaround!
