### ISSUE TITLE
train a transformer based model

### ISSUE THREAD

**Issue by dakinggg** [allenai/scispacy#304]
since spacy as a whole is supporting transformer based models, perhaps we should train one

**Comment by danielkingai2** [comment]
for NER

**Comment by rakesh4real** [comment]
I am interested. Can you share some references so that I can implement it?

**Comment by rakesh4real** [comment]
@danielkingai2 

1. where can I find **training code** for all the models mentioned below
2. Are they supervised or unsupervised
3. I want to know what option do I have to proceed with unsupervised training


![Screenshot 2021-03-06 at 1 43 49 AM](https://user-images.githubusercontent.com/45640029/110168602-6fd03700-7e1d-11eb-947b-9a8570648e25.png)

**Comment by danielkingai2** [comment]
The full training for all the models is done via spacy projects, so using our project.yml and the configs it references. It is supervised. The scibert model starts from the scibert pretrained weights, but any pretrained model from huggingface could be used instead.
