### ISSUE TITLE
Error adding Abbreviation Detector Pipeline

### ISSUE THREAD

**Issue by quangduc** [allenai/scispacy#311]
Hi, I added abbreviation_detector pipeline to spacy but met this error. I think it's related to spacy version conflict. I'm using scispacy-0.2.4, spacy-3.0.1. Can you please tell me, or give me a hint on how I solve this? Thanks you

<img width="793" alt="Screen Shot 2021-02-07 at 10 52 20" src="https://user-images.githubusercontent.com/4360657/107142965-91c7be00-6932-11eb-9b52-884de1c510f1.png">

<img width="1666" alt="Screen Shot 2021-02-07 at 10 55 00" src="https://user-images.githubusercontent.com/4360657/107143021-f420be80-6932-11eb-94b3-1615406da747.png">

If I change to use this code, then I met another error below:

<img width="550" alt="Screen Shot 2021-02-07 at 10 55 49" src="https://user-images.githubusercontent.com/4360657/107143040-0d296f80-6933-11eb-8a25-f5aabae02b07.png">

<img width="702" alt="Screen Shot 2021-02-07 at 10 55 59" src="https://user-images.githubusercontent.com/4360657/107143046-13b7e700-6933-11eb-816e-e882bec0614b.png">

**Comment by danielkingai2** [comment]
For now, you need to downgrade spacy to 2.x. You can also install scispacy from master, or wait, and we should be doing a new release compatible with spacy 3 in the next week or so.

**Comment by quangduc** [comment]
I see. Thanks a lot, I will install scispacy from master.

**Comment by danielkingai2** [comment]
We've released the latest version, so this should work now.
