### ISSUE TITLE
Missing Requirement for en_core_sci_scibert

### ISSUE THREAD

**Issue by dgourd** [allenai/scispacy#317]
I had to manually install `spacy[transformers]` before installing `en_core_sci_scibert` before getting it to work.  Maybe add it to the requirements or mention it in the readme?

**Comment by danielkingai2** [comment]
Thanks for pointing this out! I'll look into this, should be a straightforward addition.

**Comment by danielkingai2** [comment]
I've reuploaded the model with the `spacy-transformers` requirement, and am adding a note about gpu usage in the readme here #320. Thanks!
