### ISSUE TITLE
EntityLinker returns different CUIs with every run

### ISSUE THREAD

**Issue by mnhcorp** [allenai/scispacy#319]
Hi,

I'm running into a weird issue with NER extraction.

Different runs on the same document gives me identical entities, but different CUIs. I noticed the EntityLinker guide says it uses an approximate nearest neighbor search while linking entities to the KB.

This is the config I'm using:

```
linker = EntityLinker(resolve_abbreviations=True, name="umls", max_entities_per_mention=1, k=1)
```

Configuration:

```
>>> spacy.__version__
'2.3.4'
>>> scispacy.__version__
'0.3.0'
```

Question: How do I make the results deterministic? 

Thanks!

**Comment by danielkingai2** [comment]
I suspect this is the bug fixed by #298. Are you able to upgrade to the latest scispacy version (and spacy version)?

**Comment by mnhcorp** [comment]
Indeed, upgrading to the latest scispacy (and spacy) fixed it - thanks a lot! :)

Quick sidenote - the new version seems to be eating up WAY too much memory, is this expected? (I'm loading all three - core_sci_sm, ner_bc5cdr & ner_bionlp):

![image](https://user-images.githubusercontent.com/2000186/108050698-fb9d4180-706f-11eb-83fc-898145a66c8b.png)

Thanks again!

**Comment by danielkingai2** [comment]
What are you loading/running exactly? I loaded those three models, and it used ~3G of ram.

**Comment by mnhcorp** [comment]
That's correct: loading the three models take up ~3GB of RAM. It's the EntityLinker that takes up the remaining space. Here's what I'm doing:

```
model = {}
linker_config={"resolve_abbreviations": True, "name": "umls", "max_entities_per_mention": 1}

model['core'] = spacy.load("en_core_sci_sm")
model['bc5cdr']= spacy.load("en_ner_bc5cdr_md")
model['bionlp'] = spacy.load("en_ner_bionlp13cg_md")

model['core'].add_pipe("scispacy_linker", config=linker_config)
model['bc5cdr'].add_pipe("scispacy_linker", config=linker_config)
model['bionlp'].add_pipe("scispacy_linker", config=linker_config)
```

In spacy 2.x we could instantiate the EntityLinker and use it for all pipelines. With spacy 3.x add_pipe doesn't take callables anymore and needs a string (the name of the component factory). This duplicates the EntityLinker instantiation, I think, causing memory use to balloon up.

Thoughts on working around it and using a single EntityLinker instantiation across pipelines?

Thanks!

**Comment by danielkingai2** [comment]
ahh, i see. As a work around, i think you can do something like this, after loading the entity linker on just the core model

```
linker = model['core'].get_pipe('scispacy_linker')
doc = linker(model['bc5cdr'](text))
```

I'm not sure if there is a way to add a pipe without creating a copy of it in spacy3, will have to look into it.

**Comment by mnhcorp** [comment]
Yup, that works - thanks again!
