### ISSUE TITLE
Tokenizer used for NER in Scipacy model : "en_ner_bionlp13cg_md"

### ISSUE THREAD

**Issue by ChaitanyaUpadrasta** [allenai/scispacy#321]
Helllo,

I'm trying to cluster the embeddings of entities generated by my model. To train an embedding model I'll need the same tokenizer that my scispacy model uses. I tried using scispacy custom tokenizer but it does not give me the exact tokens. Could you please help me identify the tokenizer that my NER model uses to identify tokens?

**Comment by danielkingai2** [comment]
Could you please provide the versions of scispacy and spacy in your environment, and a concrete example of what you are doing and where the tokenization differs? The tokenizer on all the scispacy models should be the same as the custom tokenizer in the repo.

**Comment by ChaitanyaUpadrasta** [comment]
scispacy==0.3.0
spacy.__version__ == 2.3.5
model = en_ner_bionlp13cg_md-0.3.0

Code :
nlp = en_ner_bionlp13cg_md.load()
doc = nlp(' '.join(text))

Entities extracted:
![image](https://user-images.githubusercontent.com/63639210/108105266-b4717980-708c-11eb-9ca4-e3aed22f03d5.png)

Tokens:
![image](https://user-images.githubusercontent.com/63639210/108105372-d1a64800-708c-11eb-9dda-256921b5fa9d.png)


 Some of the 4-word entities aren't identified as tokens. Is it possible to get all the entities as tokens?

**Comment by danielkingai2** [comment]
A couple things

1) a "token" is approximately a "word". Entities can be multiple words in general. The entity boundaries should line up with tokens though. So, "New York City" might be an entity, but composed of three tokens, "New", "York", and "City". If you want a vector for "New York City", one way to do this is to average the individual token vectors. I do not know if this would work well for your use case, but it is a common thing to do.
2) From the "Tokens" output, it looks like you are passing a long list of strings to the model. The models were trained on proper sentences, and may not work as well when applied to ungrammatical text.

**Comment by ChaitanyaUpadrasta** [comment]
Thanks for the informatiom.
