### ISSUE TITLE
OSError: [E053] Could not read config.cfg from en_ner_bionlp13cg_md-0.3.0/config.cfg

### ISSUE THREAD

**Issue by shqkrck** [allenai/scispacy#322]
When upgraded version of spacy to 3.0.3, these libraries (en_ner_bionlp13cg_md, en_ner_bc5cdr_md) cannot load. On 
import en_ner_bc5cdr_md
en_ner_bc5cdr_md.load()

I get the following error. 
/root/anaconda3/lib/python3.8/site-packages/spacy/util.py:715: UserWarning: [W094] Model 'en_ner_bionlp13cg_md' (0.3.0) specifies an under-constrained spaCy version requirement: >=2.3.1. This can lead to compatibility problems with older versions, or as new spaCy versions are released, because the model may say it's compatible when it's not. Consider changing the "spacy_version" in your meta.json to a version range, with a lower and upper pin. For example: >=3.0.3,<3.1.0
  warnings.warn(warn_msg)
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-45-c2a08dda597e> in <module>
      1 import en_ner_bionlp13cg_md
----> 2 en_ner_bionlp13cg_md.load()

~/anaconda3/lib/python3.8/site-packages/en_ner_bionlp13cg_md/__init__.py in load(**overrides)
      8 
      9 def load(**overrides):
---> 10     nlp = load_model_from_init_py(__file__, **overrides)
     11     return nlp

~/anaconda3/lib/python3.8/site-packages/spacy/util.py in load_model_from_init_py(init_file, vocab, disable, exclude, config)
    512     if not model_path.exists():
    513         raise IOError(Errors.E052.format(path=data_path))
--> 514     return load_model_from_path(
    515         data_path,
    516         vocab=vocab,

~/anaconda3/lib/python3.8/site-packages/spacy/util.py in load_model_from_path(model_path, meta, vocab, disable, exclude, config)
    386         meta = get_model_meta(model_path)
    387     config_path = model_path / "config.cfg"
--> 388     config = load_config(config_path, overrides=dict_to_dot(config))
    389     nlp = load_model_from_config(config, vocab=vocab, disable=disable, exclude=exclude)
    390     return nlp.from_disk(model_path, exclude=exclude)

~/anaconda3/lib/python3.8/site-packages/spacy/util.py in load_config(path, overrides, interpolate)
    543     else:
    544         if not config_path or not config_path.exists() or not config_path.is_file():
--> 545             raise IOError(Errors.E053.format(path=config_path, name="config.cfg"))
    546         return config.from_disk(
    547             config_path, overrides=overrides, interpolate=interpolate

OSError: [E053] Could not read config.cfg from /root/anaconda3/lib/python3.8/site-packages/en_ner_bionlp13cg_md/en_ner_bionlp13cg_md-0.3.0/config.cfg

SpaCy version 2.x works normally. Is truly the problem only the missing config.cfg?

PS: Thank you for your excellent work! Life is much easier and productive with scispaCy.

**Comment by mnhcorp** [comment]
I hit this when I used the latest spacy + scispacy with older versions of the models.

Fixed by downloading the latest 0.4.0 versions found [on the home page](https://github.com/allenai/scispacy#available-models)

**Comment by shqkrck** [comment]
Excellent, it has worked, thank you. The links to models at https://allenai.github.io/scispacy/ need to be updated, I have used the models 0.3.0 from there.

**Comment by danielkingai2** [comment]
Ah woops, thanks!

**Comment by aparnam2** [comment]
I am facing this error on colab  scispacy-0.4.0+ en_core_sci_sm-0.4.0.  Any pointers how to solve this?

Code
=====
nlpipe = en_core_sci_sm.load()
doc = nlpipe("This is a scientific text.")

Error stack
=======

py.pyx in blis.py.gemm()

ValueError: Buffer and memoryview are not contiguous in the same dimension.

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/spacy/ml/staticvectors.py in forward(model, docs, is_train)
     46         vectors_data = model.ops.gemm(model.ops.as_contig(V[rows]), W, trans2=True)
     47     except ValueError:
---> 48         raise RuntimeError(Errors.E896)
     49     output = Ragged(
     50         vectors_data, model.ops.asarray([len(doc) for doc in docs], dtype="i")

RuntimeError: [E896] There was an error using the static vectors. Ensure that the vectors of the vocab are properly initialized, or set 'include_static_vectors' to False.

**Comment by danielkingai2** [comment]
Could you show the output of `pip list`? this is almost certainly a model version issue.

**Comment by shqkrck** [comment]
Had the same issue. Simply meticilously uninstall all libraries and make sure to install the newest versions.

**Comment by shqkrck** [comment]
And obviously restart the kernel!

**Comment by aparnam2** [comment]
Output of pip list for spacy and the models
==========================
en-core-sci-sm                0.4.0  
spacy                         3.0.3          
spacy-legacy                  3.0.1      
scipy                         1.4.1          
scispacy                      0.4.0

**Comment by danielkingai2** [comment]
what about the output of this?

```
In [7]: scispacy.__version__
Out[7]: '0.4.0'

In [8]: spacy.__version__
Out[8]: '3.0.3'

In [9]: nlp.meta['version']
Out[9]: '0.4.0'
```
