### ISSUE TITLE
 RuntimeError: [E896] 

### ISSUE THREAD

**Issue by itchyknobs** [allenai/scispacy#328]
Hi; I'm trying to run your example code in a Google Colab; but it doesn't appear to work. I'm not sure if it's a version issue. Could you please advise on whether this is an environment issue or if I'm missing the right imports?

![image](https://user-images.githubusercontent.com/31191581/110044501-55973b80-7ced-11eb-8c66-0930d522162b.png)

**Comment by danielkingai2** [comment]
you probably have the wrong version of spacy. you'll need to make sure that you have spacy version >= 3

**Comment by itchyknobs** [comment]
![image](https://user-images.githubusercontent.com/31191581/110045415-ba06ca80-7cee-11eb-909d-aba40dc4cb64.png)
Thanks for the note. I've tried it again with the latest versions of Spacy and Scispacy, in a new notebook and fresh environment, and it's unfortunately still showing the same error.

**Comment by danielkingai2** [comment]
We've had a bunch of people report the same error, and have it go away after using a clean environment (see #318). Could you quadruple check you are reinstalling everything in a totally clean environment? I haven't been able to reproduce this error otherwise, so I don't have another suggestion at the moment.

**Comment by itchyknobs** [comment]
Hi Daniel, per your advice, I've tried to:
1. Factory Reset my notebook and run it again
2. Set up a new Google account, log into a new Colab Notebook and run the same code
3. Run it on a jupyter notebook

Unfortunately, I'm still running into the similar issue. If it helps; this is the Colab link I was trying to reproduce the error on
https://colab.research.google.com/drive/1QdK7nKD37vnZDNMHi329NDxRfUeNWO6Z?usp=sharing

Johnson

**Comment by danielkingai2** [comment]
Thanks for your diligence. I'll have a look at the colab and see if I can figure it out.

**Comment by danielkingai2** [comment]
It appears that your colab environment is not actually a clean environment. I don't use colab much so I'm not too sure why that happens, but if you restart the runtime and just run `!pip list`, there are a lot more packages installed than would exist in a clean python environment. I happened to notice that the version of `blis` in the colab is old, and if you install the latest blis before spacy/scispacy, the error goes away. I'm not sure if there are other package version issues lurking, and would recommend figuring out how to actually create a clean base environment. Hope that helps!

**Comment by itchyknobs** [comment]
Thanks so much for your help. This was incredibly helpful. 

I get your point now. I think Google Colab preinstalls packages that runs well with each other and doesn't do updates unless the new update is stable with all it's other packages. It's unfortunate as a large community of folks must be on colab pulling their hairs out. Thanks again for your help; I'll see how the rest of the notebook goes.
