### ISSUE TITLE
"en_ner_bionlp13cg_md-0.4.0" issue with loading the package

### ISSUE THREAD

**Issue by Rashmikoparde** [allenai/scispacy#332]
I am loading the "en_ner_bionlp13cg_md-0.4.0" package which is throwing the following error.

ValueError: [E912] Failed to initialize lemmatizer. Missing lemmatizer table(s) found for mode 'rule'. Required tables: ['lemma_rules']. Found: [].

Any Solution for this will be helpful.

**Comment by danielkingai2** [comment]
I am not able to reproduce
```
In [1]: import spacy

In [2]: nlp = spacy.load('en_ner_bionlp13cg_md')

In [3]: doc = nlp("Genes are cool.")

In [4]: doc
Out[4]: Genes are cool.
```

Probably you have the wrong version of something installed. Please try again in a clean environment.

**Comment by danielkingai2** [comment]
I understand, those are the package versions in my environment as well. I am saying that you probably have some out of date/incompatible dependency in that environment. Please try again in a new, clean environment.

**Comment by Rashmikoparde** [comment]
> I understand, those are the package versions in my environment as well. I am saying that you probably have some out of date/incompatible dependency in that environment. Please try again in a new, clean environment.

Okay sure

**Comment by Rd0394** [comment]
Check if it helps. It's about loading bionlp package.

https://github.com/explosion/spaCy/discussions/7390

**Comment by Rashmikoparde** [comment]
Thank you!!! The issue is resolved. There was the problem of package version
