### ISSUE TITLE
Transfer learning of specialised NER model

### ISSUE THREAD

**Issue by nleguillarme** [allenai/scispacy#335]
Hi, I'd like to learn a specialised NER model on my own corpus starting from en_core_sci_md.

I'd like to try several things :

1. learn the NER component from scratch (so I would keep tok2vec, parser, tagger, attribute_ruler, lemmatizer, and create a new ner component)
1. keep the NER component in en_core_sci_md and resume training on my data

I have some python code to do 2. that I managed to adapt to spaCy v3, but I'd like to use the whole config file + command line way of doing things. Well, I'm having a hard time ^^"

I enclose my config file [base_ner.cfg.txt](https://github.com/allenai/scispacy/files/6129705/base_ner.cfg.txt) (inspired by your own base_ner.cfg) that I hope will let me do 1. (I have now idea how to resume training using config files at the moment), but that is returning errors when using spacy debug.

In particular, I don't understand why it asks for vectors, init_tok2vec, vocab_data, lookups in [initialize] since I want to reuse everything except the NER layer.

Thank you.

**Comment by danielkingai2** [comment]
I think its just because your initialize section asks for those things, have you tried just setting those things to null?
```
[initialize]
vectors = ${paths.vectors}
init_tok2vec = ${paths.init_tok2vec}
vocab_data = ${paths.vocab_path}
lookups = null
before_init = null
after_init = null
```

Also, this might end up being a better question for the spacy folks as there isn't much here that is specific to scispacy.

**Comment by nleguillarme** [comment]
Well if I remove all those things, I got the following error message
```
Config validation error

vocab_data     field required
lookups        field requiredthi
vectors        field required
init_tok2vec   field required
before_init    field required
after_init     field required
```

And if I set everything to null, I end up with :
```
TypeError: [E930] Received invalid get_examples callback in `Tok2Vec.initialize`. Expected function that returns an iterable of Example objects but got: []
```

I asked here because it has to do with transferring models and you did that at scispacy, but please tell me if you want me to close the issue and ask to spacy folks.

**Comment by nleguillarme** [comment]
Well, you were close ! It was not a path problem, as I set train/dev paths using command line arguments. But it made me notice that spacy convert completely messed up when I tried converting my data from the old JSON format to binary files... I tried again using a few lines of python and now spacy debug runs without throwing errors (apart from a few errors related to data themselves).

So I guess the pipeline could not init automatically because it was fed with empty data.

Thank you very much for your help. I don't have time to go any further in the training process right now, but I hope everything goes well from now on.

**Comment by danielkingai2** [comment]
Ah, makes sense! Glad I could help, I'll close this issue, hopefully the setup in the repo is helpful for you to train your own, feel free to open issues to ask questions about it, with the knowledge that I might have to defer to the spacy folks at some point :)
