### ISSUE TITLE
Spacy 3.0 - specify my own candidate generator to use custom UMLS path

### ISSUE THREAD

**Issue by phil-oxenberg** [allenai/scispacy#337]
I'm in the process of updating my python project from using Spacy 2 to use Spacy 3. My project uses my own versions of Scispacy candidate_generation.py and linking_utils.py in order to use a custom version of concept_aliases.json and other UMLS data files. How do I accomplish this in Spacy 3 (Scispacy 0.4.0)?

In V2, I simply made copies of candidate_generation.py and linking_utils.py which referenced local copies of the KB data files and instantiated my version of candidate_generation.py and passed the object to the EntitlyLinker constructor like so:
```
_candidate_generator = CandidateGenerator()
_el = EntityLinker(resolve_abbreviations=True, name="umls",
                                        candidate_generator=_candidate_generator)
```
My candidate_generation.py, in turn, references my linking_utils.py.

**Comment by danielkingai2** [comment]
A couple of questions:

1) What exactly have you tried/doesn't work? I would hope you can still do something similar, even though pipes are added by name now.
2) Is the only difference in your files that you point to custom data files? Or did you make other changes to?

**Comment by phil-oxenberg** [comment]
Yes, the only changes I made to candidate_generation.py and linking_utils.py was to replace the UmlsLinkerPaths and DEFAULT_UMLS_PATHs/DEFAULT_UMLS_TYPES_PATHs, respective;y, with local file references.  

In attempt to make it work (or get closer) I've tried mainly adjusting the config.  The following works (if I don't try to use my custom files):

```
    _nlp = spacy.load(_data_model)
    config = {"resolve_abbreviations": True,
              "linker_name": "umls"}

    _nlp.add_pipe("scispacy_linker", config=config)
    _nlp.add_pipe("abbreviation_detector")
```
I've tried variations on that configuration such as:
```
    config = {"resolve_abbreviations": True,
              "candidate_generator"=_candidate_generator
              "linker_name": "umls"}
```
That didn't work because the cg object wasn't serisalizable.  I've tried replacing the object instance with the name of the class "annotators.ScispacyAnnotator.candidate_generation.CandidateGenerator".  I've tried the following which also didn't work:
```
    config = {"resolve_abbreviations": True,
              "misc"={"misc": {"@architectures": "spacy.CandidateGenerator.v1"}}
              "linker_name": "umls"}
```

**Comment by danielkingai2** [comment]
There are a few options, but I think the simplest will be a minimal change to your previous setup. You should be able to modify the pipe after it has been added like so
```
In [5]: nlp.get_pipe('scispacy_linker')
Out[5]: <scispacy.linking.EntityLinker at 0x7f0c9a94e940>

In [6]: nlp.get_pipe('scispacy_linker').candidate_generator
Out[6]: <scispacy.candidate_generation.CandidateGenerator at 0x7f0c9a94e5b0>

In [7]: nlp.get_pipe('scispacy_linker').candidate_generator = lambda x: x

In [8]: nlp.get_pipe('scispacy_linker').candidate_generator
Out[8]: <function __main__.<lambda>(x)>
```

so you would do

```
nlp.get_pipe('scispacy_linker').candidate_generator = <your candidate generator>
nlp.get_pipe('scispacy_linker').kb = <your candidate generator>.kb
```

Alternatively, you could just fork the library and install scispacy from your fork, and then you can add whatever linker paths you want to the necessary objects.

**Comment by phil-oxenberg** [comment]
That's certainly straightforward, so this is what I did:
```
    _nlp = spacy.load(_data_model)
    _config = {"resolve_abbreviations": True,
              "linker_name": "umls"}

    _nlp.add_pipe("scispacy_linker", config=_config)
    _candidate_generator = CandidateGenerator()
    _entity_linker = _nlp.get_pipe('scispacy_linker')
    _entity_linker.candidate_generator = _candidate_generator
    
    response = self._nlp(document.normalized_text)
```
and that last line is executed I get this exception:

> [E109] Component scispacy_linker could not be run. Did you forget to call initialize()?

**Comment by danielkingai2** [comment]
I suspect that spacy error is swallowing whatever the actual error is. Can you try adding the second line from my example too?
`_entity_linker.kb = _candidate_generator.kb`

**Comment by phil-oxenberg** [comment]
Same error, even with that line included.

**Comment by danielkingai2** [comment]
Any chance its because `self._nlp` and `_nlp` are different in the code you pasted? I tried to simulate your setup, by loading the linker with umls first, and then substituting the mesh candidate generator. I get the same error as you (the full error actually shows that it is a key error resulting from a mismatched candidate generator and kb) without the kb line, but adding the kb line resolves it.

```
In [26]:     _nlp = spacy.load(_data_model)
    ...:     _config = {"resolve_abbreviations": True,       
    ...:               "linker_name": "umls"}                      
    ...:                                                      
    ...:     _nlp.add_pipe("scispacy_linker", config=_config)         
    ...:     _candidate_generator = CandidateGenerator(name="mesh")
    ...:     _entity_linker = _nlp.get_pipe('scispacy_linker')
    ...:     _entity_linker.candidate_generator = _candidate_generator
    ...:                                                                                                                                                                                                                                                           ...:     response = _nlp("This text has a disease.")
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/net/nfs2.corp/s2-research/daniel/miniconda3/envs/scispacy_3_new/lib/python3.8/site-packages/spacy/language.py in __call__(self, text, disable, component_cfg)
    988             try:
--> 989                 doc = proc(doc, **component_cfg.get(name, {}))
    990             except KeyError as e:

/net/nfs2.corp/s2-research/daniel/miniconda3/envs/scispacy_3_new/lib/python3.8/site-packages/scispacy/linking.py in __call__(self, doc)
    120                     self.filter_for_definitions
--> 121                     and self.kb.cui_to_entity[cand.concept_id].definition is None
    122                     and score < self.no_definition_threshold

KeyError: 'D000078623'

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-26-808026450e1f> in <module>
      8 _entity_linker.candidate_generator = _candidate_generator
      9 
---> 10 response = _nlp("This text has a disease.")

/net/nfs2.corp/s2-research/daniel/miniconda3/envs/scispacy_3_new/lib/python3.8/site-packages/spacy/language.py in __call__(self, text, disable, component_cfg)
    990             except KeyError as e:
    991                 # This typically happens if a component is not initialized
--> 992                 raise ValueError(Errors.E109.format(name=name)) from e
    993             except Exception as e:
    994                 error_handler(name, proc, [doc], e)

ValueError: [E109] Component 'scispacy_linker' could not be run. Did you forget to call `initialize()`?

In [27]:     _nlp = spacy.load(_data_model)
    ...:     _config = {"resolve_abbreviations": True,
    ...:               "linker_name": "umls"}
    ...: 
    ...:     _nlp.add_pipe("scispacy_linker", config=_config)
    ...:     _candidate_generator = CandidateGenerator(name="mesh")
    ...:     _entity_linker = _nlp.get_pipe('scispacy_linker')
    ...:     _entity_linker.candidate_generator = _candidate_generator
    ...:     _entity_linker.kb = _candidate_generator.kb
    ...: 
    ...:     response = _nlp("This text has a disease.")
In [28]: response.ents
Out[28]: (text, disease)

In [29]: response.ents[1]._.kb_ents
Out[29]: 
[('D004194', 1.0),
 ('D008575', 0.9078139662742615),
 ('D057973', 0.8003128170967102),
 ('D016538', 0.7885984182357788),
 ('D007644', 0.7878221273422241)]

**Comment by phil-oxenberg** [comment]
The line `response = self._nlp(document.normalized_text) ` is executed in a method that gets called by user action.  The other assignments are done at class init time.  Let me try your example.  Thanks.

**Comment by phil-oxenberg** [comment]
Daniel,  Thank you very much.  I finally got it working and determined that I had neglected to download a recent copy of concept_aliases.json and was using an older copy.
