### ISSUE TITLE
OSError at [E050] Can't find model 'en_core_sci_sm '. It doesn't seem to be a Python package or a valid path to a data directory.

### ISSUE THREAD

**Issue by phil-oxenberg** [allenai/scispacy#340]
This is somewhat related to issue# 337.

When I run my code in the debugger, everything works perfectly. When I use Jenkins to deploy/dockerize my application on an Ubuntu server, everything works perfectly. When I use Jenkins to deploy/dockerize my application on my Windows 10 laptop, everything was working perfectly until it wasn't.
The line spacy.load throws the exception:
```
_scispacy_data_model = "en_core_sci_sm"
_nlp = spacy.load(_scispacy_data_model)
```

Thoughts or suggestions?

**Comment by DeNeutoy** [comment]
@phil-oxenberg  are you installing the model package in your Dockerfile? You need both:

```
pip install scispacy
pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_sm-0.4.0.tar.gz
```
in there somewhere. If not, can you post the dockerfile?

**Comment by phil-oxenberg** [comment]
I'll post it shortly, but it has been working all day until it stopped working.

**Comment by phil-oxenberg** [comment]
FROM python:3.7.9 as base

FROM base as builder

# who maintains this file
MAINTAINER Philips CIEE Team

# set environment variable to log messages immediately
ENV PYTHONUNBUFFERED 1
# set environment variable to prevent Python from writing pyc files to disc (equivalent to python -B option)
ENV PYTHONDONTWRITEBYTECODE 1

# declare the ARG containing the spacy data model environment variable from compose file
ARG SPACY_DATA_MODEL_ARG
ENV SPACY_DATA_MODEL ${SPACY_DATA_MODEL_ARG}
RUN echo "The spacy data model will be: ${SPACY_DATA_MODEL}"
RUN echo "The spacy data model arg will be: ${SPACY_DATA_MODEL_ARG}"

ARG SCISPACY_DATA_MODEL_ARG
ENV SCISPACY_DATA_MODEL ${SCISPACY_DATA_MODEL_ARG}
RUN echo "The scispacy data model will be: ${SCISPACY_DATA_MODEL}"
RUN echo "The scispacy data model arg will be: ${SCISPACY_DATA_MODEL_ARG}"

# declare the ARG containing the doc server url environment variable from compose file
ARG DOC_SERVER_URL_ARG
ENV DOC_SERVER_URL ${DOC_SERVER_URL_ARG}
RUN echo "The doc server url will be: ${DOC_SERVER_URL}"

# declare the ARG containing the brat server url environment variable from compose file
ARG BRAT_SERVER_URL_ARG
ENV BRAT_SERVER_URL ${BRAT_SERVER_URL_ARG}
RUN echo "The brat server url will be: ${BRAT_SERVER_URL}"

RUN mkdir /install
WORKDIR /install

# copy requirements file to image
COPY ./requirements.txt /requirements.txt
COPY ./requirements-dev.txt /requirements-dev.txt

# run pip install on copied requirements file and create a folder in container to hold source code
ENV PATH="/install/bin:${PATH}"
RUN pip install --upgrade pip --prefix=/install -r /requirements.txt && mkdir /code

# we need updated version of this file
COPY ./ciee_restapi/rest_framework_swagger_index.html /install/lib/python3.7/site-packages/rest_framework_swagger/templates/rest_framework_swagger/index.html

# set working dir to that folder
WORKDIR /code

# copy or add content of current dir relevant folders to that folder
# Note:  includes tokenizers folder: tokenizers/punkt/PY3/english.pickle
COPY . /code/


FROM base
COPY --from=builder /install /usr/local
COPY --from=builder /code /code
WORKDIR /code

# declare the ARG containing the spacy data model environment variable from compose file
ARG SPACY_DATA_MODEL_ARG
ENV SPACY_DATA_MODEL ${SPACY_DATA_MODEL_ARG}
RUN echo "The spacy data model will be: ${SPACY_DATA_MODEL}"
RUN echo "The spacy data model arg will be: ${SPACY_DATA_MODEL_ARG}"

ARG SCISPACY_DATA_MODEL_ARG
ENV SCISPACY_DATA_MODEL ${SCISPACY_DATA_MODEL_ARG}
RUN echo "The scispacy data model will be: ${SCISPACY_DATA_MODEL}"
RUN echo "The scispacy data model arg will be: ${SCISPACY_DATA_MODEL_ARG}"

# declare the ARG containing the doc server url environment variable from compose file
ARG DOC_SERVER_URL_ARG
ENV DOC_SERVER_URL ${DOC_SERVER_URL_ARG}
RUN echo "The doc server url will be: ${DOC_SERVER_URL}"

# declare the ARG containing the brat server url environment variable from compose file
ARG BRAT_SERVER_URL_ARG
ENV BRAT_SERVER_URL ${BRAT_SERVER_URL_ARG}
RUN echo "The brat server url will be: ${BRAT_SERVER_URL}"

# run setup scripts (as root user)
RUN python ciee.py install -e

# reset working dir
WORKDIR /code

# create user and home dir
RUN useradd -m user && chmod 777 /home/user

# set current user to that
USER user

# RUN python -c "from nlp_engine.api import health_check; health_check()"

# python manage.py runserver 0.0.0.0:7000
# CMD ["python", "manage.py", "runserver", "0.0.0.0:7000"]
# CMD ["gunicorn", "PB_Django.wsgi:application", "--bind", "0.0.0.0:8000", "--timeout", "6000"]
CMD ["gunicorn", "PB_Django.wsgi:application", "--config", "docker/pb_django/gunicorn.conf", "--keep-alive", "600"]

**Comment by phil-oxenberg** [comment]
#requirements.txt
Django==3.1.7
djangorestframework==3.12.2
django-rest-swagger==2.2.0
intervaltree==3.0.2
nltk==3.5
requests==2.25.1
SQLAlchemy==1.3.16
pandas==1.2.3
spacy==3.0.5
psycopg2-binary==2.8.5
gunicorn==20.0.4
scispacy==0.4.0
sphinx
recommonmark
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz
en-core-web-lg @ https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.0.0/en_core_web_lg-3.0.0.tar.gz
en-core-web-trf @ https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.0.0/en_core_web_trf-3.0.0.tar.gz
en-core-sci-sm @ https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_sm-0.4.0.tar.gz
en-core-sci-md @ https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_md-0.4.0.tar.gz
en-core-sci-lg @ https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_lg-0.4.0.tar.gz
en-core-sci-scibert @ https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_scibert-0.4.0.tar.gz

**Comment by phil-oxenberg** [comment]
Perhaps it's a Docker Desktop issue?  I'm going to try the WSL 2 docker engine instead of hyper-v.

**Comment by phil-oxenberg** [comment]
Executing pip list from the container's command line shows:

> en-core-sci-lg                0.4.0
> en-core-sci-md                0.4.0
> en-core-sci-scibert           0.4.0
> en-core-sci-sm                0.4.0
> en-core-web-lg                3.0.0
> en-core-web-sm                3.0.0
> en-core-web-trf               3.0.0
> ...
> scispacy                      0.4.0
...
> spacy                         3.0.5

**Comment by phil-oxenberg** [comment]
My fix, even though its should be unnecessary, was essentially to not use a variable to hold the data model name passed to spacy.load()  Might this be a bug in spacy?

**Comment by danielkingai2** [comment]
ah! it looks like your env var has an extra space at the end :) 'en_core_sci_sm '

**Comment by phil-oxenberg** [comment]
Ha! Good catch.  Thanks for your help.

**Comment by danielkingai2** [comment]
Glad we got it working :)
