### ISSUE TITLE
Running scispacy in a locked-down container

### ISSUE THREAD

**Issue by mnhcorp** [allenai/scispacy#343]
Hi,

I'm trying to package and run scispacy on a container which may not have access to the network/Internet (passing --network=none to test).

It seems that even after downloading the cache files and seeding ~/.scispacy/datasets, it still attempts to pull the files (tfidf_vectors, etc) from S3 (and thus fails on a disconnected container). Is there a way to configure scispacy to use the locally cached files and _not_ download them on every initialization?

Thanks!

**Comment by DeNeutoy** [comment]
@mnhcorp you either need to replace these paths with local paths:

https://github.com/allenai/scispacy/blob/master/scispacy/candidate_generation.py#L43

or construct the entity linker manually, e.g first instantiating the CandidateGenerator with local paths, and passing that to the EntityLinker.

**Comment by mnhcorp** [comment]
@DeNeutoy Thanks, works perfectly!

FYI - I also had to change these paths along with the ones in candidate_generation.py:

https://github.com/allenai/scispacy/blob/4ade4ec897fa48c2ecf3187caa08a949920d126d/scispacy/linking_utils.py#L39-L40

**Comment by DSLituiev** [comment]
running into the same issue.
it would be great to have those paths cacheable in `~/.scispacy` w/o need to monkey patch
my initial guess was also that `file_cache.py` would check the `~/.scispacy` cache, but it is doing something different

**Comment by DSLituiev** [comment]
is there a reason to use hashed filenames? would you be open to a PR that rids of additional hash?

**Comment by dakinggg** [comment]
I think the file names do need to be hashed, because it is possible for the files to change, in which case the cache needs to be invalidated. I think the way to do this is for you to define your own `LocalLinkerPaths` and `LocalKnowledgeBase`, and then add those to `DEFAULT_PATHS` and `DEFAULT_KNOWLEDGE_BASES` respectively. Untested, but that is the cleanest way in my mind.
