### ISSUE TITLE
Installing older versions of scispacy and associated language models?

### ISSUE THREAD

**Issue by maxfarrell** [allenai/scispacy#349]
I'm interested in using scispacy with prodigy, which requires spaCy version 2.2. Is there a way to install older versions of scispacy and the assocaited language models that will be compatible?

**Comment by MichalMalyska** [comment]
Yeah, you can just specify the old S3 download paths, they still work. 

E.g. 

`pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.3.0/en_core_sci_lg-0.3.0.tar.gz` will get you the scispacy science large vocab for scispacy 0.3.0 which works with spacy 2.X versions

**Comment by maxfarrell** [comment]
Amazing! I think this model should work for my purposes, but is there a list of download paths somewhere in case I want to try other models?

**Comment by MichalMalyska** [comment]
The way I find them is to go to tagged release for 0.3.0 in this repo, and the old links are in the old readme. I am pretty sure they are identical as the new ones except you replace v0.4.0 with 0.3.0 everywhere.

**Comment by danielkingai2** [comment]
Yup! As @MichalMalyska says, you can either go to the tagged release you want and grab the link from the readme, or just replace the version in the url, they are the same other than that. The `0.3.0` models are compatible with spacy 2.3 and later. For 2.2.1 up to 2.3, you'll want `0.2.4`.
