### ISSUE TITLE
How can all the Entity linkers (RXNORM, UMLS, etc) be pre-installed in a Docker container

### ISSUE THREAD

**Issue by user8114** [allenai/scispacy#351]
To install a model I can do `RUN pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_md-0.4.0.tar.gz` inside of a `Dockerfile`

Can the files below be pre-installed in any manner (e.g. `wget http://XYZ -O ABC`)? I will have a runtime environment without access to downloading linkers at runtime. So it would be great to have all things in place in `Dockerfile` to execute something like `nlp.add_pipe("scispacy_linker", config={"resolve_abbreviations": True,
                                            "linker_name": "umls"})`

https://github.com/allenai/scispacy/blob/2290a80cfe0948e48d8ecfbd60064019d57a6874/scispacy/candidate_generation.py#L43-L49

i am attempting to avoid the following -
`https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/data/linkers/2020-10-09/umls/tfidf_vectors_sparse.npz not found in cache, downloading to /tmp/ `

**Comment by danielkingai2** [comment]
I think this is basically the same as #343. Does that work for you?

Also, if you have access to the internet, but just don't want to download the large files, you can just put a command in your dockerfile that triggers the download, and then copy the folder they get written to (/home/.scispacy/datasets) into your docker image.

**Comment by user8114** [comment]
@danielkingai2 , thank you for the feedback. This advice works for me!
