### ISSUE TITLE
The online demo and local results are different in Specialized NER

### ISSUE THREAD

**Issue by dgg32** [allenai/scispacy#354]
Hello. I have entered the following sentence:

"Endohydrolysis of (1→4)-β-D-linkages between D-galactose 4-sulfate and 3,6-anhydro-D-galactose in κ-carrageenans"

in the online demo and tried it on my local installation (both with "en_ner_bionlp13cg_md"). But the results are different for "κ-carrageenans". The online demo labels it as "simple chemical" (Figure 1), which is correct. But my local installation labels it as "GENE_OR_GENE_PRODUCT", which is not correct (Figure 2). Please help! Thank you.

<img width="1210" alt="Bildschirmfoto 2021-05-16 um 01 00 56" src="https://user-images.githubusercontent.com/1873196/118380486-5fd59000-b5e2-11eb-9f62-49f480245a91.png">
<img width="945" alt="Bildschirmfoto 2021-05-16 um 01 01 43" src="https://user-images.githubusercontent.com/1873196/118380489-65cb7100-b5e2-11eb-88c0-7f1d66d18262.png">

**Comment by MichalMalyska** [comment]
Hey @dgg32, this is the same issue as #342 - the demo is using spacy 2.0 compatible models it seems, which for some reason perform better

**Comment by danielkingai2** [comment]
Thanks @MichalMalyska, that is correct. I unfortunately have not had time to look into the possible performance degradation. Will close this issue as duplicate.
