### ISSUE TITLE
No module named 'scispacy.umls_utils

### ISSUE THREAD

**Issue by CamilleSchr** [allenai/scispacy#356]
Hello,
I have this error and I don't know why, can you help me please ? 
"ModuleNotFoundError: No module named 'scispacy.umls_utils'"
I download everything, and I have the umls_utils.py on scispacy
Thanks,
Cheers

**Comment by danielkingai2** [comment]
I will need some more information than that to help. How did you install scispacy? What code are you running that causes the error?
