### ISSUE TITLE
SciBERT

### ISSUE THREAD

**Issue by amirj** [allenai/scispacy#359]
May I ask you to provide more information about "en_core_sci_scibert" please?
According to the latest release note, it only supports parsing and POS tagging for now. When it will be available for NER and doc.vector, etc. Is there any branch or pre-release that I can follow?

**Comment by danielkingai2** [comment]
Scibert is used for parsing and tagging in those models, while ner is the same as the other `en_core_sci_` models. Sorry, but I cannot provide a timeline for any future improvements. We welcome contributions, and the whole training procedure is documented in `https://github.com/allenai/scispacy/blob/main/project.yml`, if you would like to do it yourself.
