### ISSUE TITLE
SciBERT not returning the proper entity label for NER

### ISSUE THREAD

**Issue by seangrant82** [allenai/scispacy#360]
When performing NER using the SciBERT model, it properly identifies entities but does not apply the proper label (CANCER, GENE, etc). All entities are marked as ENTITY

Example:
![image](https://user-images.githubusercontent.com/11846453/119068075-73ea0a80-b9b1-11eb-9ce6-09c351cd0726.png)

**Comment by danielkingai2** [comment]
The different NER models are listed here with their entity types (https://allenai.github.io/scispacy/). The base models do not categorize beyond "ENTITY". You'll have to pick which NER model has the entity types you are looking for.
