### ISSUE TITLE
How to define a custom knowledge base for Entity Linker ?

### ISSUE THREAD

**Issue by amirj** [allenai/scispacy#361]
I'm going to leverage an augmented version of UMLS (by adding new aliases from external sources to help the algorithm to match better). It seems that [candidate generation module](https://github.com/allenai/scispacy/blob/main/scispacy/candidate_generation.py) leverages a pre-indexed version of UMLS and [loads them from the cloud](https://github.com/allenai/scispacy/blob/2290a80cfe0948e48d8ecfbd60064019d57a6874/scispacy/candidate_generation.py#L43). May I ask you to help me to understand what's the best practice to load a custom version of UMLS or augment the current version with new aliases please?

**Comment by danielkingai2** [comment]
Hi, see if the response to this issue works for you: https://github.com/allenai/scispacy/issues/331#issuecomment-803291644
