### ISSUE TITLE
Explanation for the M parameter in CreateIndex in nmslib

### ISSUE THREAD

**Issue by MichalMalyska** [allenai/scispacy#366]
I was digging through code on creating the entity linker and found this TODO:

https://github.com/allenai/scispacy/blob/2290a80cfe0948e48d8ecfbd60064019d57a6874/scispacy/candidate_generation.py#L387

So i went on a deeper dive and found:

![M param explanation](https://user-images.githubusercontent.com/12971408/122602503-ee558b00-d040-11eb-9cb1-30d930c90521.png)

The M parameter seems to be the size of the neighbourhood in the underlying graph structure when creating the HNSW ( https://arxiv.org/ftp/arxiv/papers/1603/1603.09320.pdf) graph. 

My understanding is that putting this number higher increases the connectivity between clusters allowing for easier between-cluster jumping. 

The way they describe it in NMSLIB repo is:

"""
In what follows, we discuss HNSW-specific parameters. First, for HNSW, the parameter M defines the maximum number of neighbors in the zero and above-zero layers. However, the actual default maximum number of neighbors for the zero layer is 2*M. This behavior can be overriden by explicitly setting the maximum number of neighbors for the zero (maxM0) and above-zero layers (maxM). Note that the zero layer contains all the data points, but the number of points included in other layers is defined by the parameter mult (see the HNSW paper for details).
"""

**Comment by danielkingai2** [comment]
Cool, I would accept a PR renaming this param to something more meaningful and/or adding a comment explaining what it is, if you would like to submit one.

**Comment by MichalMalyska** [comment]
Done, let me know if I went a bit overboard.
