### ISSUE TITLE
 icd10 with CUI and TUI of an entity

### ISSUE THREAD

**Issue by Siddhijain16** [allenai/scispacy#371]
Hi,
Can we get icd10 value of an entity along with CUI ( Concept Unique Identifier) and TUI (semantic type )  ?
We are able to get CUI and TUI with the help of "[scispacy.linking](https://github.com/allenai/scispacy#example-usage-1) " but I need ICD10 also .
Is there any way to map CUI and TUI to get ICD10 ?
Please suggest how can I get ICD10 of an entity ...

**Comment by danielkingai2** [comment]
Sorry, I'm not sure where to find a mapping from CUI to ICD10. You would need to find some mapping from CUI to ICD10, we do not already have one in scispacy.

**Comment by Siddhijain16** [comment]
@danielkingai2  Thank you for your reply . 
Are you planning to add ICD10 with scispacy in future ?

**Comment by danielkingai2** [comment]
Sorry, currently have no plans to add ICD10, although if you do find a mapping between UMLS and ICD10, please let me know!
