### ISSUE TITLE
Getting zsh: illegal hardware instruction on MacBook M1

### ISSUE THREAD

**Issue by schittarath3** [allenai/scispacy#372]
I am attempting to run the [EntityLinking example](https://github.com/allenai/scispacy#example-usage-1), but importing the module
`from scispacy.linking import EntityLinker`
results in 
`zsh: illegal hardware instruction  /Users/username/opt/anaconda3/envs/HCNLP/bin/python`. 
I am able to run the first example to get the text entities fine.

OS: MacOS 11.4 on M1 MBP
Python: 3.7.10
conda: 4.10.1
scispacy: 0.4.0
spacy: 3.0.6

**Comment by danielkingai2** [comment]
This is probably related to the `nmslib` package. Can you check if you are able to install and use that package? Looks like the same issue as #365

**Comment by schittarath3** [comment]
> This is probably related to the `nmslib` package. Can you check if you are able to install and use that package? Looks like the same issue as #365

Thanks! For future reference, I uninstall nmslib then built from source using `pip install --no-binary :all: nmslib`

**Comment by jpetot** [comment]
this solved for me on MacOs M1 Monterey : `CFLAGS="-mavx -DWARN(a)=(a)" pip install nmslib`

https://github.com/nmslib/nmslib/issues/476#issuecomment-881044967

**Comment by aditya-kanekar** [comment]
Thanks @jpetot this worked for me.
