### ISSUE TITLE
Adding UmlsEntityLinker to model in spacy v3

### ISSUE THREAD

**Issue by farrandi** [allenai/scispacy#373]
This is the same issue I asked in [here](https://github.com/explosion/spaCy/discussions/8608) and they told me to ask here:
I am trying to add the UmlsEntityLinker to my trained model in spacy (I'm using jupyter notebook). Here is my code:
```
from scispacy.abbreviation import AbbreviationDetector
from scispacy.umls_linking import UmlsEntityLinker

entity_linker = UmlsEntityLinker(resolve_abbreviations=True)
```
However I seem to keep running and use a lot of memory...
Is this the right way to do this? or do I have to use `get_pipe` and `add_pipe` somewhere?

**Comment by danielkingai2** [comment]
what do you mean by "keep running", it does take a few minutes the first time because it needs to download a bunch of files. And here is the example of using the linker in the readme (https://github.com/allenai/scispacy#example-usage-1)

**Comment by farrandi** [comment]
Oh yea, turns out it was just downloading a bunch of files. I waited and everything worked. Thanks!
