### ISSUE TITLE
Multiple spacy model

### ISSUE THREAD

**Issue by Siddhijain16** [allenai/scispacy#374]
Hi @danielkingai2 ,

Can we load more than one model for example
model 1 ---> nlp = spacy.load("en_core_sci_md")
model 2 ---> med7 = spacy.load("en_core_med7_lg")
and so on..
then add them in a single pipeline .
As both model detect different entities and I want the results of both models in a single call .

Any help is really appreciated !!

**Comment by danielkingai2** [comment]
Hi, unfortunately I don't know of a way to do this naturally at the moment, here is a previous answer to this question (https://github.com/allenai/scispacy/issues/261#issuecomment-675167167)
