### ISSUE TITLE
Rename "filter for no defintions" to "prefer_entities_with_definitions"

### ISSUE THREAD

**Issue by MichalMalyska** [allenai/scispacy#376]
https://github.com/allenai/scispacy/blob/45e0ca1f5fad317f3daec8bb09377fa0f48d2485/scispacy/linking.py#L76

The name makes it seem like the entity linker will completely remove all entities without definitions, and you have to read the code to see how it works. This makes it more explicit

**Comment by danielkingai2** [comment]
It isn't really that either, it is just that filter for definitions requires the use of two parameters,`filter_for_no_definitions` and `no_definition_threshold`. I suppose we didn't really need both of these parameters, and could have just used `no_definition_threshold`, and have setting it to `None` mean "don't filter".

**Comment by MichalMalyska** [comment]
I can do that fix real quick

**Comment by danielkingai2** [comment]
I'm actually not sure I want to make this change since the benefit is pretty small, but it would a breaking change to the entity linker API. Let me think about it.

**Comment by danielkingai2** [comment]
I think I am not going to do this, I think the docs for the current params is good enough, and don't want to introduce a breaking change for this small of a reason. Thank you though!

**Comment by MichalMalyska** [comment]
My pleasure!
