### ISSUE TITLE
aws s3 downloading

### ISSUE THREAD

**Issue by Charles-Qiu** [allenai/scispacy#382]
**I am currently trying to train using my own corpus following the project.yml file.**
I try to download several files:
aws s3 cp s3://ai2-s2-scispacy/data/ud_ontonotes.tar.gz assets/ud_ontonotes.tar.gz
tar -xzvf assets/ud_ontonotes.tar.gz -C assets/
rm assets/ud_ontonotes.tar.gz
#############################################################
aws s3 cp s3://ai2-s2-scispacy/data/med_mentions.tar.gz assets/med_mentions.tar.gz
tar -xzvf assets/med_mentions.tar.gz -C assets/
rm assets/med_mentions.tar.gz
#############################################################
aws s3 cp s3://ai2-s2-scispacy/data/ner/ assets --recursive --exclude '*' --include '*.tsv'

But it  fails due to 
'''
**fatal error: Unable to locate credentials**
'''
I am wondering if anyone know how to solve this problem. Thanks!!!

**Comment by MichalMalyska** [comment]
This seems like a credentials issue in awscli:
https://aws.amazon.com/premiumsupport/knowledge-center/s3-locate-credentials-error/
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

**Comment by Charles-Qiu** [comment]
> This seems like a credentials issue in awscli:
> https://aws.amazon.com/premiumsupport/knowledge-center/s3-locate-credentials-error/
> https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

Have you ever succeeded in downloading these three files? I have already tried this method but it shows another fatal error.
'''
fatal error: An error occurred (403) when calling the HeadObject operation:
'''
Someone says that this is because it is not my bucket. I am not sure what does this mean and what to do next. I am totally new to the aws.

**Comment by danielkingai2** [comment]
Do you have this issue for all files (e.g. try just this one `s3://ai2-s2-scispacy/data/umls_semantic_type_tree.tsv`)? Unfortunately I cannot make the ontonotes file public due to licensing, but the others should be publicly readable. Let me know if they are not and I'll investigate which AWS permissions I may have set incorrectly. Thanks!

**Comment by MichalMalyska** [comment]
^ The umls type tree works for me, the onto notes doesn't with the same error. So I think this is the exact solution.

**Comment by Charles-Qiu** [comment]
> Do you have this issue for all files (e.g. try just this one `s3://ai2-s2-scispacy/data/umls_semantic_type_tree.tsv`)? Unfortunately I cannot make the ontonotes file public due to licensing, but the others should be publicly readable. Let me know if they are not and I'll investigate which AWS permissions I may have set incorrectly. Thanks!

This one works for me. I try again and now
'''
aws s3 cp s3://ai2-s2-scispacy/data/ud_ontonotes.tar.gz assets/ud_ontonotes.tar.gz
tar -xzvf assets/ud_ontonotes.tar.gz -C assets/
rm assets/ud_ontonotes.tar.gz
#############################################################
aws s3 cp s3://ai2-s2-scispacy/data/ner/ assets --recursive --exclude '*' --include '*.tsv'
'''
These two still doesn't work. The error information is in the following.
'''
$ aws s3 cp s3://ai2-s2-scispacy/data/ud_ontonotes.tar.gz assets/ud_ontonotes.tar.gz
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
$ aws s3 cp s3://ai2-s2-scispacy/data/ner/ assets --recursive --exclude '*' --include '*.tsv'
fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
'''
I am wondering what kind of licensing do I need? Is that UMLS Terminology Services (UTS) (Link: [https://uts.nlm.nih.gov/uts/])? I already have one for this.
If some of the files cannot be made public, can you show the details how to prepare it?(For example, the data format(one line of example), where to download the raw file, then how to convert the data into ud_ontonotes.tar.gz)
Thank you so much!!!

**Comment by danielkingai2** [comment]
Try the ner folder again?

The other one is ontonotes (https://catalog.ldc.upenn.edu/LDC2013T19), which is the corpus used to train the normal spacy models. It might not be necessary depending on what you are trying to do. We mix it in during training, but mainly use biomedical data.

**Comment by danielkingai2** [comment]
that is the original error. you need to set your aws credentials

**Comment by Charles-Qiu** [comment]
> that is the original error. you need to set your aws credentials

Again,
$ aws s3 cp s3://ai2-s2-scispacy/data/ner/ assets --recursive --exclude '*' --include '*.tsv'
fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

**Comment by danielkingai2** [comment]
Sorry, I'm having trouble getting the AWS permission right...I will try to figure this out, but you should definitely be able to download the individual files s3://ai2-s2-scispacy/data/ner/BC5CDR-IOB/devel.tsv

**Comment by Charles-Qiu** [comment]
> Sorry, I'm having trouble getting the AWS permission right...I will try to figure this out, but you should definitely be able to download the individual files s3://ai2-s2-scispacy/data/ner/BC5CDR-IOB/devel.tsv

Yes, I can download the individual one. But I cannot download s3://ai2-s2-scispacy/data/ner/. 
Or you can change the project.yml to include all the individual file links( if the number of files is not very large)
Thankyou

> Sorry, I'm having trouble getting the AWS permission right...I will try to figure this out, but you should definitely be able to download the individual files
> 
> * s3://ai2-s2-scispacy/data/ner/BC5CDR-IOB/devel.tsv
> * s3://ai2-s2-scispacy/data/ner/BC5CDR-IOB/test.tsv
> * s3://ai2-s2-scispacy/data/ner/BC5CDR-IOB/train.tsv
> * s3://ai2-s2-scispacy/data/ner/BioNLP13CG-IOB/devel.tsv
> * s3://ai2-s2-scispacy/data/ner/BioNLP13CG-IOB/test.tsv
> * s3://ai2-s2-scispacy/data/ner/BioNLP13CG-IOB/train.tsv
> * s3://ai2-s2-scispacy/data/ner/CRAFT-IOB/devel.tsv
> * s3://ai2-s2-scispacy/data/ner/CRAFT-IOB/test.tsv
> * s3://ai2-s2-scispacy/data/ner/CRAFT-IOB/train.tsv
> * s3://ai2-s2-scispacy/data/ner/JNLPBA-IOB/devel.tsv
> * s3://ai2-s2-scispacy/data/ner/JNLPBA-IOB/test.tsv
> * s3://ai2-s2-scispacy/data/ner/JNLPBA-IOB/train.tsv

Thank you so much! I can download the individual files!

**Comment by Charles-Qiu** [comment]
> Sorry, I'm having trouble getting the AWS permission right...I will try to figure this out, but you should definitely be able to download the individual files
> 
> * s3://ai2-s2-scispacy/data/ner/BC5CDR-IOB/devel.tsv
> * s3://ai2-s2-scispacy/data/ner/BC5CDR-IOB/test.tsv
> * s3://ai2-s2-scispacy/data/ner/BC5CDR-IOB/train.tsv
> * s3://ai2-s2-scispacy/data/ner/BioNLP13CG-IOB/devel.tsv
> * s3://ai2-s2-scispacy/data/ner/BioNLP13CG-IOB/test.tsv
> * s3://ai2-s2-scispacy/data/ner/BioNLP13CG-IOB/train.tsv
> * s3://ai2-s2-scispacy/data/ner/CRAFT-IOB/devel.tsv
> * s3://ai2-s2-scispacy/data/ner/CRAFT-IOB/test.tsv
> * s3://ai2-s2-scispacy/data/ner/CRAFT-IOB/train.tsv
> * s3://ai2-s2-scispacy/data/ner/JNLPBA-IOB/devel.tsv
> * s3://ai2-s2-scispacy/data/ner/JNLPBA-IOB/test.tsv
> * s3://ai2-s2-scispacy/data/ner/JNLPBA-IOB/train.tsv

Thank you so much! I can download these files!

**Comment by danielkingai2** [comment]
Ok, I think I got it right now, the original command should work

**Comment by Charles-Qiu** [comment]
> Ok, I think I got it right now, the original command should work

Yes, the original command works now.  
Also, I registered on https://catalog.ldc.upenn.edu/LDC2013T19 and try to download ud_ontonotes.tar.gz to make all things run.
Thanks for your patience and instruction!
