### ISSUE TITLE
kb_ents gives no results from custom KB

### ISSUE THREAD

**Issue by farrandi** [allenai/scispacy#384]
Following this discussion #383, where I got my custom KB to work.

I tried to test the code and for some reason it is not giving me anything.
Here is the code I tested it with:
```
linker = CandidateGenerator(name="myCustom")
text = "TR Max Velocity: 2.3 m/s"
doc = nlp(text)
spacy.displacy.render(doc, style = "ent", jupyter = True)

entity = doc.ents[2]
print("Name: ", entity)

for umls_ent in entity._.kb_ents:
    print(umls_ent)
    print(linker.kb.cui_to_entity[umls_ent[0]])
    print("----------------------")
```
This would give:
```
Name:  m/s
```
there was no `----------------------` which means it did not even enter the for loop.

I was wondering why this is the case.

If this helps, this is the jsonl file that I ran this script (https://github.com/allenai/scispacy/blob/master/scripts/create_linker.py) with:
```
...
{"concept_id": "U0013", "aliases": ["m/s"], "types": ["UN1T5"], "canonical_name": "m/s"}
...
```

**Comment by danielkingai2** [comment]
I'd have to dig into this a bit more to debug, but you might want to open your tfidf vectors file and make sure that m/s is actually present. i suspect it might not be because its a character trigram vectorizer, and probably normalize out the `/`. I'm not 100% sure of this, but the things to check are 1) `m/s` is recognized as an entity (which you did) 2) `m/s` is present in your kb (you did) 3) check the representation that the vectorizer produces if you just pass it that text (just load the vectorizer object separately and poke around)

**Comment by farrandi** [comment]
Hello Daniel, thanks for the reply. However, I am not sure how to load the vectorizer separately.
I tried doing this:
```
CustomLinkerPaths_mycustom = LinkerPaths(
    ann_index="",
    tfidf_vectorizer="output/tfidf_vectorizer.joblib",
    tfidf_vectors="",
    concept_aliases_list="",
)
class myKnowledgeBase(KnowledgeBase):
    def __init__(
        self,
        file_path: str = "custom_kb.jsonl",
    ):
        super().__init__(file_path)

DEFAULT_PATHS["myCustom"] = CustomLinkerPaths_mycustom
DEFAULT_KNOWLEDGE_BASES["myCustom"] = myKnowledgeBase

nlp.add_pipe("scispacy_linker", config={"resolve_abbreviations": True, "linker_name": "myCustom"})
linker = CandidateGenerator(name="myCustom")
```
but it gave me a `FileNotFoundError: file  not found` 

I also tried loading the joblib file but I am not sure where to go from here:
```
import joblib
joblib.load('output/tfidf_vectorizer.joblib')
#TfidfVectorizer(analyzer='char_wb', dtype=<class 'numpy.float32'>, min_df=10, ngram_range=(3, 3))
```

**Comment by farrandi** [comment]
I also tried the same script but with different units (without the "/") like: `kg`, `bpm`, `ml` and all of them gave the same results.
```
text = "TR Max Velocity: 2.3 kg"
doc = nlp(text)
spacy.displacy.render(doc, style = "ent", jupyter = True)

entity = doc.ents[2]
print("Name: ", entity)

for umls_ent in entity._.kb_ents:
    print("xx")
    print(umls_ent)
    print(linker.kb.cui_to_entity[umls_ent[0]])
    print("----------------------")
```
would give:
```
Name:  kg
```
so I am not sure if "/" is the problem.

**Comment by danielkingai2** [comment]
Can you 1) make sure that the linker is actually in your pipeline (`nlp.pipeline`) and 2) try changing the filtering, so set `filter_for_definitions=False` and `threshold=0.1`

**Comment by farrandi** [comment]
I did what you told me to:
```
nlp = spacy.load("new_model")
nlp.add_pipe("scispacy_linker", config={"resolve_abbreviations": True, "linker_name": "myCustom",
                                        "filter_for_definitions": False, "threshold": "0.1"})
linker = CandidateGenerator(name="myCustom")
print(nlp.pipe_names)
print(nlp.pipeline)
```
which returned:
```
['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'entity_ruler', 'ner', 'value_entity', 'scispacy_linker']
[('tok2vec', <spacy.pipeline.tok2vec.Tok2Vec object at 0x7f3fad155ef0>), ('tagger', <spacy.pipeline.tagger.Tagger object at 0x7f3fb0732220>), ('parser', <spacy.pipeline.dep_parser.DependencyParser object at 0x7f3fabf96d00>), ('attribute_ruler', <spacy.pipeline.attributeruler.AttributeRuler object at 0x7f3fb0fbb980>), ('entity_ruler', <spacy.pipeline.entityruler.EntityRuler object at 0x7f3fb46b9840>), ('ner', <spacy.pipeline.ner.EntityRecognizer object at 0x7f3fabf96520>), ('value_entity', <function value_entity at 0x7f3fb1121b80>), ('scispacy_linker', <scispacy.linking.EntityLinker object at 0x7f3fabefc430>)]
```
Showing that the linker is in my pipeline, then I ran the same sentence as above but I still got the same result.

**Comment by danielkingai2** [comment]
Ok, at this point I would suggest setting a breakpoint inside the entity linker and stepping through one line at a time until you can see why there are no entities returned. I'm not sure if it is because there is something wrong with your nmslib index, or some other issue

**Comment by farrandi** [comment]
From debugging I noticed that the difference with my knowledge base compared to the UMLS one from scispacy is that there are no `batch_neighbors` and `batch_distances` when it calls `candidate_generation.py` from `linking.py` at line 116:
```
 batch_candidates = self.candidate_generator(mention_strings, self.k)
```
Do you know why this is the case? is a possibility because my KB only has 25 entries (as I was just experimenting on how to use a custom KB in scispacy). Would this problem disappear with more entries in the KB. Another thing to note was it only took around 1s for me to run the script to make the ann_index and in the discussions it normally takes hours.

**Comment by MichalMalyska** [comment]
25 entries is very few entries, UMLS has ~4 Million as far as I remember

**Comment by farrandi** [comment]
Ah so most likely the problem lies there, alright then I'll try with a larger KB and update. 
But as far as the process to add the custom KB, is what I am doing correct?

**Comment by danielkingai2** [comment]
I'd be a bit surprised if the small number of entries was the problem, but I am not intimately familiar with nmslib. One thing to try is to load your nmslib index separately (https://github.com/allenai/scispacy/blob/3d153ddad1f11f000f961f7a92c0d862b93c0973/scispacy/candidate_generation.py#L116), and then see if you can play around with it following their docs (starting point here, https://nmslib.github.io/nmslib/api.html#nmslib-floatindex), and just make sure it ended up with the entries you expected and everything looks reasonable.

**Comment by farrandi** [comment]
I did some more digging and I am not sure if the problem is the ann_index from the function above.
I found out that the tfidf values from
https://github.com/allenai/scispacy/blob/3d153ddad1f11f000f961f7a92c0d862b93c0973/scispacy/candidate_generation.py#L324
give different results.

So here is the result from the normal UMLS KB:
![umls kb](https://user-images.githubusercontent.com/54917098/128267665-b054a198-9192-4b58-aef9-03562076b83a.png)
and here is the result of the custom KB:
![custom kb](https://user-images.githubusercontent.com/54917098/128267691-6f4b1eac-c96a-491b-8fdb-57b4928466e8.png)

This value affected the `batch_neighbors` and `batch_distances` when it was called in line 329:
```
batch_neighbors, batch_distances = self.nmslib_knn_with_zero_vectors(tfidfs, k)
```
Using the custom KB, https://github.com/allenai/scispacy/blob/3d153ddad1f11f000f961f7a92c0d862b93c0973/scispacy/candidate_generation.py#L251
would give the value of 1, so that made the if statement below True since `vectors` was `tfidf` that was passed to the function: ` self.nmslib_knn_with_zero_vectors(tfidfs, k)`
https://github.com/allenai/scispacy/blob/3d153ddad1f11f000f961f7a92c0d862b93c0973/scispacy/candidate_generation.py#L263-L264
and made them return empty arrays of neighbors and distance.

Is the vectorizer the problem then? or am I missing something?

**Comment by danielkingai2** [comment]
the vectorizer construction (https://github.com/allenai/scispacy/blob/3d153ddad1f11f000f961f7a92c0d862b93c0973/scispacy/candidate_generation.py#L415) has a `min_df` of 10, meaning that any ngram has to be in at least 10 docs to be included in the vectorizer. you can change this if you want to test on smaller data.

**Comment by farrandi** [comment]
Yep, that was the problem. What do you mean it has to be in at least 10 docs? when we run the script `create_liner.py`  we don't pass any text to it right?

**Comment by danielkingai2** [comment]
a "doc" here is a concept name. the tfidf vectorizer is fit on all the concept names in the kb using character trigrams. so any character trigrams that do not occur in at least 10 docs will not be included in the vectorizer. you can of course change this 10 to something lower if you want.
