### ISSUE TITLE
What does Doc.tensor contain for non-transformer models?

### ISSUE THREAD

**Issue by ldorigo** [allenai/scispacy#387]
Hi, we are processing large amounts of text and need to serialize Doc objects efficiently. We are using the `sci_md` model, and it appears that when converting a Doc to bytes, the majority of the space is taken by the `Doc.tensor` data. What does that data represent exactly? Is it static, and/or do I have to include it in each serialized Doc object?

**Comment by danielkingai2** [comment]
those vectors are static. the word vectors are word2vec trained on pubmed abstracts, and then spacy does the aggregation into the doc tensor (I think it is just an average, although not sure). I'm not sure how easy it would be to null those, it might be straightforward.

**Comment by ldorigo** [comment]
Are you sure you are talking about tensors (`token.tensor`) and not vectors (`token.vector`)?

Because if I do:

``` python
import spacy
nlp = spacy.load("en_core_sci_md")
sent_1 = nlp("I love potatoes")
sent_2 = nlp("I hate potatoes")

print(sent_1[1].tensor[:10])
print(sent_2[1].tensor[:10])
```

I get:

```
[ 0.9780569  -0.85239476  0.05534324 -0.536315   -0.7386089   1.3136992 0.15240714  0.11695394 -0.32724175 -0.28156167]
[ 0.7323813  -0.56237364  0.2564265  -0.5926044  -1.2961963   1.0635824 -0.33420312  1.120001   -0.43774125  0.18489192]
```
i.e. - two different tensors for the same word. Doing the same with `.vector` results in identical vectors, as expected.

According to this writeup: https://applied-language-technology.readthedocs.io/en/latest/notebooks/part_iii/04_embeddings_continued.html,  `.vector` should contain static information from word2vec embeddings, while `.tensor` contains context-dependent information that normally comes from transformers, but since there's no transformer in this model, I don't know what they represent?

**Comment by ldorigo** [comment]
( for reference, `nlp.pipeline` gives:

```
[('tok2vec', <spacy.pipeline.tok2vec.Tok2Vec at 0x7fe728e0fc20>),
 ('tagger', <spacy.pipeline.tagger.Tagger at 0x7fe843db99a0>),
 ('attribute_ruler', <spacy.pipeline.attributeruler.AttributeRuler at 0x7fe728d92f80>),
 ('lemmatizer', <spacy.lang.en.lemmatizer.EnglishLemmatizer at 0x7fe728dcb1c0>),
 ('parser', <spacy.pipeline.dep_parser.DependencyParser at 0x7fe729615940>),
 ('ner', <spacy.pipeline.ner.EntityRecognizer at 0x7fe729615be0>)]
```

So I'm positive that there's no transformers at work here)

**Comment by MichalMalyska** [comment]
> Are you sure you are talking about tensors (`token.tensor`) and not vectors (`token.vector`)?
> 
> Because if I do:
> 
> ```python
> import spacy
> nlp = spacy.load("en_core_sci_md")
> sent_1 = nlp("I love potatoes")
> sent_2 = nlp("I hate potatoes")
> 
> print(sent_1[1].tensor[:10])
> print(sent_2[1].tensor[:10])
> ```
> 
> I get:
> 
> ```
> [ 0.9780569  -0.85239476  0.05534324 -0.536315   -0.7386089   1.3136992 0.15240714  0.11695394 -0.32724175 -0.28156167]
> [ 0.7323813  -0.56237364  0.2564265  -0.5926044  -1.2961963   1.0635824 -0.33420312  1.120001   -0.43774125  0.18489192]
> ```
> 
> i.e. - two different tensors for the same word. Doing the same with `.vector` results in identical vectors, as expected.
> 
> According to this writeup: https://applied-language-technology.readthedocs.io/en/latest/notebooks/part_iii/04_embeddings_continued.html, `.vector` should contain static information from word2vec embeddings, while `.tensor` contains context-dependent information that normally comes from transformers, but since there's no transformer in this model, I don't know what they represent?

You are comparing tensors for "love" vs "hate", it's more weird that the vectors are the same. 

```import spacy
nlp = spacy.load("en_core_sci_md")
sent_1 = nlp("love")
sent_2 = nlp("hate") 
print(sent_1[0].vector[:10])
print(sent_2[0].vector[:10])
print(sent_1[0].tensor[:10])
print(sent_2[0].tensor[:10])
[-0.11821    -0.0708988  -0.30936    -0.105225    0.415823    0.00097378
  0.300131    0.00324844  0.207479    0.125942  ]
[-0.11821    -0.0708988  -0.30936    -0.105225    0.415823    0.00097378
  0.300131    0.00324844  0.207479    0.125942  ]
[ 1.8751609  -1.6736817  -0.29442406 -0.81565964 -0.00817816  0.06152236
  0.641755   -0.8051793  -1.1027172   0.06668803]
[ 1.3759801  -0.8531469   0.7494343  -0.7312323  -0.6730688  -0.34606454
  0.4301284   0.01695809 -1.0967836  -0.01745698]```

Having said that this is what I'm seeing:


```import spacy
nlp = spacy.load("en_core_sci_md")
sent_1 = nlp("I love potatoes")
sent_2 = nlp("I hate potatoes") 
print(sent_1[0].vector[:10])
print(sent_2[0].vector[:10])
print(sent_1[0].tensor[:10])
print(sent_2[0].tensor[:10])
[-0.00988646 -0.279009    0.083598    0.412393    0.233853    0.58461
  0.294148   -0.0245503  -0.0427367   0.144446  ]
[-0.00988646 -0.279009    0.083598    0.412393    0.233853    0.58461
  0.294148   -0.0245503  -0.0427367   0.144446  ]
[ 0.3273737  -0.04076735  0.1153962  -1.0918155   0.1258091  -0.8073256
  1.2124916   0.21230562 -0.7984005  -0.28116632]
[ 0.11558911  0.02216281  0.3639214  -1.09512    -0.05392472 -0.9066583
  1.360736    0.34528118 -0.72069037 -0.18247896]```

**Comment by danielkingai2** [comment]
Ah, sorry. Yes, I was talking about `token.vector`. I'm pretty sure the `Doc.tensor` comes from the `tok2vec` pipe. My guess is that you don't need to serialize the tensor (unless you want to use it for doc similarity or something), and can exclude it like so `doc.to_bytes(exclude=["text", "tensor"])`. That being said, there shouldn't be anything scispacy specific about this, so if you have more questions, it might be worth just asking on the spacy github directly.

**Comment by danielkingai2** [comment]
For reference: https://spacy.io/api/tok2vec

**Comment by ldorigo** [comment]
> You are comparing tensors for "love" vs "hate", it's more weird that the vectors are the same.

You're right, I messed up when copy-pasting my example - I wanted to show that the tensor tor "I" was different  in the two sentences - which is the case, as you point out. 

I will ask to spacy directly - thanks for your answers :-)

**Comment by danielkingai2** [comment]
Just to be clear, the "vectors" are word2vec vectors trained on pubmed abstracts

**Comment by ldorigo** [comment]
For reference, in case anyone wonders about this in the future, I asked to spacy as well and had some more details: https://github.com/explosion/spaCy/discussions/8898 

Closing this now, as I had my answer.
