### ISSUE TITLE
scispacy with spacy 3.1.1 and prodigy 1.11

### ISSUE THREAD

**Issue by maxfarrell** [allenai/scispacy#391]
I'm trying to use scispacy with the newly release prodigy (1.11.2) but there seems to be a conflict between the required spacy versions. scispacy uses spacy 3.0.7, but prodigy requires spacy<3.2.0, >=3.1.1

Is there some way that I can use scispacy with a newer version or spacy, or should I wait for an update from the scispacy team?

**Comment by danielkingai2** [comment]
I haven't had time to upgrade to 3.1.x yet, but you can probably just install that version of spacy yourself after installing scispacy, given https://spacy.io/usage/v3-1#upgrading

**Comment by MattBrauer** [comment]
The libraries still work, but with a warning:

`/opt/anaconda3/envs/prodigy/lib/python3.8/site-packages/spacy/util.py:732: UserWarning: [W095] Model 'en_ner_jnlpba_md' (0.4.0) was trained with spaCy v3.0 and may not be 100% compatible with the current version (3.1.2). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate`

**Comment by sudarshan85** [comment]
Hi,

I'm sort in the same boat. I'll be asking our support staff to ingress new versions of Prodigy, spacy and scispacy. But I want to make sure they are the _latest compatible_ versions. Currently, if I just install spacy, I get version 3.2.1. But as soon as I "install" one of the scispacy models, spacy version goes to 3.0.7. Prodigy latest version is 1.11.7 which has support for Spacy 3.2. 

Whats the best version of all that works without any conflicts? Or is it OK to use all the latest version and ignore the upgrade warning?

**Comment by dakinggg** [comment]
As far as I know it should be fine to use with the warning, but I haven't tried it to check for possible performance degradation

**Comment by dakinggg** [comment]
The upgrade to the latest spacy is done, except that I am having some issues with pypi. You can use master if you need the upgrade now.

**Comment by baxtree** [comment]
Hi, there. Given scispacy v0.5.0 and v0.4.0 support spacy 3.2 and 3.0 respectively, am I right in thinking there is seemingly no official support on spacy 3.1? Could anyone confirm which version is more compatible with spacy 3.1 and whether the aforementioned UserWarning on incompatibility can be ignored safely?
