### ISSUE TITLE
computing resources and models in output/

### ISSUE THREAD

**Issue by CharlesQ9** [allenai/scispacy#395]
I try to train en_core_sci_scibert_parser_tagger following the project.yml
spacy train configs/base_parser_tagger_scibert.cfg --output output/en_core_sci_scibert_parser_tagger --code scispacy/base_project_code.py --paths.vocab_path project_data/vocab_lg.jsonl --gpu-id 0

Then I met:
✔ Initialized pipeline
============================= Training pipeline =============================
ℹ Pipeline: ['transformer', 'tagger', 'attribute_ruler', 'lemmatizer',
'parser']
ℹ Frozen components: ['attribute_ruler', 'lemmatizer']
ℹ Initial learn rate: 5e-05
E    #       LOSS TRANS...  LOSS TAGGER  LOSS PARSER  TAG_ACC  LEMMA_ACC  DEP_UAS  DEP_LAS  SENTS_F  SCORE 
---  ------  -------------  -----------  -----------  -------  ---------  -------  -------  -------  ------
  0       0           0.00      4175.17      8352.18    71.48       0.00    24.43     6.92     0.00    0.17
Epoch 1:  15%|████████████████▍                                                                                            | 347/2300 [08:11<51:33,  1.58s/it]⚠ Aborting and saving the final best model. Encountered exception:
RuntimeError('CUDA out of memory. Tried to allocate 268.00 MiB (GPU 0; 31.75 GiB total capacity; 29.89 GiB already allocated; 11.50 MiB free; 30.27 GiB reserved in total by PyTorch)')

I am wondering how large memory do you  usuallly use for training, so that I can try to apply for that in my college.

Furthermore, I would appreciate it very much if you could share(if possible) part of the saved models like output/en_core_sci_scibert_parser_tagger somewhere so that it will be very convenient for more people to customize their training based on your previous results. Currently I only customize the training for "name: ner-train-scibert", so for the previous steps I can skip them if I have access to "output/en_core_sci_scibert_parser_tagger/model-best" and just download and put the model in the assigned path.
Thank you so much!

**Comment by dakinggg** [comment]
that command you ran has a gpu id because someone else trained that model not me, but they probably trained it on a gpu with 48gb of memory. you should be able to reduce memory usage by reducing the batch size in the config file.

**Comment by CharlesQ9** [comment]
Thank you! Solved!
