### ISSUE TITLE
Can't find factory for 'scispacy_linker' for language English

### ISSUE THREAD

**Issue by zhanyuanucb** [allenai/scispacy#405]
**Describe the bug**
`ValueError: [E002] Can't find factory for 'scispacy_linker' for language English` occurs if one doesn't import `scispacy.linking`

**To Reproduce**
```
import spacy

lang_model = "en_core_sci_sm"
nlp = spacy.load(lang_model)
nlp.add_pipe("scispacy_linker",
             config={"resolve_abbreviations": True,
                     "linker_name": "umls"})
```

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Version:
```
>>> scispacy.__version__
'0.4.0'
>>> spacy.__version__
'3.0.7'
```
 - Python: `python3.6`

**Comment by dakinggg** [comment]
This is the expected behavior.
