### ISSUE TITLE
How to solve duplicate abbreviation situation 

### ISSUE THREAD

**Issue by ksj20** [allenai/scispacy#410]
Hi,

First of all, thanks for developing the package and the wonderful features.

I wanted to ask about how you would solve the problem of duplicate abbreviations.

This happens in bio field, although an example that I can think of is
``` Mindful memoization (MM) ```

In this case, the abbreviationDetector would trace this as
``` memoization (long form): MM (short form) ```
instead of "mindful memoization" as the long form.

AFAIK, this is because the detector detects purely the short form letters' occurence.

Are there any endeavors to tackle this?

**Comment by dakinggg** [comment]
Yeah, this is a limitation of the abbreviation algorithm, sorry about that. I suspect there is not a simple fix for this. Depending on your use case and tradeoffs, you could try to patch this yourself by looking one word back from the abbreviation returned and seeing if it starts with the first letter of the short form, or something like that.
