### ISSUE TITLE
Re: error using the static vectors in Entity Linking example

### ISSUE THREAD

**Issue by BengWord2Vec** [allenai/scispacy#413]
RuntimeError: [E896] There was an error using the static vectors. Ensure that the vectors of the vocab are properly initialized, or set 'include_static_vectors' to False.

ANy idea how to solve this issue?

**Comment by davidshumway** [comment]
If running on Google Colab, see this comment: https://github.com/allenai/scispacy/issues/328#issuecomment-791043751.

This error appears in Colab due to preinstalled libraries. At present, updating the `blis` library appears to solve the problem, e.g., `!pip install -U blis`.
