### ISSUE TITLE
How would someone replicate scispacy vectors?

### ISSUE THREAD

**Issue by azhx** [allenai/scispacy#416]
https://github.com/allenai/scispacy/blob/main/docs/index.md
Talks about the datasources used but im not entirely clear on how exactly the vector tables were trained for, say, en_core_sci_md vs en_core_sci_lg. 

I didn't seem to find anything in the original scispacy paper either.
What specific algorithms/libraries were used, etc?

**Comment by dakinggg** [comment]
Please see https://github.com/allenai/scispacy/issues/83
