### ISSUE TITLE
Support for Python 3.9 and Spacy 3.2.2

### ISSUE THREAD

**Issue by avoutsas67** [allenai/scispacy#417]
Dear all, 

When installing scispacy in python 3.9 and using spacy 3.2.2 I get the following error 

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
black 22.1.0 requires click>=8.0.0, but you have click 7.1.2 which is incompatible.

Can you please provide an update on your plans to support python 3.9 and spacy 3.2.2? 

Thanks

Achilleas Voutsas

**Comment by dakinggg** [comment]
What installation process led you to this error? scispacy should be compatible with spacy 3.2.2 even though the released package says it is not. If I install scispacy and then spacy==3.2.2, I get a different error, but the error does not block the installation and everything still seems to work.

```ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scispacy 0.4.0 requires spacy<3.1.0,>=3.0.0, but you have spacy 3.2.2 which is incompatible.
Successfully installed langcodes-3.3.0 spacy-3.2.2 spacy-loggers-1.0.1```

As for "official" support, I do not know if or when scispacy will be officially updated to use spacy 3.2.2.

**Comment by avoutsas67** [comment]
Thanks for the response, I get the error when I try to load spacy, spacy-transformers and then scispacy. 

Achilleas

**Comment by dakinggg** [comment]
Can you share the exact commands that produce the error? But also, the libraries probably still work even though you got the error.

**Comment by avoutsas67** [comment]
I am running the following commands in macOS v12.2.1 and python 3.9.10
```
python
Python 3.9.10 (main, Jan 15 2022, 11:48:04) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin

```

```
python -m pip install --upgrade pip
pip install spacy
pip install spacy-transformers
pip install scispacy
```

When executing 
`pip install scispacy ` I get the following error:
```
Installing collected packages: threadpoolctl, scipy, pysbd, pybind11, psutil, conllu, click, typer, scikit-learn, nmslib, spacy, scispacy
  Attempting uninstall: click
    Found existing installation: click 8.0.4
    Uninstalling click-8.0.4:
      Successfully uninstalled click-8.0.4
  Attempting uninstall: typer
    Found existing installation: typer 0.4.0
    Uninstalling typer-0.4.0:
      Successfully uninstalled typer-0.4.0
  Attempting uninstall: spacy
    Found existing installation: spacy 3.2.2
    Uninstalling spacy-3.2.2:
      Successfully uninstalled spacy-3.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spacy-transformers 1.1.4 requires spacy<4.0.0,>=3.1.3, but you have spacy 3.0.7 which is incompatible.
Successfully installed click-7.1.2 conllu-4.4.1 nmslib-2.1.1 psutil-5.9.0 pybind11-2.6.1 pysbd-0.3.4 scikit-learn-1.0.2 scipy-1.8.0 scispacy-0.4.0 spacy-3.0.7 threadpoolctl-3.1.0 typer-0.3.2

```

Following your advice I run successfully the SciSpacy example provided at https://allenai.github.io/scispacy/

Thanks

Achilleas

**Comment by dakinggg** [comment]
Great!
