### ISSUE TITLE
Replacing Abbreviations with the long form

### ISSUE THREAD

**Issue by nermeetadhillon** [allenai/scispacy#418]
Hi I am trying to go through my tokens and replace abbreviations like cvd, with cardiovascular disease, etc. However whenever I go to replace my tokens I get the following error
 'spacy.tokens.doc.Doc' object has no attribute 'append'
or 
 'spacy.tokens.doc.Doc' object has no attribute 'replace'

**Comment by dakinggg** [comment]
spacy Docs are not really editable. I think the simplest way is to convert to string, replace the part of the string you want to, and then reprocess to a spacy doc.
