### ISSUE TITLE
AWS permissions

### ISSUE THREAD

**Issue by mprorock** [allenai/scispacy#419]
As noted in #382 and #386 permissions appear a bit wonky here - getting a request for creds on `med_mentions.tar.gz` which is fine since that can be sourced directly from the [source](https://github.com/chanzuckerberg/MedMentions) but the final download command is also bombing on credentials `aws s3 cp ${vars.ner_loc_s3} assets --recursive --exclude '*' --include '*.tsv'`

**Comment by mprorock** [comment]
fix is to adjust that final line to include `--no-sign-request` - ill issue a PR if i get a chance.

**Comment by dakinggg** [comment]
Ahh yes, good catch. I'll leave this open so others can find it. Feel free to issue a pr, I'll accept it.

**Comment by mprorock** [comment]
> Ahh yes, good catch. I'll leave this open so others can find it. Feel free to issue a pr, I'll accept it.

PR #420
