### ISSUE TITLE
Compatibility with Apple Silicon

### ISSUE THREAD

**Issue by ghostintheshellarise** [allenai/scispacy#424]
While Spacy v3.2 is made native in Apple Silicon, scispacy requires Spacy v3.0 which is not optimised.   

Is there any plan to upgrade Scispacy to make it compatible with Spacy v3.2?

**Comment by dakinggg** [comment]
hopefully pretty soon, am training the new models right now, hopefully that goes smoothly. Neither I nor the other co creator work on this right now, so maintenance is slow.

**Comment by dakinggg** [comment]
This is done, except that I am having some issues with pypi, you can use master if you need the upgrade now.
