### ISSUE TITLE
Installation issue with Python 3.9

### ISSUE THREAD

**Issue by smakurugoda** [allenai/scispacy#432]
There seems to be an issue with the installation of scispacy on Python 3.9. The following error gets thrown during the installation process. 

> command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

I was able to install on Python 3.6 without any issues.

**Comment by dakinggg** [comment]
Please show the whole error and what command you ran.
