### ISSUE TITLE
MeSH + OMIM entity linkers for a single piece of text at a time

### ISSUE THREAD

**Issue by srishti-git1110** [allenai/scispacy#433]
Hi, 
First of all, thankyou very much for all the hard work you've put in to make SciSpacy for us.
I need some help with NEL; it's my first time using scispacy.

I'm quite new to this, but what I know from my research is that the MeSH system doesn't have genetic diseases. That’s why any “complete” disease ontology that uses MeSH will also use OMIM.
My question is: Is there any way to do this with scispacy? Like any way to use both systems for a piece of text so that what MeSH misses OMIM covers.

They also have this thing in the NCBI dataset (disease annotated dataset), so for diseases that do not have any id in MeSH they have used the OMIM system for it.  (see the image attached)

![Screenshot (75)](https://user-images.githubusercontent.com/84127491/166462649-9bbd3ab6-bd3e-46a9-b7b2-a7f7dcd6b668.png)

Thanks for your time reading this. Any help is appreciated! :)

**Comment by dakinggg** [comment]
Hi, we don't have support for the OMIM ontology at this point. It should be possible to add your entity linker if you have access to the ontology though. See https://github.com/allenai/scispacy/issues/331#issuecomment-803291644 for more information.
