### ISSUE TITLE
Spacy >=3.3.0 

### ISSUE THREAD

**Issue by mpetruc** [allenai/scispacy#434]
Hi, was wondering if there is a timeline for supporting Spacy >=3.3.0? What pitfalls should i expect if i tried to manually modify the requirements to allow it?
thank you.

**Comment by dakinggg** [comment]
There is no timeline, but it looks like it doesn't necessarily require retraining the models, so it might just work if you change the requirements or force install it.

**Comment by qhreul** [comment]
Not sure whether it would have an impact, but Spacy >=3.3 has looser dependencies on `typing-extensions`. 
`typing_extensions>=3.7.4.1,<4.2.0; python_version < "3.8"`
The current restriction in Spacy == 2.2.x makes it difficult to compile with recently updated libraries.

**Comment by dakinggg** [comment]
Ok, I will try to release an updated version soon. I was trying to add something new with the next release but haven't really had time. Just doing the upgrade should be straightforward.

**Comment by dakinggg** [comment]
@qhreul @mpetruc @davidefiocco I just release scispacy 0.5.1, which is compatible with spacy 3.4.x
