### ISSUE TITLE
Drug name entity recognition

### ISSUE THREAD

**Issue by Frank-LIU-520** [allenai/scispacy#444]
any other model fro drug name entity recognition. I found that both BC5CDR model ande med7 model are not that accurate for drug name recognition.

**Comment by dakinggg** [comment]
Sorry, no. If you have another dataset you would like to have an NER model for, it would be very easy to train one though! Have a look at https://github.com/allenai/scispacy/blob/57fe1b3a8af3215934f831d69610ffc1805f2379/project.yml#L360. Feel free to open a new issue if you have a particular dataset in mind.
