### ISSUE TITLE
Unable to install scispacy on windows using pip

### ISSUE THREAD

**Issue by Cbezz** [allenai/scispacy#445]
Hey, sorry to bother you.

I keep getting an error when I try to download scispacy on windows 10, python 3.10.0 using pip.
I've tried a couple of different pip versions but they haven't worked.
The error spits out pages and pages of error messages but it says the error was encountered while trying to install nmslib (version 1.7.3.6)
It also mentions Microsoft Visual Studio.

I've spent a large portion of my day today trying to figure out a solution, including trying to pip install other versions of nmslib (1.8 and 2.1.1). But nothing I've tried has succeeded.

I'm wondering if this has happened to others and also obviously if there is a fix haha

It's a shame I was looking forward to using the library
Thanks for any help!

EDIT:
Should mention that I've read this thread:
https://github.com/allenai/scispacy/issues/137

And this thread on nmslib's github:
https://github.com/nmslib/nmslib/issues/508

Hope that helps

**Comment by dakinggg** [comment]
Hey, this is all about installing nmslib. So if you can figure out a way to install nmslib on your setup, scispacy should work. But I'm going to close this in favor of the issue on nmslib. Thanks! Feel free to reopen if you discover something specific to scispacy or have other questions.

**Comment by dakinggg** [comment]
It looks like it might work if you use an older python version though.
