### ISSUE TITLE
Error thrown out at LINE:  from scispacy.linking import EntityLinker

### ISSUE THREAD

**Issue by rjiang9** [allenai/scispacy#446]
I am trying out scispacy on Mac M1:

1) conda env with python=3.8 OK
2) pip install scispacy OK
3) pip install the models OK
4) run sample code in section AbbreviationDetector OK

But when I run sample code in section EntityLinker, error thrown out:

`zsh: illegal hardware instruction`

and it looks the error is from line:
`from scispacy.linking import EntityLinker`

Any suggestion is appreciated. 

RJ

<img width="400" alt="image" src="https://user-images.githubusercontent.com/7293118/184972016-7d2b09d5-32bd-4b4f-af99-abf28127ded1.png">

**Comment by dakinggg** [comment]
This is likely to be an issue with nmslib (see https://github.com/nmslib/nmslib/issues/476 for example). Could you see if anything over there works for you?

To verify if it is nmslib, it would also be great if you could try out some example.code from nmslib and see if that works.

Unfortunately I don't have an M1, so I can't really test anything myself.

**Comment by rjiang9** [comment]
Thank you Daniel @dakinggg 

It looks the solution from this thread works for me: 

[https://github.com/allenai/scispacy/issues/372](url)

`pip install --no-binary :all: nmslib`

**Comment by dakinggg** [comment]
Great!
