### ISSUE TITLE
Update UMLS to latest release

### ISSUE THREAD

**Issue by rxk2rxk** [allenai/scispacy#460]
Hi,

I'm parsing text from clinicaltrials.gov (Trial ID NCT04837209) using scispaCy plus language model 'en_core_sci_md' and seeing 'Dostarlimab' being linked to UMLS concept C1621793 which is a bird (a Starling).

It looks like this is the result of fuzzy matching - both words have a substring ('starlit') in common - as evident by the low match probability (0.5594).

However, the biologic drug Dostarlimab is in the latest UMLS release (2022AB) as the concept C5242455. Is scispaCy linking to an older version of UMLS?

Thanks,
Ron

**Comment by dakinggg** [comment]
Hi, yes. I believe scisoacy is still using the 2020 release of UMLS. Unfortunately I no longer have access to UMLS, so I can't actually update it. That being said, if you do have access, the script to generate the artifacts used for entity linking is here:

**Comment by rxk2rxk** [comment]
Hi Daniel,Thanks for getting back to me quickly! You should be able to access the latest UMLS release (2022AB) as it doesn’t require user registration anymore:UMLS Knowledge Sources: File Downloadsnlm.nih.govIt would be good to subset the Metathesaurus (i.e., a few key taxonomies in English) as the current Python package makes unnecessary demands on memory.Best,RonOn Dec 28, 2022, at 7:35 PM, Daniel King ***@***.***> wrote:﻿
Hi, yes. I believe scisoacy is still using the 2020 release of UMLS. Unfortunately I no longer have access to UMLS, so I can't actually update it. That being said, if you do have access, the script to generate the artifacts used for entity linking is here:

**Comment by dakinggg** [comment]
Ah I didn't know it no longer required registration! I'm not sure if/when I would get to updating to the latest UMLS, but I appreciate the info! As for subsets, we do have a few subsets available. See here in the readme: https://github.com/allenai/scispacy#entitylinker

**Comment by rxk2rxk** [comment]
﻿Thanks, please update me know if/when you get to updating the UMLS database used by SciSpaCy. Let me know if you need help with this.

Re: subsetting, it would be helpful to be able to further subset the UMLS subset on the fly (during load) to exclude certain sources (e.g., NCBI).

**Comment by rahulmohan** [comment]
@rxk2rxk I am also looking to update the UMLS NER models to use the latest data. Just checking if you made progress with this yet?

**Comment by rxk2rxk** [comment]
Hi @rahulmohan I haven't tried yet as I'm maxed out at work. I'll update the issue if make progress on this.

**Comment by nanthony007** [comment]
I'd be willing to do this and submit a PR for it. Not sure if it as simple as running `scripts/create_linker.py` on the MRCONSO.rff file or if I'd need to download the entire UMLS and run `scripts/export_umls_json.py`. Also not sure if I could include the data for those files in the PR due to size or if I'd need to retrain and publish the models themselves which I am sure I don't have permissions for...

I think going forward making this process as simple as possible should be a requirement so no matter your load users can easily update the primary (UMLS) knowledge base to keep it up to date.

The first paragraph here raises a general question I had, is the UMLS data used only for the NER or is it a larger part of the model?  I.e. if I created my own EntityLinker using 2022AB UMLS, would that solve this "outdated" issue?

**Comment by rxk2rxk** [comment]
I was able to (partially) build the UMLS knowledge base and linker on my Mac by running the following commands:

cd ~/Documents/GitHub/scispacy
mkdir output
cd scripts 
python3 export_umls_json.py --meta_path ~/Documents/Taxonomy/UMLS/2022AB/META --output_path ../output/umls_kb.jsonl
python3 create_linker.py --kb_path ../output/umls_kb.jsonl --output_path ../output/

The export script successfully crested the KB (in JSONL format) but the linker script, which takes a very long time (> 2 hours), was killed by the OS halfway through due to excessive memory pressure.

**Comment by dakinggg** [comment]
@nanthony007 Yes, if you create your own `EntityLinker` using your own set of paths (e.g. https://github.com/allenai/scispacy/blob/4f9ba0931d216ddfb9a8f01334d76cfb662738ae/scispacy/candidate_generation.py#L43-L48), it should work.

@rxk2rxk Let me try running those scripts on my machine...I do recall them being pretty resource intensive 😅

**Comment by dakinggg** [comment]
It looks to me that UMLS does still require registration to download the full subset. In scispacy we use sections 0, 1, 2, and 9.

**Comment by dakinggg** [comment]
Ok I have the latest umls files, will try to get the new linkers done soon.

**Comment by dakinggg** [comment]
Local files should work natively with `file_cache.py`, because of the else there
```
    elif os.path.exists(url_or_filename):
        # File, and it exists.
        return url_or_filename
```

**Comment by rxk2rxk** [comment]
Thanks Daniel! I got past this issue by dropping off the "file:///" prefix from the URLs (not obvious immediately).

**Comment by dakinggg** [comment]
This is now done in the latest release :)
