### ISSUE TITLE
Degradation in en-core-sci-scibert model performance 

### ISSUE THREAD

**Issue by aryehgigi** [allenai/scispacy#465]
Hey @dakinggg 
I am working on SPIKE in the AI2-israel team, where we use scispacy's Models
We have seen some degradation in the performance of the en-core-sci-scibert model from version 0.4.0 to 0.5.1 (esp. around PP-attachment, conjunction attachments, and noun/adjective mixups)
1. Do you know anything about this?
2. Would it be possible to send us the data you trained on so we can try and retain (at least so we have something until a fix will be released)?
3. Lmk if you want me to attach examples and done stats

Btw are you the maintainer of this repo? 
Lmk if you want to discuss it offline aryeht@allenai.org

Thanks a lot

**Comment by dakinggg** [comment]
Responded via email
