### ISSUE TITLE
How to extract all species names in a document?

### ISSUE THREAD

**Issue by bpersevere** [allenai/scispacy#468]
Can we use scispaCy to extract all species names in a document? The species name here refers to the scientific name of the species, also known as binomal names or Linnean names. For example, Ganoderma lucidum.

**Comment by nleguillarme** [comment]
Okay, this is self-promotion, but you can look at [TaxoNERD](https://github.com/nleguillarme/taxonerd) which relies heavily on scispacy and is specifically designed to extract taxonomic entities.

**Comment by bpersevere** [comment]
Thank you very much for your help.

**Comment by andyjessen** [comment]
Great work @nleguillarme!

**Comment by dakinggg** [comment]
Thanks for sharing @nleguillarme!
