### ISSUE TITLE
Add support for spaCy 3.5.x

### ISSUE THREAD

**Issue by de-code** [allenai/scispacy#486]
Currently the constraints of scispacy require spaCy < 3.5.0.
Version 3.5.0 was release 20 Jan 2023.
It would be nice to support that version.

**Comment by dakinggg** [comment]
Thanks! I will try to get to this soon.

**Comment by fehbari** [comment]
Any updates on this? spaCy is currently on `3.6.1`, but scispaCy still has a hard requirement on `< 3.5.0`.

```
Because en-core-sci-sm (0.5.1) @ https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.1/en_core_sci_sm-0.5.1.tar.gz depends on spacy (>=3.4.1,<3.5.0)
 and my-project depends on spacy (^3.6.1), en-core-sci-sm is forbidden.
So, because my-project depends on en_core_sci_sm (0.5.1) @ https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.1/en_core_sci_sm-0.5.1.tar.gz, version solving failed.
```

**Comment by dakinggg** [comment]
Hi, I just started looking at this. Will hopefully get new models up soon!

**Comment by dakinggg** [comment]
Hello, the 0.5.3 release is compatible with the latest spacy version.

**Comment by fehbari** [comment]
Great news. Appreciate it!
