### ISSUE TITLE
Entity linker sets redundant extensions on Span objects

### ISSUE THREAD

**Issue by JohnGiorgi** [allenai/scispacy#488]
Hi!

I noticed that the current entity linking code sets two extensions on span objects:

https://github.com/allenai/scispacy/blob/a5276f1829cf716362b1f151f2b513b9a00bc01f/scispacy/linking.py#L83-L85

but they appear to store exactly the same KB IDs:

https://github.com/allenai/scispacy/blob/a5276f1829cf716362b1f151f2b513b9a00bc01f/scispacy/linking.py#L134-L135

Is this a workaround for something, or can it be removed? I need to serialize a bunch of docs to disk so I am after anything I can remove to make them smaller. Happy to open a PR if in fact one of these extensions on the `Span` can be dropped.

**Comment by dakinggg** [comment]
This is not needed for anything. It is there for backwards compat, as we changed the name at some point. Would be ok to remove now I think.

**Comment by JohnGiorgi** [comment]
Cool, PR'd it!
