### ISSUE TITLE
Module for scispacy not working 

### ISSUE THREAD

**Issue by Akkun4** [allenai/scispacy#503]
Hey, I am new to the topic of nlp so please bear with me if this issue sounds mundane. Scispacy was successfully installed. All the modules for spacy are working. However no of the scispacy modules are working for me. Probably the issue is with the version. Can someone please let me know which versions are required for modules en_ner_bionlp13cg_md and en_ner_bc5cdr_md, EntityLinker, ulms? Or how to solve the issue for the above? I am using linux terminal and jupyter notebook.

**Comment by dakinggg** [comment]
Anyone will need more information to help you. How did you create your environment? What are you trying to run? What does it mean when you say "not working"?
