### ISSUE TITLE
SciSpacy Python 3.11 Installation Fails / Broken nmslib dependency

### ISSUE THREAD

**Issue by ksaadDE** [allenai/scispacy#504]
**python3 -m pip install scispacy**

bin/python  (venv)
--> Python 3.11.6

bin/pip --version (venv)
--> 3.11.6

```pip
Building wheel for nmslib (pyproject.toml)
include -I/usr/include/python3.11 -c nmslib.cc -o build/temp.linux-x86_64-cpython-311/nmslib.o -O3 -march=native -fopenmp -DVERSION_INFO=\"2.1.1\" -std=c++14 -fvisibility=hidden
python3.11/site-packages/pybind11/include/pybind11/attr.h:310:20: Err: »const struct pybind11::detail::function_record
error: command '/usr/bin/gcc' failed with exit code 
Failed to build nmslib
ERROR: Could not build wheels for nmslib, which is required to install pyproject.toml-based projects
```

**Comment by ksaadDE** [comment]
Luckily enough, nobody needs to install the entire scispacy library to just obtain the Abbreviation Extraction utility :)  https://github.com/allenai/scispacy/blob/main/scispacy/abbreviation.py

Just in case someone needs it as well.

**Comment by mp-lunartree-bio** [comment]
Has anyone figured out a work-around for this for the functionalities which require  scispacy or even nmslib?

**Comment by dakinggg** [comment]
Hi, you may have some luck with this workaround here: https://github.com/allenai/scispacy/issues/473#issuecomment-1590443024

**Comment by ddofer** [comment]
My workaround was to install everything in Python/anaconda 3.9. Annoying, but it works

**Comment by ulc0** [comment]
@dakinggg Do you have a workaround for Databricks ML? I've run out of tricks, I cannot get nmslib to install on 3.11 or 3.10

**Comment by dakinggg** [comment]
Based on https://github.com/allenai/scispacy/issues/520#issue-2438749767, I was able to get it working on both windows and wsl with python 3.11, by installing with `mamba`. Could others on this thread try that and let me know if it works? If so, I will update the installation instructions.

**Comment by dakinggg** [comment]
I've added a known support matrix to the readme for nmslib, so going to go ahead and close this issue.
