### ISSUE TITLE
export_umls_json.py failing

### ISSUE THREAD

**Issue by ethanhkim** [allenai/scispacy#509]
Hi! I noticed that while I was trying to build my own Linker, the script [export_umls_json.py](https://github.com/allenai/scispacy/blob/main/scripts/export_umls_json.py) is currently failing, and may have been for the past 10 months. Traceback below:

```
  Traceback (most recent call last):
    File "/dir/to/project/export_umls_json.py", line 115, in <module>
      main(args.meta_path, args.output_path, args.lang, args.source, args.non_suppressed)
  TypeError: main() takes from 2 to 4 positional arguments but 5 were given
```

Commenting out the last argument (lines 109-113) doesn't resolve the issue as well, creating an empty jsonl file.

For now, I'm using the previous commit's code but the current script may need to be reverted. Thanks!

**Comment by dakinggg** [comment]
Ah looks like a mistake in the last pr that touched that file! Would you be interested in opening a PR to fix it?

**Comment by dakinggg** [comment]
Thank you!
