### ISSUE TITLE
pip install scispacy > ERROR: Failed cleaning build dir for nmslib

### ISSUE THREAD

**Issue by science-labs-f** [allenai/scispacy#518]
Running Python 3.11.2 
![Screenshot 2024-07-15 at 11 00 27](https://github.com/user-attachments/assets/095e0ef0-5eb1-4a62-b9ac-54812ce16856)
What can I do?

**Comment by science-labs-f** [comment]
Solved with Python 3.10.10. On mac Intel here. Had a successful build of nmslib.

**Comment by dakinggg** [comment]
Hey @science-labs-f, would you be able to try out https://github.com/allenai/scispacy/issues/520#issue-2438749767 for python 3.11? Looking to see if it works for others.

**Comment by science-labs-f** [comment]
I am sorry Daniel, but can't make tie for it. Good luck!

------------------
Frederik Feys
Sent with [Proton Mail](https://proton.me/) secure email.
