### ISSUE TITLE
It fails installation scipy<1.11

### ISSUE THREAD

**Issue by ainilaha** [allenai/scispacy#521]
Collecting scipy<1.11 (from scispacy)
  Using cached scipy-1.9.3.tar.gz (42.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]

**Comment by dakinggg** [comment]
Hi @ainilaha, please share more about your installation setup. What command did you  run? What is the full error? What environment are you installing in? This project doesn't have a pyproject.toml, so I suspect you are installing a different package.

**Comment by JSchmie** [comment]
I encountered the same issue while using Conda. It appears that Conda now defaults to Python 3.12.*, which is causing the problem. To resolve this, I downgraded my Python version to 3.9.19, and it worked perfectly.

In the `setup.py` of scispacy, it specifies `python>=3.6`, leading pip to attempt an installation even though it is no longer compatible with the latest Python version.

Hope this helps!
