### ISSUE TITLE
Update RxNorm Entity Linker Data

### ISSUE THREAD

**Issue by ulc0** [allenai/scispacy#522]
Greetings SciSpacy fans!

We have almost successfully run a UMLS update (nmslib issues and all!) in an Azure Databricks Python 3.11 environment.

The code says the process is only for UMLS and MESH.

How can we refresh RxNorm? Is it some sort of hidden parameter? 

Thanks

-Kate
CDC Data Hub

**Comment by dakinggg** [comment]
I believe the export_umls_json.py script is used to produce all of the linker variants, with the --source argument. Is that not working?

**Comment by ulc0** [comment]
umls_util/read_umls_concepts seems to be hardcoded to the UMLS metathesaurus, not the RXNORM. I can probably create a "read_rxnorm_concepts" by reverse engineering the published linker data

**Comment by ulc0** [comment]
> I believe the export_umls_json.py script is used to produce all of the linker variants, with the --source argument. Is that not working?

So the UMLS linker is a superset of the RXNorm linker? So in theory I do not have to refresh the rxnorm linker if I have refreshed the umls linker?
