### ISSUE TITLE
Evaluate how difficult feature parity with MetamapLite is

### ISSUE THREAD

**Issue by DeNeutoy** [allenai/scispacy#66]
- [ ] Term normalisation
- [ ] Entity Linking
- [ ] Negation Detection

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6080672/

**Comment by kaushikacharya** [comment]
@DeNeutoy 
In the Conclusion section of your paper, your team has mentioned negation detection as a future work.
Has the work on "Negation Detection" feature started?

As per my knowledge, these are the following algorithms for negation detection in clinical notes:

- MetaMap/ MetaMapLite uses variation of [NegEx](https://metamap.nlm.nih.gov/Docs/MM_2013_ReleaseNotes.pdf).
- [NegBio](https://github.com/ncbi-nlp/NegBio) uses patterns in dependency parsing.

Is anything similar planned for negation detection in scispacy? Or are you planning a different approach?

**Comment by danielkingai2** [comment]
Someone else created a spacy pipe based on the NegEx algorith, here: https://github.com/jenojp/negspacy. I haven't tried it, but you should be able to just use it with scispacy.

**Comment by MichalMalyska** [comment]
@kaushikacharya @dakinggg I think the best resource for that would be medspacy: https://github.com/medspacy/medspacy
It's a step-up from just NegEx
