### ISSUE TITLE
No module named 'scispacy.custom_sentence_segmenter'; 'scispacy' is not a package

### ISSUE THREAD

**Issue by sakibshaik** [allenai/scispacy#78]
I am getting following error:
Traceback (most recent call last):
  File "scispacy.py", line 2, in <module>
    import scispacy
  File "/Users/shai26/office/spacy/scispacy/scispacy.py", line 5, in <module>
    nlp = spacy.load("en_core_sci_sm")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spacy/__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spacy/util.py", line 114, in load_model
    return load_model_from_package(name, **overrides)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spacy/util.py", line 134, in load_model_from_package
    cls = importlib.import_module(name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/en_core_sci_sm/__init__.py", line 7, in <module>
    from scispacy.custom_sentence_segmenter import combined_rule_sentence_segmenter
ModuleNotFoundError: No module named 'scispacy.custom_sentence_segmenter'; 'scispacy' is not a package

**Comment by danielkingai2** [comment]
Hi! Sorry you are having trouble getting setup. I am not able to reproduce this issue in a clean environment. Could you list the exact steps you took to install? For comparison, here is what I did:
1. `conda create -n scispacy_install python=3.6`
1. `conda activate scispacy_install`
1. `pip install scispacy`
1. `pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.1.0/en_core_sci_sm-0.1.0.tar.gz`
```
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> nlp = spacy.load('en_core_sci_sm')
```

**Comment by danielkingai2** [comment]
Looking again, my guess is that you skipped step 3. Is that possible?

**Comment by sakibshaik** [comment]
Hi Daniel,

I am not using Conda, i am trying to setup without any virtual environment.

steps i followed was 3 and 4 from above.

Environment details:
Python 3.6.8
scispacy: 0.1.0
spacy: 2.0.18

**Comment by danielkingai2** [comment]
The easiest solution is probably to use a virtual environment. That being said, my guess is that you are somehow running your program `scispacy.py` from an environment that does not have the packages installed. Possibly your `pip` and `python` installations are not connected. If you would still prefer to not use a virtual environment, could you share the output of these commands?
1. `which -a pip`
1. `which -a python`
1. `pip list`
1. the last couple lines of `brew doctor`

**Comment by sakibshaik** [comment]
which -a pip : /usr/local/bin/pip3
which -a python: /usr/local/bin/python3
pip list:`Package         Version
--------------- ----------
awscli          1.16.111
botocore        1.12.101
certifi         2018.11.29
chardet         3.0.4
colorama        0.3.9
conllu          1.2.2
cymem           2.0.2
cytoolz         0.9.0.1
dill            0.2.9
docutils        0.14
en-core-sci-sm  0.1.0
idna            2.8
jmespath        0.9.4
msgpack         0.5.6
msgpack-numpy   0.4.3.2
murmurhash      1.0.2
numpy           1.16.1
pip             18.1
plac            0.9.6
preshed         2.0.1
pyasn1          0.4.5
python-dateutil 2.8.0
PyYAML          3.13
regex           2018.1.10
requests        2.21.0
rsa             3.4.2
s3transfer      0.2.0
scispacy        0.1.0
setuptools      40.6.2
six             1.12.0
spacy           2.0.18
thinc           6.12.1
toolz           0.9.0
tqdm            4.31.1
ujson           1.35
urllib3         1.24.1
wrapt           1.10.11`

Last few lines brew doctor: 
 /usr/local/include/node/v8-platform.h
  /usr/local/include/node/v8-profiler.h
  /usr/local/include/node/v8-testing.h
  /usr/local/include/node/v8-util.h
  /usr/local/include/node/v8-value-serializer-version.h
  /usr/local/include/node/v8-version-string.h
  /usr/local/include/node/v8-version.h
  /usr/local/include/node/v8.h
  /usr/local/include/node/v8config.h
  /usr/local/include/node/zconf.h
  /usr/local/include/node/zlib.h

**Comment by danielkingai2** [comment]
This seems like an issue with your python setup rather than with this package specifically. Rather than trying to debug your python install over github, the easiest thing here would be for you to setup a virtual environment (instructions for this are also in the readme). Is this something that you could try out?

**Comment by sakibshaik** [comment]
Sure, it makes sense to use Virtual environment.. Thanks for helping

**Comment by danielkingai2** [comment]
Great, feel free to reach out again if you are still having issues!

**Comment by sakibshaik** [comment]
@danielkingai2 , still struggling after installing conda

`Traceback (most recent call last):
  File "scispacy.py", line 1, in <module>
    import scispacy
  File "/Users/shai26/office/spacy/scispacy/scispacy.py", line 4, in <module>
    nlp = spacy.load("en_core_sci_sm")
  File "/Users/shai26/anaconda3/envs/scispacy/lib/python3.6/site-packages/spacy/__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "/Users/shai26/anaconda3/envs/scispacy/lib/python3.6/site-packages/spacy/util.py", line 114, in load_model
    return load_model_from_package(name, **overrides)
  File "/Users/shai26/anaconda3/envs/scispacy/lib/python3.6/site-packages/spacy/util.py", line 134, in load_model_from_package
    cls = importlib.import_module(name)
  File "/Users/shai26/anaconda3/envs/scispacy/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/shai26/anaconda3/envs/scispacy/lib/python3.6/site-packages/en_core_sci_sm/__init__.py", line 7, in <module>
    from scispacy.custom_sentence_segmenter import combined_rule_sentence_segmenter
ModuleNotFoundError: No module named 'scispacy.custom_sentence_segmenter'; 'scispacy' is not a package`

**Comment by danielkingai2** [comment]
Inside your conda environment,
could you show the output of 
```python```
and then at the python repl that opens
```import spacy
import scispacy```

**Comment by sakibshaik** [comment]
Here  : 
`Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> import scispacy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shai26/office/spacy/scispacy/scispacy.py", line 27, in <module>
    nlp = spacy.load("en_ner_craft_md")
  File "/Users/shai26/anaconda3/envs/scispacy/lib/python3.6/site-packages/spacy/__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "/Users/shai26/anaconda3/envs/scispacy/lib/python3.6/site-packages/spacy/util.py", line 114, in load_model
    return load_model_from_package(name, **overrides)
  File "/Users/shai26/anaconda3/envs/scispacy/lib/python3.6/site-packages/spacy/util.py", line 134, in load_model_from_package
    cls = importlib.import_module(name)
  File "/Users/shai26/anaconda3/envs/scispacy/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/shai26/anaconda3/envs/scispacy/lib/python3.6/site-packages/en_ner_craft_md/__init__.py", line 7, in <module>
    from scispacy.custom_sentence_segmenter import combined_rule_sentence_segmenter
ModuleNotFoundError: No module named 'scispacy.custom_sentence_segmenter'; 'scispacy' is not a package`

**Comment by danielkingai2** [comment]
Also output of `conda list`? Sorry, this is difficult to debug over github and seems to be an issue with your python setup rather than the package itself as I am not able to reproduce your issue.

**Comment by sakibshaik** [comment]
seems like, i understand it can be a pain over github.. i am also trying to figure out.. but in vain .. here is the list of conda list

`# packages in environment at /Users/shai26/anaconda3/envs/scispacy:
#
# Name                    Version                   Build  Channel
awscli                    1.16.113                  <pip>
botocore                  1.12.103                  <pip>
ca-certificates           2019.1.23                     0
certifi                   2018.11.29               py36_0
chardet                   3.0.4                     <pip>
colorama                  0.3.9                     <pip>
conllu                    1.2.2                     <pip>
cymem                     2.0.2                     <pip>
cytoolz                   0.9.0.1                   <pip>
dill                      0.2.9                     <pip>
docutils                  0.14                      <pip>
en-core-sci-sm            0.1.0                     <pip>
en-ner-craft-md           0.1.0                     <pip>
idna                      2.8                       <pip>
jmespath                  0.9.4                     <pip>
libcxx                    4.0.1                hcfea43d_1
libcxxabi                 4.0.1                hcfea43d_1
libedit                   3.1.20181209         hb402a30_0
libffi                    3.2.1                h475c297_4
msgpack                   0.5.6                     <pip>
msgpack-numpy             0.4.3.2                   <pip>
murmurhash                1.0.2                     <pip>
ncurses                   6.1                  h0a44026_1
numpy                     1.16.2                    <pip>
openssl                   1.1.1b               h1de35cc_0
pip                       19.0.3                   py36_0
plac                      0.9.6                     <pip>
preshed                   2.0.1                     <pip>
pyasn1                    0.4.5                     <pip>
python                    3.6.8                haf84260_0
python-dateutil           2.8.0                     <pip>
PyYAML                    3.13                      <pip>
readline                  7.0                  h1de35cc_5
regex                     2018.1.10                 <pip>
requests                  2.21.0                    <pip>
rsa                       3.4.2                     <pip>
s3transfer                0.2.0                     <pip>
scispacy                  0.1.0                     <pip>
setuptools                40.8.0                   py36_0
six                       1.12.0                    <pip>
spacy                     2.0.18                    <pip>
sqlite                    3.26.0               ha441bb4_0
thinc                     6.12.1                    <pip>
tk                        8.6.8                ha441bb4_0
toolz                     0.9.0                     <pip>
tqdm                      4.31.1                    <pip>
ujson                     1.35                      <pip>
urllib3                   1.24.1                    <pip>
wheel                     0.33.1                   py36_0
wrapt                     1.10.11                   <pip>
xz                        5.2.4                h1de35cc_4
zlib                      1.2.11               h1de35cc_3`

**Comment by danielkingai2** [comment]
Ok lets try this
```
conda deactivate
pip uninstall en-core-sci-sm
pip uninstall en-ner-craft-md
pip uninstall scispacy
pip uninstall spacy
```
Then verify that you can't import spacy or scispacy
Then create a new conda environment with
```
conda create -n test_env python=3.6
conda activate test_env
```
Then verify that you still can't import spacy or scispacy
Then
```
pip install scispacy
```
Then try to import it

**Comment by danielkingai2** [comment]
@sakibshaik and from inside the conda env, run
```
which python
which pip
```

**Comment by sakibshaik** [comment]
here it is : 
`Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> import scispacy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: bad magic number in 'scispacy': b'\x03\xf3\r\n'`

which python:
/Users/shai26/anaconda3/envs/test_env/bin/python

which pip:
/Users/shai26/anaconda3/envs/test_env/bin/pip

**Comment by sakibshaik** [comment]
deleted the ".pyc" files from the directory, and its working now!!

**Comment by danielkingai2** [comment]
*phew* nicely done. Sorry that was so difficult and glad you have gotten it working :)

**Comment by sakibshaik** [comment]
Thanks a ton.. really appreciate your help.. keep up the good work.. cheers..
