### ISSUE TITLE
How to know what type of entity is extracted (e.g drug name,indication,treatment)using scispacy?

### ISSUE THREAD

**Issue by aaryaa** [allenai/scispacy#79]

**Comment by brilliantblu** [comment]
import spacy
nlp = spacy.load("en_ner_craft_md")
text = "Myeloid derived suppressor cells (MDSC) are immature myeloid cells with immunosuppressive activity. " \
       "They accumulate in tumor-bearing mice and humans with different types of cancer, including hepatocellular carcinoma (HCC)."
doc = nlp(text)
for ent in doc.ents:
       print(ent, ent.label_)

**Comment by aaryaa** [comment]
Hi Ravina,
Thank you for the information. I am trying to extract drug name and disease
name from a sentence. So which model will be best fit for this and also can
you give me a clearity what GGP and CL entity mean in medical terms.
Thank you so much for your help.
-Regards,
Sujeet

**Comment by danielkingai2** [comment]
You will want to experiment with different models and combine predictions from multiple, limiting to the types that are of interest to you. For example, diseases are in the BC5CDR,  As for what GGP and CL are specifically, there are more details about the craft corpus here: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-13-161. But loosely speaking, GGP is genes and proteins, and CL is cell types. @DeNeutoy can you confirm what GGP is? It isn't directly listed in the CRAFT documentation.

Additionally, our paper about scispacy is now on arxiv: https://arxiv.org/pdf/1902.07669.pdf

**Comment by aaryaa** [comment]
Thank you.

**Comment by aaryaa** [comment]
Does the CHEMICAL label mean a medicine or drug  ?
This is the output i got using "en_ner_bc5cdr_md" model

Acetaminophen CHEMICAL
paracetamol CHEMICAL
loss of DISEASE
deaths DISEASE
deaths DISEASE
infectious diseases DISEASE
nutritional deficiencies.a (HCC).'doc DISEASE

**Comment by danielkingai2** [comment]
The annotation guidelines for the BC5CDR data (which that model was trained on can) can be found here: https://www.nlm.nih.gov/mesh/trees.html. and that document says that a chemical is defined as the Drugs and Chemicals [D] branch of Mesh 2015, which can be found here: https://www.nlm.nih.gov/mesh/trees.html

**Comment by aaryaa** [comment]
Got it. Thank you

**Comment by victoriastuart** [comment]
Concept annotation / terminology in the CRAFT corpus (ontology-based):

https://www.ncbi.nlm.nih.gov/pubmed/22776079
https://bmcbioinformatics.biomedcentral.com/track/pdf/10.1186/1471-2105-13-161

```
CL          cell line
ChEBI       chemical entities of biological interest
EG          Entrez gene
GO BP       Gene Ontology biological processes
GO CC       Gene Ontology cellular components
GO MF       Gene Ontology molecular functions
NCBITaxon   NCBI taxonomy
PRO         protein
SO          Sequence Ontology
```
![CRAFT_corpus_concepts_terminology](https://user-images.githubusercontent.com/2575920/69473213-09c6ba00-0d68-11ea-8114-b22f456f5c75.png)

**Comment by hbeychaner** [comment]
> You will want to experiment with different models and combine predictions from multiple, limiting to the types that are of interest to you. For example, diseases are in the BC5CDR, but drug names might appear in multiple models. Possibly start with BC5CDR and see if that works for you. As for what GGP and CL are specifically, there are more details about the craft corpus here: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-13-161. But loosely speaking, GGP is genes and proteins, and CL is cell types. @DeNeutoy can you confirm what GGP is? It isn't directly listed in the CRAFT documentation.
> 
> Additionally, our paper about scispacy is now on arxiv: https://arxiv.org/pdf/1902.07669.pdf

Potentially related issue: is there easy to access documentation for entity labels within scispaCy? Labels are working fine, but I need a way to provide a short description of what each label means, since some aren't self-explanatory. I realize I can go to all the papers, but does this documentation already exist somewhere?

**Comment by danielkingai2** [comment]
Hi, this documentation does not currently exist anywhere outside of the original dataset papers. Perhaps it should. If you end up compiling this information, we would welcome a contribution to the README or something with the info. Also, if there is any particular entity label you are unable to figure out, feel free to leave a question and I can try to find the info. Thanks!

**Comment by issayatim** [comment]
hi aaryaa, 

I have the same question like you. I am trying to extract drug name and disease
name  Or drug/protein from a sentence using scispacy. so which model will be best fit for this? can you please?
has anyone got the code for this association/relation?

i have done the below table. i need similar output with columns for drug / protein relation /disease

![187511971_480226719702340_7097340215165296287_n](https://user-images.githubusercontent.com/84497052/118938744-a49d5600-b957-11eb-8a01-19b5185884a1.png)

**Comment by aaryaa** [comment]
you can use standford core nlp.

https://github.com/mridultuteja/Custom-Labelled-NER-tagger
