### ISSUE TITLE
Replace NER

### ISSUE THREAD

**Issue by gabrieledicerbo** [allenai/scispacy#82]
Hi, 

I'm trying to add one of your pre-trained NER to one of the main models but unfortunately, I run into an error. Can somebody help?

This is what I did: 

nlp = spacy.load("en_core_sci_sm")
ner = spacy.load("en_ner_bionlp13cg_md")

nlp.replace_pipe('ner',ner.pipeline[0][1])

Then run on some text:

doc = nlp(text)

When I ask for entities I get the error:

doc.ents

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-30-2631206314ab> in <module>()
----> 1 doc.ents
doc.pyx in spacy.tokens.doc.Doc.ents.__get__()
span.pyx in spacy.tokens.span.Span.__cinit__()
ValueError: [E084] Error assigning label ID 7634832301877222523 to span: not in StringStore.

If I try to just add a new NER to the model with:

nlp.add_pipe(ner.pipeline[0][1], 'new_ner')

the kernel crashes...

Thank you!

**Comment by danielkingai2** [comment]
spaCy model components need to use the vocab that they were created with. Each of the models has a different vocab and so components from separate models will not be compatible. There may be a workaround here that I don't know about, but for now I think what we would suggest for this use case is running the pipelines separately and then attempting to merge their outputs yourself by iterating over the resulting docs together. For example, this might look something like running en_core_sci_sm on text, then running en_ner_bionlp13cg_md on text, then iterating over the two resulting docs together and labeling entities on one doc using the other.

**Comment by gabrieledicerbo** [comment]
Oh you are absolutely right! Thank you very much!

**Comment by danielkingai2** [comment]
I haven't tested this at all, but it looks like you might be able to do something like here: https://github.com/explosion/spaCy/issues/1752 with vocab=False. Let us know if you experiment with this and get it to work! (I might poke around with it also)

**Comment by gabrieledicerbo** [comment]
I was trying to do the same things in explosion/spaCy#1752 but it doesn't work for the issue you pointed out. how would you use vocab=False? It seems to me that I cannot detach vocab from a NER model (vocab is used even for the tokenizer.) maybe I need to re-do the training of the NERs fixing the vocabulary at the beginning, for example the one "en_core_sci_md"

**Comment by gabrieledicerbo** [comment]
unfortunately the command ner_A.from_disk('ner_A', vocab=False) does not work. you cannot call vocab=False and I can't find a way of detaching vocab to a NER model. it maybe the case that one need to retrain the NER using a fixed vocab, for example the one from "en_core_sci_md". Let me know if you have a better idea!
